import crypto from "node:crypto";
import { actionPolicy, assertCommandAuthorized } from "./policy.js";

const now=()=>new Date().toISOString();
const primaryProductIds=new Set(["inbox","followup","phone"]);
const base={
  organization:{id:"org_curacao_auto",organizationId:"org_curacao_auto",name:"Curaçao Auto Center",contact:"Tim Curaçao",branch:"Autobedrijf",status:"active",source:"demo",demoMode:true,createdAt:now(),updatedAt:now()},
  implementation:{id:"impl_001",organizationId:"org_curacao_auto",name:"AI Telefoniste",state:"integration_setup",progress:58,targetLiveDate:"2026-08-03",status:"active",source:"demo",demoMode:true,createdAt:now(),updatedAt:now()},
  commercial:{proposalId:"prop_001",proposalVersion:"2.1",status:"preview_ready",priceSetup:5000,priceMonthly:2500,currency:"EUR",validUntil:"2026-08-03",paidAt:null,paymentReference:null,activatedAt:null,demoMode:true,createdAt:now(),updatedAt:now()},
  preview:{status:"ready",environment:"isolated_sandbox",expiresAt:"2026-08-19",knowledgeSources:3,assumptions:2,externalWrites:false,realCustomerData:false,capabilities:["Onderhoudsafspraken aannemen","Proefritten kwalificeren","Voorraadvragen beantwoorden","Menselijke overdracht starten"],restrictions:["Geen bindende prijzen afgeven","Geen productieacties vóór livegoedkeuring","Geen secrets of ruwe tokens zichtbaar voor agents"],demoMode:true},
  entitlement:{id:"ent_impl_001",organizationId:"org_curacao_auto",productId:"phone",plan:"scale_demo",status:"active",environment:"demo",features:["personal_preview","requirements","legal_acceptance","sandbox_checkout","secure_data_room","integration_testing"],usageLimits:{workflowRuns:100,voiceMinutes:0,externalWrites:0},effectiveAt:now(),expiresAt:"2026-08-19",source:"demo_contract",demoMode:true},
  workflow:{id:"wf_implementation_001",organizationId:"org_curacao_auto",name:"Preview naar veilige implementatie",version:"1.0.0",state:"preview_ready",currentStep:"requirements_and_legal",exitCondition:"ready_for_authorized_activation",externalWrites:false,demoMode:true,updatedAt:now()},
  understanding:{summary:"Curaçao Auto Center wil gemiste en drukke contactmomenten omzetten naar een complete intake, afspraak of menselijke vervolgactie.",sources:["Consult A · commerciële doelen","Consult B · processen en uitzonderingen","Openbare bedrijfsinformatie"],challenges:["Telefoon wordt tijdens piekdrukte niet altijd opgenomen","Service- en verkoopvragen onderbreken het team","Informatie komt niet altijd compleet in agenda en CRM"],goals:["Meer bereikbaarheid zonder extra receptiedruk","Volledige intake vóór een medewerker overneemt","Afspraken en vervolgacties aantoonbaar vastleggen"],channels:["Telefonie","E-mail","WhatsApp","Website"],systems:["Serviceagenda","GoHighLevel CRM","Telefonie","Gmail"],boundaries:["Geen bindende prijs toezeggen","Boze of onduidelijke klant met context overdragen","Naam, telefoon en kenteken bevestigen vóór een afspraak"],openAssumptions:["Definitieve agenda-scopes nog bevestigen","Fallbackteam buiten openingstijden nog aanwijzen"]},
  products:[
    {id:"inbox",slug:"ai-inboxmedewerker",name:"AI Inboxmedewerker",baseProduct:"AI Inboxmedewerker",eyebrow:"DIGITALE KLANTVRAGEN",recommended:true,selected:false,promise:"Behandelt e-mail, WhatsApp, chat en formulieren vanuit één afgesproken werkwijze.",channels:["E-mail","WhatsApp","Chat"],capabilities:["Berichten classificeren","Vragen beantwoorden","Intake compleet maken","Ticket, afspraak of overdracht voorbereiden"]},
    {id:"followup",slug:"ai-leadopvolger",name:"AI Leadopvolger",baseProduct:"AI Leadopvolger",eyebrow:"LEADS EN OFFERTES",recommended:true,selected:false,promise:"Volgt leads, offertes en no-shows consequent op tot een duidelijke uitkomst.",channels:["WhatsApp","E-mail","SMS","Telefonie"],capabilities:["Nieuwe leads direct ontvangen","Opvolgsequenties uitvoeren","Reacties en bezwaren herkennen","Pipeline en volgende stap bijwerken"]},
    {id:"phone",slug:"ai-telefoniste",name:"AI Telefoniste",baseProduct:"AI Telefoniste",eyebrow:"AANBEVOLEN · TELEFONISCHE BEREIKBAARHEID",recommended:true,selected:true,promise:"Neemt service- en verkoopcalls aan, vraagt door, plant en schakelt volgens afspraken door.",channels:["Telefonie","Agenda","CRM"],capabilities:["Oproepen aannemen","Service- en verkoopvragen uitvragen","Afspraken plannen","Menselijke overdracht starten"]},
    {id:"crm",slug:"autopilots-crm",name:"Autopilots CRM",baseProduct:"Autopilots CRM",eyebrow:"VERBINDENDE LAAG",recommended:false,selected:false,promise:"Brengt klantcontext, gesprekken, afspraken, taken en AI-acties samen.",channels:["CRM","Pipelines","Rapportage"],capabilities:["Klantcontext centraliseren","Pipelines beheren","Taken verdelen","AI- en mensacties verbinden"]},
    {id:"leads",slug:"leadsmachine-ai",name:"Leadsmachine AI",baseProduct:"Leadsmachine AI",eyebrow:"VAN CAMPAGNE NAAR KLANT",recommended:false,selected:false,promise:"Verbindt campagnes, landingspagina, intake, opvolging en CRM-resultaat.",channels:["Advertenties","Landingspagina","CRM"],capabilities:["Campagnes structureren","Leads kwalificeren","Direct opvolgen","Resultaat meten"]}
  ],
  legal:{terms:{id:"terms_2026_01",title:"Algemene Voorwaarden",version:"2026.1",hash:"sha256:demo-terms-2026-1",accepted:false,acceptedAt:null},privacy:{id:"privacy_2026_01",title:"Privacyverklaring",version:"2026.1",hash:"sha256:demo-privacy-2026-1",acknowledged:false,acknowledgedAt:null},dpa:{id:"dpa_2026_01",title:"Verwerkersovereenkomst",version:"2026.1",hash:"sha256:demo-dpa-2026-1",accepted:false,acceptedAt:null},marketing:{accepted:false,acceptedAt:null}},
  dataRoom:{status:"locked_until_payment",classification:"confidential",fields:[{id:"field_contact",label:"Implementatiecontact",value:"",status:"missing",sensitivity:"normal"},{id:"field_fallback",label:"Fallback telefoonnummer",value:"",status:"missing",sensitivity:"personal"},{id:"field_retention",label:"Gewenste bewaartermijn",value:"90 dagen",status:"review",sensitivity:"normal"}],documents:[],secrets:[],lastSecurityScan:null},
  requirements:["Openingstijden en feestdagen","Tone of voice: vriendelijk en direct","Onderhoud, proefritten en voorraadvragen","Altijd naam, telefoon en kenteken bevestigen","Geen bindende prijzen afgeven","Bij frustratie of twijfel overdragen aan het team"].map((title,index)=>({id:`req_${index+1}`,organizationId:"org_curacao_auto",title,status:index<4?"confirmed":"open",comment:"",source:"consult",demoMode:true,createdAt:now(),updatedAt:now()})),
  onboarding:["Bedrijfsgegevens","Openingstijden","Medewerkers en fallback","Serviceagenda","CRM","Telefonie","Kennisbank","Tone of voice","Uitzonderingen","Privacy-afspraken","Testcontacten","Livegang akkoord"].map((title,index)=>({id:`onb_${index+1}`,organizationId:"org_curacao_auto",title,status:index<5?"done":"open",owner:index%3===0?"Klant":"Autopilots",source:"demo",demoMode:true,createdAt:now(),updatedAt:now()})),
  integrations:[
    ["google","Google Calendar","connected","Agenda lezen en afspraken beheren"],["microsoft","Microsoft 365","available","Agenda en e-mail"],["ghl","GoHighLevel","connected","Contacten en opportunities"],["hubspot","HubSpot","available","Contacten en deals"],["crm","Generiek CRM","review","Beperkte API-koppeling"],["telnyx","Telefonie","testing","Inkomende testcalls"],["gmail","E-mail","available","Bevestigingen als concept"]
  ].map(([id,name,status,scope])=>({id:`int_${id}`,organizationId:"org_curacao_auto",name,status,scope,environment:"test",health:status==="connected"?"healthy":"not_tested",owner:"Curaçao Auto Center",source:"demo",demoMode:true,createdAt:now(),updatedAt:now()})),
  tasks:[{id:"task_1",organizationId:"org_curacao_auto",priority:"P2",title:"Agenda permissies bevestigen",impact:"Implementatie wacht op toestemming",proposal:"Bevestig beperkte agenda-toegang",evidence:"OAuth scopes: calendar.events",owner:"Tim",status:"open",source:"demo",demoMode:true,createdAt:now(),updatedAt:now()}],
  agents:["Intake Agent","Requirements Agent","Demo Builder","Solution Architect","Voice Builder","Integration Agent","QA Agent","Security Reviewer","Deployment Agent","Monitoring Agent","Human Escalation Router"].map((name,index)=>({id:`agent_${index+1}`,organizationId:"org_curacao_auto",name,version:"1.0",status:index<4?"running":"ready",task:index<4?["Consult structureren","Requirements controleren","Demo personaliseren","Koppelingen plannen"][index]:"Wacht op opdracht",tools:index===5?["connector-catalog","sandbox"]:["demo-store"],budget:"€2,50",approval:index>6?"required":"not_required",source:"demo",demoMode:true,createdAt:now(),updatedAt:now()})),
  approvals:[{id:"approval_live_001",organizationId:"org_curacao_auto",type:"implementation_activation",requester:"Deployment Agent",target:"impl_001",rationale:"Productie-activatie na succesvolle readiness gates",evidence:["requirements","legal_versions","payment_reference","readiness_tests"],risk:"R3",reversible:false,outgoingData:"Geen in deze demo",blastRadius:"Alleen Curaçao Auto Center",deadline:"2026-08-03",status:"not_ready",contextVersion:1,decision:null,decidedBy:null,decidedAt:null,requestedAt:null,demoMode:true}],
  executions:[],
  usageLedger:[{id:"usage_seed_001",organizationId:"org_curacao_auto",workflowId:"wf_implementation_001",agentId:"agent_3",provider:"demo_engine",metric:"sandbox_build",quantity:1,unit:"run",unitCostCents:3140,totalCostCents:3140,quality:"measured_demo",sourceReference:"demo-seed",adjustsEntryId:null,createdAt:now()}],
  metricRegistry:[
    {id:"metric_verified_activation",name:"Veilig geactiveerde implementaties",formula:"Aantal implementaties met juridische acceptatie, geverifieerde demo-betaling en menselijke approval",source:"workflow + approvals",freshness:"direct",owner:"Delivery"},
    {id:"metric_cost_per_activation",name:"Kosten per geactiveerde implementatie",formula:"Som usage ledger / veilig geactiveerde implementaties",source:"usage ledger",freshness:"direct",owner:"FinOps"},
    {id:"metric_human_attention",name:"Menselijke aandacht nodig",formula:"Open taken + pending approvals",source:"tasks + approvals",freshness:"direct",owner:"Operations"}
  ],
  audit:[{id:"audit_1",organizationId:"org_curacao_auto",actor:"System",action:"Demo-omgeving aangemaakt",reason:"Veilige salesdemonstratie",result:"Geslaagd",environment:"demo",risk:0,source:"demo",demoMode:true,createdAt:now(),updatedAt:now()}]
};

export class DemoStore{
  constructor(){this.reset()}
  reset(){this.data=structuredClone(base);this.seen=new Map();return this.snapshot()}
  snapshot(){const data=structuredClone(this.data);data.metrics=this.metrics();return data}
  snapshotFor(context){this.assertScope(context);const data=this.snapshot();data.viewer={id:context.id,name:context.name,email:context.email,role:context.role,organizationId:context.organizationId};if(context.role==="customer"){delete data.tasks;delete data.agents;delete data.approvals;delete data.executions;delete data.usageLedger;delete data.metricRegistry;delete data.metrics.humanAttention;data.audit=data.audit.filter(item=>item.actorRole!=="internal").slice(0,25)}return data}
  command(key,action,payload={},context){if(!key)throw new Error("Idempotency key ontbreekt");this.assertScope(context);assertCommandAuthorized(context,action);const scopedKey=`${context.organizationId}:${key}`;if(this.seen.has(scopedKey))return structuredClone(this.seen.get(scopedKey));const startedAt=Date.now();let result;
    if(action==="requirement.confirm")result=this.update("requirements",payload.id,{status:"confirmed",comment:payload.comment||""});
    else if(action==="onboarding.toggle"){const item=this.find("onboarding",payload.id);result=this.update("onboarding",payload.id,{status:item.status==="done"?"open":"done"})}
    else if(action==="integration.connect")result=this.update("integrations",payload.id,{status:"connected",health:"healthy"});
    else if(action==="integration.test")result=this.update("integrations",payload.id,{health:"healthy"});
    else if(action==="task.resolve")result=this.update("tasks",payload.id,{status:payload.decision||"approved"});
    else if(action==="agent.toggle"){const item=this.find("agents",payload.id);if(item.status==="stopped")throw new Error("Gestopte agent vereist menselijke heractivatie");result=this.update("agents",payload.id,{status:item.status==="paused"?"running":"paused"})}
    else if(action==="agent.kill")result=this.update("agents",payload.id,{status:"stopped",task:"Gestopt via kill switch"});
    else if(action==="legal.accept")result=this.acceptLegal(payload);
    else if(action==="payment.complete")result=this.completePayment(payload);
    else if(action==="dataroom.field")result=this.updateDataField(payload);
    else if(action==="dataroom.document")result=this.addDocument(payload);
    else if(action==="dataroom.secret")result=this.addSecret(payload);
    else if(action==="product.select")result=this.selectProduct(payload);
    else if(action==="lifecycle.advance")result=this.advanceLifecycle();
    else if(action==="approval.decide")result=this.decideApproval(payload,context);
    else if(action==="demo.reset"){result=this.reset();this.seen.set(scopedKey,{item:{status:"reset"}});return {item:{status:"reset"}}}else throw new Error("Onbekende demoactie");
    const policy=actionPolicy[action];
    this.data.audit.unshift({id:crypto.randomUUID(),organizationId:context.organizationId,actor:context.email,actorRole:context.role,action,reason:payload.reason||"Actie in veilige demo",result:"Geslaagd",environment:"demo",risk:policy.risk,source:"demo",demoMode:true,createdAt:now(),updatedAt:now()});
    this.recordExecution({key:scopedKey,action,context,startedAt,policy});
    const response={item:result,audit:this.data.audit[0],execution:this.data.executions[0]};this.seen.set(scopedKey,response);return structuredClone(response)}
  assertScope(context){if(!context?.organizationId)throw this.forbidden("Organisatiescope ontbreekt");if(context.organizationId!==this.data.organization.id)throw this.forbidden("Organisatie valt buiten deze tenant")}
  forbidden(message){const error=new Error(message);error.status=403;return error}
  find(collection,id){const item=this.data[collection].find(x=>x.id===id);if(!item)throw new Error("Item niet gevonden");return item}
  update(collection,id,patch){const item=this.find(collection,id);Object.assign(item,patch,{updatedAt:now()});return structuredClone(item)}
  acceptLegal(payload){const allowed=["terms","privacy","dpa","marketing"];if(!allowed.includes(payload.type))throw new Error("Onbekend juridisch document");if(this.data.commercial.status==="implementation_activated"&&payload.type!=="marketing")throw new Error("Contractacceptatie is na activatie vergrendeld");const item=this.data.legal[payload.type];const accepted=payload.accepted!==false;if(payload.type==="privacy"){item.acknowledged=accepted;item.acknowledgedAt=accepted?now():null}else{item.accepted=accepted;item.acceptedAt=accepted?now():null}item.actor="demo@curacao-auto.example";item.proposalVersion=this.data.commercial.proposalVersion;return structuredClone(item)}
  completePayment(){if(this.data.commercial.status==="implementation_activated")return structuredClone(this.data.commercial);const {terms,privacy,dpa}=this.data.legal;if(!terms.accepted||!privacy.acknowledged||!dpa.accepted)throw new Error("Lees en accepteer eerst alle verplichte documenten");this.data.commercial.status="implementation_activated";this.data.commercial.paidAt=now();this.data.commercial.activatedAt=this.data.commercial.paidAt;this.data.commercial.paymentReference="demo_checkout_verified";this.data.commercial.updatedAt=now();this.data.dataRoom.status="open";this.data.workflow.state="implementation_activated";this.data.workflow.currentStep="secure_onboarding";this.data.workflow.updatedAt=now();return structuredClone(this.data.commercial)}
  requireActivated(){if(this.data.commercial.status!=="implementation_activated")throw new Error("Secure Data Room opent pas na betaling")}
  updateDataField(payload){this.requireActivated();const field=this.data.dataRoom.fields.find(x=>x.id===payload.id);if(!field)throw new Error("Veld niet gevonden");field.value=String(payload.value||"").slice(0,250);field.status=field.value?"submitted":"missing";field.updatedAt=now();return structuredClone(field)}
  addDocument(payload){this.requireActivated();const name=String(payload.name||"").replace(/[^a-zA-Z0-9._ -]/g,"").slice(0,80);if(!/^[a-zA-Z0-9][a-zA-Z0-9._ -]*\.(pdf|docx|csv|txt)$/i.test(name))throw new Error("Alleen een geldig PDF-, DOCX-, CSV- of TXT-bestand toegestaan");const item={id:crypto.randomUUID(),name,status:"quarantined_and_scanned",size:"demo",encrypted:true,tenantIsolated:true,uploadedAt:now()};this.data.dataRoom.documents.push(item);this.data.dataRoom.lastSecurityScan=now();return structuredClone(item)}
  addSecret(payload){this.requireActivated();if(typeof payload.value!=="string"||payload.value.length<4)throw new Error("Vul een geldige secret in");const label=String(payload.label||"").trim().slice(0,60);if(!label)throw new Error("Naam van de toegang ontbreekt");const item={id:crypto.randomUUID(),label,reference:`vault://org_curacao_auto/${crypto.randomUUID()}`,masked:"••••••••••••",status:"stored",readableByAgents:false,rotatable:true,createdAt:now()};this.data.dataRoom.secrets.push(item);return structuredClone(item)}
  selectProduct(payload){if(this.data.commercial.status==="implementation_activated")throw new Error("Gekocht product kan niet meer worden gewijzigd");if(!primaryProductIds.has(payload.id))throw new Error("Product kan niet als primaire AI Medewerker worden geselecteerd");const product=this.data.products.find(x=>x.id===payload.id);if(!product)throw new Error("Product niet gevonden");this.data.products.forEach(x=>x.selected=x.id===product.id);this.data.implementation.name=product.name;this.data.implementation.updatedAt=now();this.data.preview.capabilities=[...product.capabilities];return structuredClone(product)}
  advanceLifecycle(){const transitions={integration_setup:["ready_to_build",68],ready_to_build:["testing",78],testing:["ready_for_review",90]};const next=transitions[this.data.implementation.state];if(!next)throw new Error("Menselijke livegoedkeuring vereist");if(next[0]==="ready_for_review")this.assertApprovalGates();this.data.implementation.state=next[0];this.data.implementation.progress=next[1];this.data.implementation.updatedAt=now();if(next[0]==="ready_for_review"){const approval=this.data.approvals[0];approval.status="pending";approval.requestedAt=now();approval.contextVersion+=1;this.data.workflow.currentStep="human_activation_approval";this.data.workflow.updatedAt=now()}return structuredClone(this.data.implementation)}
  assertApprovalGates(){if(this.data.requirements.some(item=>item.status!=="confirmed"))throw new Error("Niet alle requirements zijn bevestigd");if(this.data.commercial.status!=="implementation_activated")throw new Error("Een geverifieerde demo-betaling ontbreekt");if(this.data.dataRoom.fields.some(field=>field.status!=="submitted"))throw new Error("De Secure Data Room bevat nog open velden");if(!this.data.dataRoom.documents.length)throw new Error("Een gescand implementatiedocument ontbreekt");if(!this.data.dataRoom.secrets.length)throw new Error("Een vault-referentie voor de koppeling ontbreekt")}
  decideApproval(payload,context){const approval=this.data.approvals.find(item=>item.id===payload.id);if(!approval)throw new Error("Approval niet gevonden");if(approval.status!=="pending")throw new Error("Approval is niet beschikbaar");if(Number(payload.contextVersion)!==approval.contextVersion)throw new Error("Approvalcontext is gewijzigd");if(!["approved","rejected"].includes(payload.decision))throw new Error("Ongeldige approvalbeslissing");approval.status=payload.decision;approval.decision=payload.decision;approval.decidedBy=context.email;approval.decidedAt=now();if(payload.decision==="approved"){this.data.implementation.state="ready_for_authorized_activation";this.data.implementation.progress=96;this.data.workflow.state="ready_for_authorized_activation";this.data.workflow.currentStep="external_activation_blocked"}else{this.data.implementation.state="changes_requested";this.data.workflow.state="changes_requested";this.data.workflow.currentStep="remediation"}this.data.workflow.updatedAt=now();return structuredClone(approval)}
  recordExecution({key,action,context,startedAt,policy}){const costCents={"integration.test":1,"lifecycle.advance":4,"approval.decide":2,"agent.toggle":1,"agent.kill":1}[action]||2;const execution={id:crypto.randomUUID(),organizationId:context.organizationId,workflowId:"wf_implementation_001",action,idempotencyKey:key,status:"succeeded",risk:policy.risk,reversible:policy.reversible,actorId:context.id,startedAt:new Date(startedAt).toISOString(),completedAt:now(),durationMs:Math.max(0,Date.now()-startedAt),costCents,evidence:[`audit:${this.data.audit[0].id}`],demoMode:true};this.data.executions.unshift(execution);this.data.usageLedger.push({id:crypto.randomUUID(),organizationId:context.organizationId,workflowId:execution.workflowId,agentId:null,provider:"demo_engine",metric:"workflow_command",quantity:1,unit:"command",unitCostCents:costCents,totalCostCents:costCents,quality:"measured_demo",sourceReference:execution.id,adjustsEntryId:null,createdAt:now()})}
  metrics(){const safeActivation=this.data.workflow.state==="ready_for_authorized_activation"?1:0;const totalCostCents=this.data.usageLedger.reduce((sum,item)=>sum+item.totalCostCents,0);return{verifiedActivations:safeActivation,totalCostCents,costPerActivationCents:safeActivation?totalCostCents:null,humanAttention:this.data.tasks.filter(item=>item.status==="open").length+this.data.approvals.filter(item=>item.status==="pending").length,quality:"measured_demo",updatedAt:now()}}
}
