import type { KnowledgeArticle } from "./knowledgeArticles";

type Sections = KnowledgeArticle["sections"];

export const articleExpansions: Record<string, Sections> = {
  "wat-is-een-ai-medewerker": [
    { id: "architectuur-in-praktijk", eyebrow: "Architectuur", title: "De zichtbare conversatie is maar één laag van het systeem", paragraphs: ["Onder de chat- of telefooninterface draait een orkestratielaag die instructies, kennisbronnen, tools en gespreksstatus samenbrengt. De AI hoeft niet alle bedrijfsinformatie in één prompt te krijgen. Relevante informatie wordt per stap opgehaald en alleen noodzakelijke acties worden beschikbaar gesteld.", "Een tool hoort klein en voorspelbaar te zijn. ‘Beheer het CRM’ is te breed; ‘zoek klant op e-mailadres’, ‘controleer beschikbaarheid’ en ‘maak een concepttaak’ zijn beter te valideren. De applicatie controleert invoer, rechten en resultaat voordat de klant een bevestiging krijgt.", "Observability maakt zichtbaar welke bron, tool en route zijn gebruikt. Daardoor kan een team een fout terugbrengen tot bronkwaliteit, classificatie, bedrijfsregel, koppeling of overdracht in plaats van alleen de laatste AI-zin te beoordelen."], bullets: ["Conversatielaag voor natuurlijke interactie", "Kennislaag met beheerde bronnen", "Regellaag voor harde grenzen", "Toollaag voor lees- en schrijfacties", "Monitoring en menselijke fallback"] },
    { id: "businesscase", eyebrow: "Businesscase", title: "Beoordeel waarde op klantuitkomst en herstelwerk", paragraphs: ["Het aantal volledig geautomatiseerde gesprekken is geen volledige businesscase. Een AI-medewerker kan al waarde leveren door een intake compleet te maken, wachttijd te verkorten of een medewerker met betere context te laten starten. Andersom kan een hoog automatiseringspercentage verborgen herstelwerk veroorzaken.", "Leg vóór de pilot de huidige route vast: volume, wachttijd, overdrachten, ontbrekende velden, gemiste afspraken en handmatige registratie. Kies vervolgens enkele kwaliteitsmaten die het proces echt vertegenwoordigen, zoals complete intake, succesvolle agenda-write en terecht uitgevoerde escalatie.", "Vergelijk na livegang dezelfde definities en bekijk uitzonderingen afzonderlijk. Zo voorkom je dat seizoensdrukte, een andere campagne of veranderde openingstijden ten onrechte als AI-effect worden gepresenteerd."] }
  ],
  "wat-is-een-ai-telefoniste": [
    { id: "gespreksontwerp", eyebrow: "Gespreksontwerp", title: "Een goed telefoongesprek heeft tempo, bevestiging en herstel", paragraphs: ["Voice vraagt ander ontwerp dan chat. Een beller ziet geen knoppen of eerder antwoord en kan de agent onderbreken. Stel daarom één gerichte vraag tegelijk, bevestig kritieke gegevens en geef hoorbaar aan wanneer een agenda of dossier wordt gecontroleerd.", "Namen, e-mailadressen, kentekens, postcodes en tijden zijn foutgevoelig. Laat de agent deze gegevens herhalen of via een veilig alternatief kanaal bevestigen. Een natuurlijk klinkende stem mag nooit belangrijker worden dan een correct geregistreerde afspraak.", "Ontwerp ook herstelzinnen. Na twee misverstanden hoort de agent niet dezelfde vraag luider te herhalen, maar de formulering te veranderen, een keuze te bieden of een medewerker in te schakelen."], bullets: ["Korte beurten en natuurlijke interruptie", "Bevestiging van kritieke gegevens", "Stilte- en time-outgedrag", "Herstel na transcriptiefout", "Directe mensroute"] },
    { id: "telefonieproductie", eyebrow: "Productie", title: "Telefonie, agenda en CRM bepalen samen de betrouwbaarheid", paragraphs: ["De voice-agent moet passen in nummerplan, openingstijden, wachtrijen en doorschakeling. Bepaal wat gebeurt bij piekbelasting, anonieme bellers, terugbellen, verbroken verbinding en uitval van de AI-dienst.", "Agenda-integratie vraagt meer dan vrije tijden oplezen. Behandel tijdzone, duur, medewerker, locatie, buffers, dubbele boeking en annulering. Bevestig alleen nadat het agendasysteem de reservering succesvol heeft teruggegeven.", "Sla in CRM of ticketing niet automatisch het volledige transcript op wanneer een korte feitelijke samenvatting en gestructureerde velden volstaan. Dit beperkt privacyrisico en maakt de overdracht voor medewerkers sneller bruikbaar."] }
  ],
  "chatbot-voicebot-ai-medewerker-verschil": [
    { id: "keuzematrix", eyebrow: "Keuzematrix", title: "Kies het kanaal op taak, omgeving en benodigde zekerheid", paragraphs: ["Chat werkt goed wanneer een klant links, afbeeldingen of precieze tekst wil teruglezen. Voice past bij snelheid, toegankelijkheid en situaties waarin typen lastig is. E-mail blijft logisch voor langere context en documenten. Een AI-medewerker kan dezelfde bedrijfsrol over meerdere kanalen uitvoeren.", "Beoordeel per taak hoeveel informatie moet worden verzameld, hoe foutgevoelig die informatie is en of de klant rustig kan controleren. Een serienummer van twintig tekens kan schriftelijk beter werken; een eenvoudige afspraakwijziging kan telefonisch sneller zijn.", "Kies niet uitsluitend op kanaalvoorkeur van het bedrijf. Geef de klant een alternatief wanneer bereikbaarheid, beperking, omgeving of gevoeligheid daar aanleiding toe geeft."] },
    { id: "hybride-ontwerp", eyebrow: "Hybride route", title: "De sterkste klantreis wisselt gecontroleerd van kanaal", paragraphs: ["Een voicebot kan na toestemming een beveiligde link sturen voor foto’s of documentatie. Een chatbot kan een terugbelverzoek maken wanneer nuance mondeling beter werkt. Kanaalwisseling hoort de context mee te nemen zonder persoonsgegevens onnodig in URL’s of onbeveiligde berichten te plaatsen.", "Bepaal welk systeem de gespreksstatus bewaart. Zonder gedeelde context vraagt ieder kanaal opnieuw naar naam, onderwerp en afspraak. Met een gemeenschappelijk dossier kan een medewerker zien wat bevestigd is en wat nog openstaat.", "Test de volledige hybride route, inclusief niet geopende link, verkeerd telefoonnummer en klant die later via een ander kanaal terugkomt. De ervaring is zo sterk als de zwakste overgang."] }
  ],
  "wat-is-ai-leadopvolging": [
    { id: "opvolglogica", eyebrow: "Opvolglogica", title: "Een sequence is een beslisroute, geen stapel herinneringen", paragraphs: ["Iedere stap hoort een reden te hebben: eerste reactie, ontbrekende informatie, afspraakvoorstel of heractivatie. Het volgende bericht hangt af van kanaalrespons, status, toestemming, openingstijd en eerdere acties. Zodra het doel is bereikt, stopt de sequence.", "Laat de AI niet onbeperkt variëren in aanbod of belofte. Productvoorwaarden, korting, servicegebied en beschikbaarheid komen uit beheerde bronnen en harde regels. Vrije taal helpt bij relevantie; commerciële grenzen blijven voorspelbaar.", "Synchroniseer uitschrijvingen, afwijzingen en contactvoorkeuren tussen campagne, inbox en CRM. Een lead die ‘geen interesse’ zegt, mag niet via een tweede kanaal automatisch opnieuw worden benaderd alsof er niets is gebeurd."], bullets: ["Trigger en doel per sequence", "Stopvoorwaarden", "Kanaal- en toestemmingsregels", "Eigenaar en escalatie", "CRM-status na iedere relevante stap"] },
    { id: "kwaliteit-lead", eyebrow: "Kwaliteit", title: "Snelle opvolging telt alleen als de reactie inhoudelijk verder helpt", paragraphs: ["Een automatische ontvangstbevestiging kan verwachtingen managen, maar is nog geen kwalificatie. Een bruikbare reactie herkent de vraag, verzamelt relevante context en maakt de volgende stap concreet.", "Meet daarom niet alleen time-to-first-response. Kijk naar bereikbare leads, complete kwalificatie, geplande afspraken, terechte diskwalificatie, menselijke correcties en leads die na een verkeerde sequence afhaken.", "Laat sales terugkoppelen welke context ontbrak of verkeerd was. Die feedback hoort in bronbeheer, gesprekslogica en evaluatieset terecht te komen, niet alleen in losse opmerkingen bij een lead."] }
  ],
  "hoe-snel-nieuwe-lead-opvolgen": [
    { id: "serviceniveau", eyebrow: "Serviceniveau", title: "Definieer snelheid per bron, urgentie en openingstijd", paragraphs: ["Een demo-aanvraag met gekozen product vraagt een andere route dan een gedownloade gids. Leg per bron vast wanneer eerste ontvangst, inhoudelijke reactie en menselijke opvolging verwacht worden. Communiceer buiten openingstijd eerlijk wanneer een medewerker beschikbaar is.", "Gebruik wachtrijen met prioriteit in plaats van één universele timer. Bestaande klant, spoed, hoge intentie en ontbrekende toestemming kunnen ieder een andere behandeling vragen. De regel moet uitlegbaar zijn voor sales en service.", "Monitor uitzonderingen zoals ongeldige contactgegevens, dubbele leads en CRM-uitval. Anders lijkt de gemiddelde reactietijd goed terwijl juist waardevolle aanvragen in een foutstatus blijven hangen."] },
    { id: "experiment", eyebrow: "Meten", title: "Test responstijd zonder causaliteit te verzinnen", paragraphs: ["Vergelijk groepen alleen wanneer bron, campagne, aanbod, moment en kwalificatie voldoende vergelijkbaar zijn. Een groep met warmere leads zal vaker converteren, ook wanneer de opvolging even snel is.", "Gebruik eerst operationele maten: tijd tot betekenisvolle reactie, percentage binnen het afgesproken venster en aandeel leads zonder eigenaar. Koppel daarna aan afspraken of omzet met een duidelijk attributievenster.", "Een experiment moet ook klantdruk bewaken. Meer contactmomenten kunnen een korte termijnreactie verhogen en tegelijk irritatie of uitschrijvingen veroorzaken. Neem stopwoorden en contactfrequentie daarom mee in de evaluatie."] }
  ],
  "roi-automatische-leadopvolging-berekenen": [
    { id: "businesscase-bandbreedte", eyebrow: "Rekenmodel", title: "Maak aannames zichtbaar en werk met een bandbreedte", paragraphs: ["Zet maandelijks leadvolume, huidige bereikbaarheid, afspraakratio, showratio, brutobijdrage en opvolgtijd in afzonderlijke variabelen. Bereken een conservatief, verwacht en ambitieus scenario in plaats van één precies getal.", "Tel implementatie, licenties, communicatie, monitoring en menselijke uitzonderingen mee. Vermijd dubbele baten: tijdsbesparing en extra capaciteit kunnen dezelfde vrijgekomen uren beschrijven en mogen niet zonder uitleg bij elkaar worden opgeteld.", "Scheid directe omzet van operationele waarde zoals snellere service of completere data. Beide kunnen belangrijk zijn, maar vragen een andere bewijsvoering en beslistermijn."], bullets: ["Incrementele afspraken × showratio × brutobijdrage", "Bespaarde minuten × realistische uurwaarde", "Min alle vaste en variabele kosten", "Apart: risico, kwaliteit en klantimpact"] },
    { id: "validatie-roi", eyebrow: "Validatie", title: "Vervang businesscase-aannames na livegang door waarnemingen", paragraphs: ["Leg vóór de pilot vast waar iedere maat vandaan komt: CRM, agenda, telefonie of urenregistratie. Definieer wat een bereikbare lead, afspraak en geslaagde opvolging is.", "Controleer of extra afspraken werkelijk door de nieuwe route komen en niet door meer advertentiebudget of seizoen. Gebruik cohort- of gefaseerde vergelijking waar dat praktisch en verantwoord kan.", "Herbereken de businesscase na een representatieve periode. Als kwaliteit of overdracht achterblijft, kan optimalisatie waardevoller zijn dan direct opschalen naar meer kanalen of meer autonomie."] }
  ],
  "ai-email-whatsapp-websitechat": [
    { id: "omnichannel-context", eyebrow: "Kanaalcontext", title: "Centraliseren betekent één klantbeeld, niet één identiek antwoord", paragraphs: ["E-mail ondersteunt lange context en bijlagen, WhatsApp korte asynchrone berichten en chat een actieve websitesessie. Dezelfde klantintentie vraagt per kanaal andere lengte, timing, bevestiging en toestemming.", "Gebruik een gedeelde conversatie-ID of klantkoppeling wanneer identiteit betrouwbaar is vastgesteld. Voeg onbekende afzenders niet automatisch samen op basis van alleen naam. Een verkeerde koppeling kan informatie tussen klanten lekken.", "Bewaar kanaalbron en originele klantvraag bij samenvatting en actie. Zo ziet een medewerker of een afspraak via chat is bevestigd en op welk kanaal vervolgcommunicatie verwacht wordt."], bullets: ["Kanaalspecifieke tone of voice", "Identiteits- en koppelregels", "Gedeelde status en eigenaar", "Toestemming en opt-out per kanaal", "Bijlagen en gevoelige data apart behandelen"] },
    { id: "operationeel-inbox", eyebrow: "Operatie", title: "Ontwerp wachtrijen voor berichten die de AI niet afrondt", paragraphs: ["Niet ieder bericht hoeft automatisch beantwoord te worden. De AI kan classificeren, gegevens verzamelen en een concept maken. Klachten, uitzonderingen en gevoelige documenten gaan met prioriteit naar een passende medewerker.", "Maak zichtbaar waarom iets in de wachtrij staat en welke vervolgstap nodig is. Zonder reden en ontbrekende velden verschuift de AI alleen sorteerwerk naar het team.", "Voorkom dubbele antwoorden wanneer een medewerker en agent tegelijk werken. Gebruik lock-, concept- of eigenaarsstatus en stop automatische follow-up zodra menselijke behandeling begint."] }
  ],
  "hoe-werken-ai-en-crm-samen": [
    { id: "integratiepatronen", eyebrow: "Integratie", title: "Kies bewust tussen directe API, middleware en gecontroleerde wachtrij", paragraphs: ["Een directe API-koppeling is snel maar kan bedrijfslogica verspreiden over meerdere agents. Middleware centraliseert validatie, mapping en observability. Een wachtrij maakt retries en menselijke beoordeling mogelijk wanneer een actie niet onmiddellijk hoeft.", "Gebruik webhooks voor relevante statuswijzigingen, maar valideer herkomst en voorkom dubbele verwerking. Geef ieder event een unieke sleutel en bewaar de laatste verwerkingsstatus.", "Ontwerp versiebeheer voor velden en pipelines. Een CRM-beheerder die een statusnaam verandert, mag niet stil alle AI-routes breken. Test integraties na schemawijzigingen en leveranciersupdates."], bullets: ["Schema-validatie", "Idempotency en retries", "Authenticatie en minimale scopes", "Versie- en wijzigingsbeheer", "Traceerbare foutstatus"] },
    { id: "datakwaliteit", eyebrow: "Datakwaliteit", title: "AI maakt vervuilde CRM-data sneller zichtbaar — en soms sneller groter", paragraphs: ["Wanneer dubbele klanten, vrije statusvelden en ontbrekende eigenaars bestaan, kan automatisering deze inconsistentie opschalen. Begin met de objecten en velden van de gekozen route en bepaal wie ze beheert.", "Laat AI mogelijke matches of ontbrekende data voorstellen, maar gebruik deterministische regels voor unieke sleutels en toegestane waarden. Markeer afgeleide intentie of samenvatting anders dan door de klant bevestigde informatie.", "Meet write-fouten, correcties door medewerkers en records zonder eigenaar. Datakwaliteit is een productie-indicator, niet alleen een eenmalige migratietaak."] }
  ],
  "klantcontactprocessen-veilig-automatiseren": [
    { id: "procesdecompositie", eyebrow: "Procesontwerp", title: "Knip een klantreis op voordat je autonomie kiest", paragraphs: ["Een reparatiemelding bestaat uit ontvangst, identiteit, locatie, probleemtype, urgentiesignalen, planning, opdracht en bevestiging. Iedere stap heeft andere data, regels en impact. Automatisering hoeft niet op alle stappen hetzelfde niveau te hebben.", "Maak een beslisdiagram met normale route, ontbrekende informatie, conflict, systeemfout en menselijke escalatie. Beschrijf ook wie eigenaar is wanneer de route stopt.", "Kies daarna per stap tussen samenvatten, voorstellen, uitvoeren of overdragen. Zo kan een risicovolle klantreis toch gedeeltelijk veilig worden ondersteund zonder een fictieve keuze tussen volledig autonoom en volledig handmatig."], bullets: ["Startgebeurtenis", "Benodigde en bevestigde gegevens", "Beslisregels en verboden acties", "Systeemactie en controle", "Fallback met eigenaar"] },
    { id: "acceptatie", eyebrow: "Acceptatie", title: "Publiceer pas wanneer ook afwijkende routes voldoen", paragraphs: ["Een happy-pathdemo toont weinig over productie. Test tegenstrijdige antwoorden, ontbrekende dossiers, ongeldige postcodes, dubbele afspraken, ongepaste taal en uitgevallen koppelingen.", "Definieer kritieke fouten die livegang blokkeren, zoals informatie van de verkeerde klant, onterechte spoedverlaging of bevestiging van een niet-geboekte afspraak. Minder kritieke taalvariatie kan een ander herstelpad krijgen.", "Laat eindgebruikers beoordelen of overdrachten bruikbaar zijn. Een technisch juiste route kan operationeel falen wanneer de wachtrij niet wordt bekeken of de samenvatting essentiële context mist."] }
  ],
  "ai-medewerker-implementeren": [
    { id: "projectgovernance", eyebrow: "Governance", title: "Organiseer besluitvorming, wijzigingen en incidenten vóór livegang", paragraphs: ["Benoem naast de proceseigenaar een technische eigenaar en aanspreekpunt voor privacy en beveiliging. Leg vast wie bronnen mag wijzigen, wie model- of promptupdates goedkeurt en wie bij een incident autonomie kan beperken.", "Gebruik een wijzigingslog met reden, risicoklasse, tests en uitroldatum. Kleine tekstwijzigingen kunnen onverwacht toolgedrag beïnvloeden; behandel productie-instructies daarom als beheerde configuratie.", "Maak een incidentroute voor verkeerde informatie, datalek, foutieve systeemactie en uitval. Bewaar voldoende bewijs voor analyse zonder meer persoonsgegevens te loggen dan noodzakelijk."], bullets: ["RACI of duidelijke rolverdeling", "Versiebeheer en goedkeuring", "Regressietests", "Gefaseerde uitrol en terugweg", "Incident- en communicatieplan"] },
    { id: "leverancierskeuze", eyebrow: "Inkoop", title: "Beoordeel leveranciers op de hele levenscyclus", paragraphs: ["Vergelijk niet alleen demokwaliteit. Vraag naar dataregio, retentie, subverwerkers, beveiliging, beschikbaarheid, logging, export, modelupdates en beëindiging. Controleer welke claims contractueel worden gedragen.", "Voorkom sterke afhankelijkheid van één model door bedrijfsregels, bronnen en tooldefinities in eigen beheerde lagen te houden waar dat praktisch is. Portabiliteit hoeft niet absoluut te zijn, maar kritieke data en proceskennis moeten overdraagbaar blijven.", "Bereken kosten op complete gesprekken en acties, inclusief telefonie, transcriptie, modelgebruik, integratie, monitoring en menselijke fallback. Een lage tokenprijs zegt weinig over totale proceskosten."] }
  ],
  "verkeerde-ai-antwoorden-hallucinaties-voorkomen": [
    { id: "dreigingsmodel", eyebrow: "Security", title: "Behandel onbetrouwbare klantinput als data, niet als systeeminstructie", paragraphs: ["Een klantbericht, website of bijlage kan tekst bevatten die probeert instructies of geheimen te beïnvloeden. Scheid systeemregels, vertrouwde bronnen en onbetrouwbare inhoud technisch en conceptueel.", "Geef tools minimale rechten en laat gevoelige acties niet afhangen van vrije modeltekst. Valideer bestemmingen, identifiers, bedragen en veldwaarden in applicatielogica. Geheimen horen nooit in prompts of terugleesbare toolresultaten.", "Test prompt-injectie, data-exfiltratie, ongeautoriseerde klantwissel en misbruik van herhaalde requests. Combineer modelmaatregelen met normale beveiliging, authenticatie en rate limiting."], bullets: ["Vertrouwensgrenzen tussen bronnen", "Minimale rechten", "Input- en outputvalidatie", "Geen geheimen in context", "Misbruikmonitoring en incidentroute"] },
    { id: "foutbudget", eyebrow: "Kwaliteitsbeheer", title: "Bepaal per fouttype hoeveel risico acceptabel is", paragraphs: ["Niet iedere fout heeft dezelfde impact. Een onnatuurlijke formulering is anders dan een verkeerde prijs, klantverwisseling of onterechte veiligheidsinstructie. Maak categorieën en blokkades per route.", "Gebruik gouden voorbeelden, automatisch controleerbare regels en menselijke beoordeling samen. Controleer niet alleen gemiddelde scores; een zeldzame kritieke fout kan de route ongeschikt maken.", "Koppel productiemeldingen terug aan een oorzaak en test. Sluit een incident pas wanneer bron, prompt, tool of proces is aangepast en de regressietest aantoont dat de specifieke route is hersteld."] }
  ],
  "menselijke-overdracht-ai-klantcontact": [
    { id: "overdrachtsontwerp", eyebrow: "Serviceontwerp", title: "Ontwerp warme, asynchrone en noodoverdracht afzonderlijk", paragraphs: ["Bij warme overdracht blijft de klant in het gesprek en krijgt de medewerker direct context. Asynchrone overdracht maakt een taak of ticket met verwachting. Een noodroute kan vaste instructies en directe prioriteit vereisen. Eén generieke knop dekt deze situaties niet.", "Bepaal kanaal, wachttijd en klantbevestiging per route. Als direct doorschakelen niet lukt, moet de klant weten of opnieuw bellen nodig is of dat het team contact opneemt.", "Laat de agent geen emotionele of juridische interpretatie als feit doorgeven. Gebruik feitelijke gebeurtenissen, letterlijke klantbehoefte en bevestigde gegevens, met afleidingen duidelijk gemarkeerd."], bullets: ["Type overdracht", "Ontvangend team", "Urgentie en serviceniveau", "Contextpakket", "Klantbevestiging en fallback"] },
    { id: "capaciteit", eyebrow: "Capaciteit", title: "Menselijke fallback vraagt echte bezetting en eigenaarschap", paragraphs: ["Een organisatie kan niet beloven dat altijd een mens beschikbaar is zonder planning. Stem openingstijden, wachtrijcapaciteit en prioriteiten af op verwachte overdracht en pieken.", "Monitor wachttijd na overdracht, herhaalcontact, ontbrekende context en teruggestuurde taken. Zo zie je of de AI te vroeg, te laat of naar het verkeerde team escaleert.", "Gebruik verbeteringen niet alleen om het overdrachtspercentage te verlagen. Een terechte escalatie die sneller wordt opgepakt kan meer klantwaarde leveren dan autonome afhandeling met onzeker resultaat."] }
  ],
  "ai-avg-geautomatiseerd-klantcontact": [
    { id: "transparantie-avg", eyebrow: "Transparantie", title: "Leg in lagen uit wat er met klantgegevens gebeurt", paragraphs: ["Een korte melding in chat of telefoon kan naar begrijpelijke aanvullende privacy-informatie verwijzen. Beschrijf doel, categorieën gegevens, ontvangers, bewaartermijnen, rechten en contactpunt passend bij de concrete verwerking.", "Maak onderscheid tussen noodzakelijke verwerking voor het klantverzoek en eventueel hergebruik voor analyse of verbetering. Een brede zin dat gegevens ‘voor AI’ worden gebruikt, is onvoldoende om de werkelijke doelen te begrijpen.", "Controleer ook interne transparantie. Medewerkers moeten weten wanneer een veld of samenvatting door AI is afgeleid en hoe zij een fout kunnen corrigeren of melden."], bullets: ["Informatie op het moment dat het relevant is", "Volledige privacy-informatie bereikbaar", "AI-afleidingen herkenbaar", "Rechten uitvoerbaar in alle systemen"] },
    { id: "privacy-test", eyebrow: "Controle", title: "Test privacymaatregelen als onderdeel van de acceptatie", paragraphs: ["Controleer met testaccounts of een gebruiker alleen passende gegevens ziet, een klantwisseling geen context meeneemt en logs geen geheimen bevatten. Test verwijdering, retentie en export in plaats van alleen beleid te documenteren.", "Simuleer een verzoek om inzage of correctie. Het team moet gegevens in gesprek, CRM, transcriptie en eventuele zoekindex kunnen vinden en uitleggen wat feit en AI-inschatting is.", "Herhaal de beoordeling wanneer een nieuw kanaal, model, bron, leverancier of doel wordt toegevoegd. Een eerdere AVG-analyse dekt niet automatisch een wezenlijk andere verwerking."] }
  ],
  "ai-act-chatbot-melden-dat-het-ai-is": [
    { id: "interfacepatronen", eyebrow: "Interface", title: "Transparantie moet ook overeind blijven bij realistische interactie", paragraphs: ["Test de melding bij een geopende widget, deeplink, terugkerende sessie, doorgestuurd gesprek en snelle onderbreking. Een tekst die alleen in een welkomstscherm staat kan verdwijnen voordat de klant haar waarneemt.", "Gebruik naast woorden eventueel een consistent visueel of auditief signaal, maar laat een pictogram niet de enige informatie dragen. Houd taal begrijpelijk voor het publiek en vermijd juridische afkortingen in de eerste boodschap.", "Wanneer AI alleen een medewerker ondersteunt en niet rechtstreeks met de klant communiceert, kan een andere analyse gelden. Documenteer daarom de werkelijke rol en gebruikerservaring in plaats van alleen de technologie te labelen."], bullets: ["Vroege en duidelijke melding", "Rol en mogelijkheden afgebakend", "Menselijke route zichtbaar", "Toegankelijke formulering", "Hercontrole bij kanaal- of rolwissel"] },
    { id: "compliance-proces", eyebrow: "Compliance", title: "Maak van transparantie een beheerd proces", paragraphs: ["Wijs een eigenaar aan voor meldingen, privacy-informatie en menselijke routes. Bewaar versies en testresultaten, zodat wijzigingen in interface of regelgeving aantoonbaar worden verwerkt.", "Controleer naast de AI Act ook AVG, consumentenrecht, toegankelijkheid en sectorspecifieke regels. De toepasselijke verplichtingen hangen af van rol, publiek, gegevens en impact.", "Plan voor dit artikel en de eigen implementatie een korte review rond 2 augustus 2026 en na publicatie van definitieve Europese richtlijnen. Gebruik bij twijfel actuele juridische expertise; deze kennisbank is geen individueel advies."] }
  ],
  "voice-ai-conversational-ai-ontwikkelingen-2026": [
    { id: "evaluatie-voice", eyebrow: "Evaluatie", title: "Test voice op meer dan natuurlijkheid en latency", paragraphs: ["Maak een audio-evaluatieset met accenten, achtergrondgeluid, interrupties, stiltes, cijfers, namen en correcties. Beoordeel transcript, intentie, vervolgvragen, toolargumenten en uiteindelijke systeemactie afzonderlijk.", "Meet tijd tot eerste hoorbare reactie en onderbreekbaarheid, maar ook het aandeel gesprekken waarin de klant moet herhalen. Lage latency met veel herstelbeurten voelt niet snel.", "Controleer stemconsistentie en passende toon zonder menselijke identiteit te suggereren. Meld duidelijk dat het AI is en bied een werkende mensroute, zeker wanneer stemmen natuurlijker worden."], bullets: ["Audio- en transcriptiekwaliteit", "Beurtwisseling en interruptie", "Taakvoltooiing", "Tool- en CRM-resultaat", "Overdracht en klantinspanning"] },
    { id: "architectuurkeuze-voice", eyebrow: "Architectuurkeuze", title: "Bouw voor modelontwikkeling zonder iedere maand de klantreis te herschrijven", paragraphs: ["Houd telefonie, bedrijfsregels, tools, evaluaties en logging zoveel mogelijk los van één specifiek model. Zo kan een modelwissel gericht worden getest zonder CRM-rechten of serviceregels opnieuw uit te vinden.", "Gebruik feature flags of gefaseerde routing om nieuwe modellen met een beperkte groep scenario’s te vergelijken. Controleer prijs, latency, taalgedrag, toolgebruik en datavoorwaarden in de actuele regio.", "Volg officiële documentatie voor beschikbaarheid. Een aangekondigd model, preview of ChatGPT-functie is niet automatisch een ondersteunde API voor productie. Leg bij tijdgevoelige keuzes altijd de controledatum vast."] }
  ]
};
