import type { KnowledgeArticle } from "./knowledgeArticles";
import { articleExpansions } from "./articleExpansions";

type ArticleInput = Omit<KnowledgeArticle, "label" | "published" | "modified" | "reviewed" | "author"> & Partial<Pick<KnowledgeArticle, "label" | "published" | "modified" | "reviewed" | "author">>;

const checked = "Gecontroleerd op 15 juli 2026";
const source = (label: string, href: string) => ({ label: `${label} · ${checked}`, href });
const openAiAgents = source("OpenAI — Agents guide", "https://developers.openai.com/api/docs/guides/agents");
const openAiTools = source("OpenAI — Using tools", "https://developers.openai.com/api/docs/guides/tools");
const openAiRealtime = source("OpenAI — Realtime and audio", "https://developers.openai.com/api/docs/guides/realtime");
const openAiSafety = source("OpenAI — Safety best practices", "https://developers.openai.com/api/docs/guides/safety-best-practices");
const openAiEvals = source("OpenAI — Evaluation best practices", "https://developers.openai.com/api/docs/guides/evaluation-best-practices");
const openAiFileSearch = source("OpenAI — File search", "https://developers.openai.com/api/docs/guides/tools-file-search");
const apAcmChatbots = source("Autoriteit Persoonsgegevens en ACM — menselijke route bij chatbots", "https://autoriteitpersoonsgegevens.nl/actueel/ap-en-acm-chatbot-mag-mens-niet-volledig-vervangen-bij-klantenservice");
const uwvKlantcontact = source("UWV — Factsheet klantcontact", "https://www.uwv.nl/nl/arbeidsmarktinformatie/sector/zakelijke-dienstverlening/factsheet-klantcontact");
const euAiLiteracy = source("Europese Commissie — AI literacy Q&A", "https://digital-strategy.ec.europa.eu/en/faqs/ai-literacy-questions-answers");
const apAiAvg = source("Autoriteit Persoonsgegevens — Algoritmes, AI en de AVG", "https://autoriteitpersoonsgegevens.nl/themas/algoritmes-ai/algoritmes-ai-en-de-avg");
const apGenerativeAi = source("Autoriteit Persoonsgegevens — verantwoorde inzet generatieve AI", "https://autoriteitpersoonsgegevens.nl/actueel/ap-gezamenlijke-keuzes-nodig-voor-verantwoorde-inzet-generatieve-ai");
const euAiAct = source("Europese Commissie — AI Act regulatory framework", "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai");
const euTransparency = source("Europese Commissie — concept-richtlijnen transparantie onder de AI Act", "https://digital-strategy.ec.europa.eu/en/consultations/consultation-draft-guidelines-transparency-obligations-under-ai-act");
const openAiVoice2026 = source("OpenAI — Advancing voice intelligence with new models in the API · 7 mei 2026", "https://openai.com/index/advancing-voice-intelligence-with-new-models-in-the-api/");
const openAiGptLive = source("OpenAI — Introducing GPT-Live · 8 juli 2026", "https://openai.com/index/introducing-gpt-live/");
const openAiSpeech = source("OpenAI — Speech to text", "https://developers.openai.com/api/docs/guides/speech-to-text");

const article = (input: ArticleInput): KnowledgeArticle => ({
  label: "AI Kennis",
  published: "2026-07-15",
  modified: "2026-07-15",
  reviewed: "2026-07-15",
  author: "Autopilots redactie",
  ...input
});

const clusterA: KnowledgeArticle[] = [
  article({
    slug: "wat-is-een-ai-medewerker",
    category: "AI-medewerkers",
    contentCluster: "AI-medewerkers en klantcontact",
    pillar: true,
    readTime: "11 min",
    title: "Wat is een AI-medewerker en wat kan deze voor een bedrijf doen?",
    accent: "voor een bedrijf doen?",
    cardTitle: "Wat is een AI-medewerker?",
    excerpt: "Een AI-medewerker begrijpt een klantvraag, verzamelt ontbrekende context en voert binnen afgesproken regels een concrete vervolgactie uit.",
    description: "Wat is een AI-medewerker? Lees hoe deze klantvragen verwerkt, CRM-acties uitvoert, grenzen bewaakt en samenwerkt met medewerkers.",
    intent: "Neutrale uitleg over wat een AI-medewerker is, hoe deze werkt en wanneer inzet zinvol is.",
    searchIntent: "informatief",
    primaryKeyword: "wat is een AI-medewerker",
    audience: "Ondernemers en teams die klantcontact, planning of opvolging willen verbeteren.",
    promise: "Je begrijpt de techniek, praktische mogelijkheden, grenzen en eerste implementatiestap.",
    conversion: "Kies één afgebakende klantreis om te onderzoeken.",
    keywords: ["wat is een AI-medewerker", "AI medewerker bedrijf", "digitale medewerker", "AI agent klantcontact", "AI medewerker CRM"],
    relatedArticles: ["wat-is-een-ai-telefoniste", "chatbot-voicebot-ai-medewerker-verschil", "ai-medewerker-implementeren", "menselijke-overdracht-ai-klantcontact"],
    relatedProducts: ["ai-inboxmedewerker", "ai-leadopvolger", "ai-telefoniste"],
    relatedNiches: ["autobedrijven", "installatietechniek", "vastgoedbeheerders"],
    summary: [
      "Een AI-medewerker is software die taal begrijpt, bedrijfsinformatie gebruikt en een afgebakende taak uitvoert, zoals intake, planning, opvolging of registratie.",
      "Het verschil met een losse chatbot zit in de systeemactie: een antwoord wordt bijvoorbeeld een afspraak, taak, ticket, CRM-update of complete overdracht.",
      "Betrouwbare inzet vraagt goedgekeurde kennis, harde bedrijfsregels, beperkte rechten, tests en een duidelijke route naar een mens."
    ],
    sections: [
      { id: "definitie", eyebrow: "Definitie", title: "Een AI-medewerker combineert taalbegrip met een afgebakende bedrijfsrol", paragraphs: ["Een AI-medewerker is geen juridisch nieuwe soort werknemer en ook geen algemeen digitaal brein. Het is een softwarematige rol rond een concreet proces. De rol kan een inkomende e-mail beoordelen, een beller gericht doorvragen, een lead opvolgen of een afspraak voorbereiden.", "De AI ontvangt input, herkent de bedoeling en bepaalt welke informatie nog ontbreekt. Daarna gebruikt de toepassing alleen de bronnen en tools die voor die taak beschikbaar zijn. Een model kan bijvoorbeeld een vraag begrijpen; de applicatie bepaalt of het klantgegevens mag lezen, een agenda mag controleren of een taak mag aanmaken.", "Het woord medewerker is dus vooral een praktische ontwerpkeuze. Het dwingt tot duidelijkheid over verantwoordelijkheid: welke taak hoort bij de rol, welke kwaliteit verwachten we en wanneer neemt een mens het over?"] },
      { id: "werking", eyebrow: "Werking", title: "Van klantvraag naar vervolgactie in vijf controleerbare stappen", paragraphs: ["Eerst komt een vraag binnen via telefoon, e-mail, WhatsApp, chat of formulier. De AI classificeert niet alleen het kanaal, maar vooral de intentie: informatie, afspraak, offerte, storing, klacht of wijziging.", "Vervolgens verzamelt de AI de minimale gegevens die nodig zijn. Bij een daklekkage zijn locatie, actief water en veiligheid relevant. Bij een proefrit gaat het om voertuig, voorkeurstijd en eventueel inruil. Bedrijfsregels controleren daarna servicegebied, beschikbaarheid, rechten en uitzonderingen.", "Pas dan volgt een actie. Het resultaat wordt teruggeschreven naar CRM, agenda of ticketing. Bij onzekerheid, gevoelige onderwerpen of een mislukte koppeling wordt een medewerker ingeschakeld met gesprek, samenvatting, verzamelde gegevens en reden van overdracht."], bullets: ["Input en intentie", "Ontbrekende gegevens", "Goedgekeurde kennis en regels", "Gevalideerde systeemactie", "Bevestiging of menselijke overdracht"] },
      { id: "geschikte-taken", eyebrow: "Toepassing", title: "Begin met veelvoorkomend werk waarvan de uitkomst duidelijk is", paragraphs: ["Een goede eerste toepassing heeft herhaling, een herkenbare start en een controleerbare uitkomst. Denk aan afspraakvragen, statusvragen, gemiste oproepen, eerste leadkwalificatie of het voorbereiden van een serviceticket.", "Een slechte eerste toepassing bevat veel ongeschreven uitzonderingen, vereist professioneel oordeel of heeft grote gevolgen bij een fout. Medische beoordeling, juridische toezeggingen, complexe klachten en prijsafspraken zonder vast kader horen niet automatisch bij een eerste autonome route.", "Meet niet alleen hoeveel gesprekken zonder mens eindigen. Meet ook of de informatie compleet is, de juiste systeemactie is uitgevoerd, de klant niet hoeft te herhalen en overdrachten terecht en bruikbaar zijn."] },
      { id: "grenzen", eyebrow: "Grenzen", title: "AI blijft afhankelijk van data, integraties en menselijk eigenaarschap", paragraphs: ["Een AI-medewerker weet niet vanzelf hoe een bedrijf werkt. Verouderde documenten, tegenstrijdige agenda’s en onduidelijke eigenaarschap leiden ook met een goed model tot slechte uitkomsten.", "Daarom blijven procesontwerp, toegangsbeheer, privacy, monitoring en inhoudelijk eigenaarschap noodzakelijk. De AI kan werk overnemen, maar de organisatie blijft verantwoordelijk voor de klantreis en de gebruikte gegevens."] }
    ],
    examples: [{ title: "Scenario: autobedrijf", text: "Een platformlead vraagt buiten openingstijd naar een voorraadmodel. De AI controleert beschikbaarheid, verzamelt inruilgegevens, stelt een proefritmoment voor en zet de context bij de juiste verkoper." }, { title: "Scenario: installatiebedrijf", text: "Een storing komt telefonisch binnen. De AI vraagt foutcode, veiligheid, adres en contract uit en maakt afhankelijk van urgentie een werkbon of menselijke escalatie." }],
    faq: [{ question: "Is een AI-medewerker hetzelfde als ChatGPT?", answer: "Nee. Een taalmodel kan onderdeel zijn van de oplossing. De AI-medewerker bestaat daarnaast uit bedrijfskennis, regels, tools, rechten, logging, monitoring en menselijke fallback." }, { question: "Kan een AI-medewerker zelfstandig beslissen?", answer: "Alleen binnen de vooraf ontworpen rol. Harde regels en autorisatie horen buiten het taalmodel te worden afgedwongen. Impactvolle of onzekere situaties vragen bevestiging of overdracht." }, { question: "Waar begin je met een AI-medewerker?", answer: "Kies één terugkerende klantreis met duidelijke gegevens en uitkomst. Beschrijf uitzonderingen, eigenaar, systemen en kwaliteitscriteria voordat je techniek kiest." }],
    related: [{ label: "Product", title: "Bekijk de AI Inboxmedewerker.", href: "/producten/ai-inboxmedewerker/" }, { label: "Proces", title: "Bekijk hoe een AI-medewerker live gaat.", href: "/proces/" }, { label: "Branche", title: "Bekijk AI voor autobedrijven.", href: "/voor-wie/autobedrijven/" }],
    sources: [openAiAgents, openAiTools, openAiSafety, uwvKlantcontact]
  }),
  article({
    slug: "wat-is-een-ai-telefoniste",
    category: "AI-telefonie",
    contentCluster: "AI-medewerkers en klantcontact",
    readTime: "9 min",
    title: "Wat is een AI-telefoniste en hoe werkt automatische telefonie?",
    accent: "automatische telefonie?",
    cardTitle: "Wat is een AI-telefoniste?",
    excerpt: "Een AI-telefoniste voert een natuurlijk gesprek, verzamelt verplichte gegevens en zet het gesprek om in een afspraak, taak of complete overdracht.",
    description: "Lees hoe een AI-telefoniste gesprekken aanneemt, vragen uitvraagt, agenda en CRM gebruikt en veilig overdraagt aan medewerkers.",
    intent: "Uitleg en keuzehulp voor bedrijven die telefonische opvang met AI overwegen.",
    searchIntent: "informatief-commercieel",
    primaryKeyword: "wat is een AI-telefoniste",
    audience: "Bedrijven met veel inkomende oproepen, gemiste gesprekken, intake of planning.",
    promise: "Je weet wat automatische telefonie wel en niet kan en welke inrichting nodig is.",
    conversion: "Breng één veelvoorkomend telefoontype in kaart.",
    keywords: ["wat is een AI-telefoniste", "AI telefoniste", "automatische telefonie", "voice agent", "AI telefoon aannemen"],
    relatedArticles: ["wat-is-een-ai-medewerker", "chatbot-voicebot-ai-medewerker-verschil", "menselijke-overdracht-ai-klantcontact", "voice-ai-conversational-ai-ontwikkelingen-2026"],
    relatedProducts: ["ai-telefoniste"], relatedNiches: ["tandartsen", "installatietechniek", "autobedrijven"],
    summary: ["Een AI-telefoniste is een voice agent die spraak begrijpt, gericht doorvraagt en binnen vaste regels een vervolgactie uitvoert.", "De telefoniekoppeling, agenda, kennis, bevestiging van kritieke gegevens en fallback bepalen de kwaliteit meer dan alleen een natuurlijke stem.", "Start met een afgebakende route zoals afspraakintake, gemiste oproep of storingsclassificatie en behoud een bereikbare menselijke optie."],
    sections: [
      { id: "spraakroute", eyebrow: "Gespreksroute", title: "Luisteren en praten zijn slechts de buitenkant van de oplossing", paragraphs: ["Een voice agent ontvangt audio, zet die direct of tussentijds om naar betekenis en maakt een antwoord in spraak. Moderne realtime systemen kunnen onderbrekingen, stiltes en correcties beter verwerken dan klassieke spraakmenu’s.", "Voor zakelijk gebruik komt daar een proceslaag bij. De AI moet weten welk type afspraak past, welke velden verplicht zijn, wanneer een melding spoed is en welke informatie mag worden gedeeld. Zonder die laag klinkt het gesprek misschien goed, maar eindigt het zonder bruikbaar resultaat.", "Namen, adressen, kentekens, foutcodes en tijden verdienen extra bevestiging. Een kleine transcriptiefout kan anders een verkeerde afspraak of werkbon veroorzaken."] },
      { id: "acties", eyebrow: "Acties", title: "Een goed gesprek eindigt met bevestiging, registratie of overdracht", paragraphs: ["De AI kan beschikbaarheid lezen, een afspraak voorstellen en na bevestiging boeken. Ook kan hij een terugbeltaak, ticket of CRM-notitie maken. De toepassing moet technisch controleren of de actie echt is gelukt voordat de beller een toezegging hoort.", "Als agenda of CRM niet reageert, is improviseren verkeerd. De AI benoemt dat de afspraak nog niet bevestigd is, legt een terugbelverzoek vast en stuurt de context naar de juiste eigenaar."], bullets: ["Gesprekstype en klant herkennen", "Verplichte gegevens teruglezen", "Toolresultaat technisch valideren", "Bevestiging naar beller sturen", "Fallback bij onzekerheid of storing"] },
      { id: "wanneer-passend", eyebrow: "Selectie", title: "Voice AI past bij tijdkritische en gestructureerde telefoonroutes", paragraphs: ["Telefonie is nuttig wanneer klanten niet willen typen, snel duidelijkheid nodig hebben of buiten openingstijden bellen. Afspraken, statusvragen, eerste storingsintake en gemiste oproepen zijn vaak beter af te bakenen dan complexe advisering.", "Klachten, emotionele situaties, veiligheid en professioneel oordeel vragen een lage drempel naar een medewerker. Ook een klant die expliciet om een mens vraagt, hoort niet in een eindeloze lus terecht te komen."] }
    ],
    examples: [{ title: "Tandarts", text: "Een patiënt vraagt of er deze week een controleplek vrij is. De AI controleert het juiste afspraaktype, biedt twee momenten en bevestigt pas na keuze." }, { title: "Werkplaats", text: "Na een gemiste oproep vraagt de AI kenteken, klacht en rijdbaarheid uit en maakt een complete diagnosetaak." }],
    faq: [{ question: "Is een AI-telefoniste hetzelfde als een keuzemenu?", answer: "Nee. Een keuzemenu laat vaste opties kiezen. Een AI-telefoniste begrijpt vrije taal en kan doorvragen, maar hoort nog steeds binnen vaste bedrijfsregels te werken." }, { question: "Kan een beller worden doorverbonden?", answer: "Dat kan wanneer de telefonie-infrastructuur en routering dit ondersteunen. Leg vooraf teams, openingstijden, wachtrijen en fallback vast." }, { question: "Moet je vertellen dat de beller met AI praat?", answer: "Transparantie is een goed ontwerpuitgangspunt en wordt door Europese regels extra relevant. Meld het duidelijk in de opening en houd de juridische toepassing actueel." }],
    related: [{ label: "Product", title: "Bekijk de AI Telefoniste.", href: "/producten/ai-telefoniste/" }, { label: "Vergelijking", title: "Chatbot, voicebot of AI-medewerker?", href: "/kennisbank/chatbot-voicebot-ai-medewerker-verschil/" }, { label: "Branche", title: "Bekijk AI voor tandartsen.", href: "/voor-wie/tandartsen/" }],
    sources: [openAiRealtime, openAiTools, apAcmChatbots]
  }),
  article({
    slug: "chatbot-voicebot-ai-medewerker-verschil", category: "Keuzehulp", contentCluster: "AI-medewerkers en klantcontact", readTime: "8 min",
    title: "Chatbot, voicebot of AI-medewerker: wat is het verschil?", accent: "wat is het verschil?", cardTitle: "Chatbot, voicebot of AI-medewerker?",
    excerpt: "Het kanaal zegt niet hoeveel werk een systeem overneemt. Vergelijk op context, acties, rechten, overdracht en meetbare uitkomst.",
    description: "Vergelijk chatbot, voicebot en AI-medewerker op kanaal, mogelijkheden, systeemacties, risico’s en geschikte klantcontactprocessen.",
    intent: "Vergelijkende keuzehulp tussen chatbots, voicebots en AI-medewerkers.", searchIntent: "vergelijkend", primaryKeyword: "chatbot voicebot verschil", audience: "Teams die een kanaal of automatiseringsvorm kiezen.", promise: "Je kiest op proces en uitkomst in plaats van op een modieuze productnaam.", conversion: "Bepaal eerst input, gewenste actie en menselijke fallback.",
    keywords: ["chatbot voicebot verschil", "AI medewerker vs chatbot", "voicebot", "conversational AI kiezen", "AI klantcontact kanalen"], relatedArticles: ["wat-is-een-ai-medewerker", "wat-is-een-ai-telefoniste", "ai-email-whatsapp-websitechat"], relatedProducts: ["ai-inboxmedewerker", "ai-telefoniste"], relatedNiches: ["kapperszaken", "tandartsen", "vastgoedbeheerders"],
    summary: ["Een chatbot werkt via tekst; een voicebot via spraak. Een AI-medewerker beschrijft vooral de bredere rol, inclusief kennis, regels en systeemacties.", "Een tekstbot kan operationeler zijn dan een voicebot wanneer hij CRM en agenda mag gebruiken. Vergelijk daarom niet alleen op kanaal.", "Kies het kanaal waar de klantvraag ontstaat en automatiseer alleen de acties die betrouwbaar, toegestaan en controleerbaar zijn."],
    sections: [
      { id: "drie-begrippen", eyebrow: "Begrippen", title: "Kanaal, gesprekstechniek en bedrijfsrol zijn drie verschillende keuzes", paragraphs: ["Chatbot betekent meestal tekstinteractie op website of messaging. Voicebot betekent spraakinteractie via telefoon of app. Beide kunnen eenvoudig en regelgestuurd zijn of juist taalmodellen, kennis en tools gebruiken.", "AI-medewerker is een bredere term voor een afgebakende bedrijfsrol. Die rol kan over meerdere kanalen werken. Een inboxmedewerker kan e-mail, WhatsApp en chat verwerken; een telefoniste richt zich op voice; een leadopvolger bewaakt tijd en vervolgacties.", "Vraag daarom niet alleen welk type bot je nodig hebt. Vraag welk klantmoment, welke gegevens en welke systeemuitkomst je wilt verbeteren."] },
      { id: "vergelijking", eyebrow: "Vergelijking", title: "Vergelijk op vijf criteria die na de demo nog steeds tellen", paragraphs: ["Beoordeel bereik: op welk kanaal stelt de klant de vraag? Beoordeel context: kan het systeem klant- en procesgegevens gecontroleerd gebruiken? Beoordeel acties: mag het lezen, voorstellen of schrijven?", "Kijk vervolgens naar foutafhandeling en overdracht. Een systeem dat mooi praat maar geen toolfout herkent of geen mens kan inschakelen, is niet productiegeschikt."], bullets: ["Kanaal en bereikbaarheid", "Kennis en klantcontext", "Gevalideerde systeemacties", "Privacy en toegangsrechten", "Menselijke fallback en monitoring"] },
      { id: "keuze", eyebrow: "Beslisroute", title: "Kies tekst voor asynchrone context en voice voor directe, tijdkritische interactie", paragraphs: ["E-mail en WhatsApp zijn geschikt wanneer documenten, foto’s, langere antwoorden of een niet-direct gesprek belangrijk zijn. Telefonie past wanneer snelheid, toegankelijkheid of mondelinge toelichting centraal staat.", "Gebruik meerdere kanalen alleen wanneer zij dezelfde klantcontext delen. Anders moet de klant opnieuw beginnen en ontstaan tegenstrijdige statussen. Eén goed ontworpen route op het belangrijkste kanaal is vaak een betere start dan drie losse bots."] }
    ],
    examples: [{ title: "Vastgoedbeheer", text: "Chat of e-mail is handig voor foto’s en dossiergegevens; telefonie blijft beschikbaar voor urgente lekkage en bewoners die niet kunnen typen." }, { title: "Kapperszaak", text: "WhatsApp verwerkt afspraakwijzigingen asynchroon; voice vangt oproepen op terwijl medewerkers behandelen." }],
    faq: [{ question: "Is een AI-medewerker altijd slimmer dan een chatbot?", answer: "Niet automatisch. De term zegt niets over kwaliteit. Controleer kennis, rechten, acties, tests en fallback." }, { question: "Kunnen chat en voice dezelfde kennis gebruiken?", answer: "Ja, maar antwoorden en interactieregels moeten per kanaal worden ontworpen. Kritieke gegevens vragen in voice bijvoorbeeld vaker expliciete teruglezing." }, { question: "Moet je meteen omnichannel starten?", answer: "Nee. Start waar de grootste bottleneck zit en ontwerp een gedeeld datamodel voordat je extra kanalen toevoegt." }],
    related: [{ label: "Pillar", title: "Lees wat een AI-medewerker is.", href: "/kennisbank/wat-is-een-ai-medewerker/" }, { label: "Product", title: "Bekijk de AI Inboxmedewerker.", href: "/producten/ai-inboxmedewerker/" }, { label: "Product", title: "Bekijk de AI Telefoniste.", href: "/producten/ai-telefoniste/" }],
    sources: [openAiAgents, openAiRealtime, apAcmChatbots, uwvKlantcontact]
  })
];

const clusterB: KnowledgeArticle[] = [
  article({
    slug: "wat-is-ai-leadopvolging", category: "Leads en conversie", contentCluster: "Leads en conversie", pillar: true, readTime: "10 min",
    title: "Wat is AI-leadopvolging en hoe werkt het?", accent: "hoe werkt het?", cardTitle: "Wat is AI-leadopvolging?",
    excerpt: "AI-leadopvolging bewaakt de volgende stap na een aanvraag, stelt gerichte vragen en legt reactie, status en eigenaar vast in het CRM.",
    description: "Lees hoe AI-leadopvolging werkt, van eerste reactie en kwalificatie tot afspraak, CRM-update en menselijke salesoverdracht.",
    intent: "Neutrale uitleg over automatische leadopvolging met AI.", searchIntent: "informatief-commercieel", primaryKeyword: "AI leadopvolging", audience: "Sales- en marketingteams met inkomende leads, offertes of open aanvragen.", promise: "Je begrijpt de workflow, gegevens, grenzen en meetpunten.", conversion: "Teken de route van nieuwe lead naar concrete actie.",
    keywords: ["AI leadopvolging", "leads automatisch opvolgen", "AI sales opvolging", "leadkwalificatie AI", "CRM opvolging"], relatedArticles: ["hoe-snel-nieuwe-lead-opvolgen", "roi-automatische-leadopvolging-berekenen", "hoe-werken-ai-en-crm-samen"], relatedProducts: ["ai-leadopvolger", "autopilots-crm"], relatedNiches: ["autobedrijven", "makelaars", "zonnepanelen"],
    summary: ["AI-leadopvolging reageert niet alleen, maar bewaakt per lead welke vraag, herinnering of overdracht logisch is.", "De AI gebruikt bron, product, eerdere interacties, toestemming en CRM-status om een beperkte volgende stap voor te stellen of uit te voeren.", "De kwaliteit blijkt uit correcte reacties, complete context, geldige afspraken en bruikbare overdracht — niet uit het aantal verstuurde berichten."],
    sections: [
      { id: "workflow", eyebrow: "Workflow", title: "De opvolging begint bij één gebeurtenis en eindigt bij een duidelijke status", paragraphs: ["Een nieuwe formulierlead, platformaanvraag, gemiste oproep of open offerte activeert de route. De toepassing controleert of opvolging is toegestaan, welk kanaal past en of een medewerker al actief bezig is.", "Daarna komt een korte eerste reactie die aansluit op de aanvraag. De AI vraagt alleen wat nodig is voor de volgende stap, bijvoorbeeld voertuig, budgetrichting, locatie, planning of reden van twijfel.", "Elke reactie verandert de status. Geïnteresseerd, later, onbereikbaar, niet passend, afspraak voorgesteld of mens nodig zijn concreter dan één algemene kolom ‘open’. Daardoor kan sales gericht overnemen en stopt automatisering wanneer dat hoort."], bullets: ["Trigger en bron vastleggen", "Toestemming en kanaalregels controleren", "Contextuele vraag stellen", "Antwoord en status verwerken", "Afspraak, taak, pauze of overdracht"] },
      { id: "cadans", eyebrow: "Cadans", title: "Een goede reeks reageert op gedrag en stopt op duidelijke signalen", paragraphs: ["Een vaste reeks van identieke herinneringen voelt snel onpersoonlijk. AI kan inhoud en timing laten afhangen van de oorspronkelijke vraag, een reactie, een geopende offerte of een geplande afspraak.", "Dat betekent niet onbeperkt blijven sturen. Leg maximaal aantal pogingen, rustperiodes, kanaalvoorkeur, afmeldsignalen en uitsluitingen vast. Een expliciete afwijzing of menselijke overname stopt de route direct."] },
      { id: "crm", eyebrow: "CRM", title: "Zonder betrouwbaar CRM ontstaat dubbele of tegenstrijdige opvolging", paragraphs: ["De agent moet kunnen zien wie eigenaar is, welke boodschap al is verstuurd en wat de actuele fase is. Als verschillende systemen een andere status tonen, kan een klant tegelijk door AI en verkoper worden benaderd.", "Maak daarom één bron leidend voor status en eigenaarschap. Schrijf na iedere actie tijd, kanaal, samenvatting, uitkomst en volgende stap terug. Valideer de write voordat de route verdergaat." ] },
      { id: "meten", eyebrow: "Meten", title: "Meet klantuitkomst en proceskwaliteit naast conversie", paragraphs: ["Aantal reacties en afspraken zijn nuttig, maar zeggen niet of de afspraken geldig of passend zijn. Controleer ook compleetheid, no-show-signalen, verkeerde routing, afmeldingen en tijd tot menselijke overname.", "Vergelijk een afgebakende periode met dezelfde definities. Seizoen, campagnekwaliteit en aanbod beïnvloeden het resultaat. Presenteer een verandering daarom niet automatisch als effect van AI alleen."] }
    ],
    examples: [{ title: "Platformlead autobedrijf", text: "De AI reageert op het specifieke voorraadmodel, vraagt naar proefrit en inruil en zet een complete afspraak bij de verantwoordelijke verkoper." }, { title: "Open offerte", text: "De AI vraagt of prijs, planning of scope nog onduidelijk is en draagt bij een inhoudelijk bezwaar over aan de offerte-eigenaar." }],
    faq: [{ question: "Is AI-leadopvolging hetzelfde als e-mailautomation?", answer: "Niet per se. Klassieke automation volgt vaste triggers en teksten. AI kan vrije antwoorden begrijpen en contextueel doorvragen, maar hoort nog steeds binnen vaste toestemming, cadans en bedrijfsregels te werken." }, { question: "Kan AI iedere lead automatisch kwalificeren?", answer: "Alleen met duidelijke criteria en beschikbare gegevens. Strategische, gevoelige of onzekere beoordeling blijft bij een medewerker." }, { question: "Wanneer stopt automatische opvolging?", answer: "Bij afmelding, afwijzing, ongeldige contactgrond, menselijke overname, bereikte poginglimiet, geplande afspraak of een andere vooraf bepaalde eindstatus." }],
    related: [{ label: "Product", title: "Bekijk de AI Leadopvolger.", href: "/producten/ai-leadopvolger/" }, { label: "Rekenmodel", title: "Bereken de ROI van leadopvolging.", href: "/kennisbank/roi-automatische-leadopvolging-berekenen/" }, { label: "Branche", title: "Bekijk de leadroute voor autobedrijven.", href: "/voor-wie/autobedrijven/" }],
    sources: [openAiAgents, openAiTools, openAiSafety]
  }),
  article({
    slug: "hoe-snel-nieuwe-lead-opvolgen", category: "Leads en conversie", contentCluster: "Leads en conversie", readTime: "8 min",
    title: "Hoe snel moet je een nieuwe lead opvolgen?", accent: "een nieuwe lead opvolgen?", cardTitle: "Hoe snel moet je een lead opvolgen?",
    excerpt: "De juiste responstijd hangt af van intentie, kanaal en urgentie. Belangrijker dan één universeel getal is een directe, relevante en uitvoerbare eerste stap.",
    description: "Hoe snel moet je leads opvolgen? Gebruik een praktisch prioriteitsmodel voor kanaal, intentie, openingstijden, automatisering en menselijke overdracht.",
    intent: "Probleemgerichte uitleg over responstijd bij nieuwe leads zonder onbewezen universele benchmarks.", searchIntent: "probleemgericht", primaryKeyword: "hoe snel lead opvolgen", audience: "Sales- en serviceteams die nieuwe aanvragen prioriteren.", promise: "Je maakt een responstijdbeleid dat past bij de klantvraag.", conversion: "Verdeel leads op urgentie, koopintentie en benodigde actie.",
    keywords: ["hoe snel lead opvolgen", "responstijd leads", "nieuwe lead bellen", "lead buiten openingstijd", "snelle leadopvolging"], relatedArticles: ["wat-is-ai-leadopvolging", "roi-automatische-leadopvolging-berekenen", "wat-is-een-ai-telefoniste"], relatedProducts: ["ai-leadopvolger", "ai-telefoniste"], relatedNiches: ["autobedrijven", "makelaars", "zonnepanelen"],
    summary: ["Een live chat, gemiste oproep en vrijblijvende download hebben niet dezelfde gewenste responstijd.", "Reageer snel genoeg om context en verwachting vast te houden, maar stuur geen leeg ontvangstbericht wanneer een gerichte vraag of actie mogelijk is.", "Ontwerp servicelevels per intentie en kanaal, plus een fallback wanneer agenda, CRM of verantwoordelijke medewerker niet beschikbaar is."],
    sections: [
      { id: "geen-universeel-getal", eyebrow: "Nuance", title: "Er bestaat geen geloofwaardig universeel aantal minuten voor iedere lead", paragraphs: ["Online artikelen noemen vaak één ideaal getal. Zonder context over branche, kanaal, campagne, product en onderzoeksopzet zegt zo’n benchmark weinig. Een spoedaanvraag is iets anders dan iemand die een gids downloadt.", "Bepaal responstijd vanuit de klantverwachting. Wie in een live kanaal een concrete voorraad- of afspraakvraag stelt, verwacht sneller antwoord dan iemand die expliciet informatie voor later aanvraagt.", "Snelheid zonder relevantie kan juist frictie veroorzaken. Een generiek bericht dat opnieuw vraagt wat al in het formulier staat, is technisch snel maar inhoudelijk traag."] },
      { id: "prioriteitsmodel", eyebrow: "Prioriteit", title: "Gebruik intentie, tijdgevoeligheid en actie als prioriteitsmodel", paragraphs: ["Geef hoge prioriteit aan vragen waarbij beschikbaarheid verandert, de klant nu wil handelen of veiligheid speelt. Plan informatievragen en lange oriëntatie anders in.", "Leg per klasse vast wie eigenaar is, wat de eerste reactie moet bereiken en wanneer de route escaleert."], bullets: ["Nu: live gesprek, gemiste oproep, afspraak of schaarse beschikbaarheid", "Vandaag: concrete offerte-, voorraad- of servicevraag", "Gepland: oriëntatie, nurture of een toekomstige hercontactdatum", "Mens direct: klacht, emotie, veiligheid of inhoudelijk oordeel"] },
      { id: "buiten-openingstijd", eyebrow: "Buiten openingstijd", title: "Automatisering kan de wachttijd benutten zonder te doen alsof alles direct kan", paragraphs: ["Buiten openingstijd kan AI de vraag erkennen, relevante gegevens verzamelen en beschikbare momenten aanbieden. Als een medewerker of systeem nodig is, vermeldt de route eerlijk wanneer bevestiging volgt.", "Zo begint de volgende werkdag met complete context in plaats van een naam en telefoonnummer. De klant krijgt ondertussen duidelijkheid over de volgende stap."] }
    ],
    examples: [{ title: "Voorraadlead", text: "De AI controleert het voertuig, vraagt naar proefrit en inruil en geeft een concreet vervolg. Niet alleen: ‘we nemen contact op’." }, { title: "Offerteoriëntatie", text: "De lead ontvangt relevante uitleg en kiest zelf een terugbelmoment, zonder ’s avonds onverwacht gebeld te worden." }],
    faq: [{ question: "Moet je iedere lead direct bellen?", answer: "Nee. Kanaalvoorkeur, toestemming, intentie en tijdstip bepalen wat passend is. Soms is een inhoudelijke chat- of e-mailreactie beter." }, { question: "Is een automatisch ontvangstbericht genoeg?", answer: "Het bevestigt ontvangst, maar lost de informatiebehoefte niet op. Verzamel waar mogelijk direct de context voor een bruikbare volgende stap." }, { question: "Hoe stel je een servicelevel vast?", answer: "Analyseer leadtypen, klantverwachting, beschikbaarheid en huidige uitval. Definieer per klasse een eigenaar, eerste actie en escalatiemoment en test dit in de praktijk." }],
    related: [{ label: "Pillar", title: "Lees hoe AI-leadopvolging werkt.", href: "/kennisbank/wat-is-ai-leadopvolging/" }, { label: "Product", title: "Bekijk de AI Leadopvolger.", href: "/producten/ai-leadopvolger/" }, { label: "Branche", title: "Bekijk AI voor makelaars.", href: "/voor-wie/makelaars/" }],
    sources: [uwvKlantcontact, openAiAgents, apAcmChatbots]
  }),
  article({
    slug: "roi-automatische-leadopvolging-berekenen", category: "Leads en conversie", contentCluster: "Leads en conversie", readTime: "9 min",
    title: "Hoe bereken je de ROI van automatische leadopvolging?", accent: "automatische leadopvolging?", cardTitle: "ROI van automatische leadopvolging berekenen",
    excerpt: "Een bruikbare businesscase begint met gemiste opvolging, extra concrete acties, klantwaarde en alle kosten — niet met een beloofd conversiepercentage.",
    description: "Bereken transparant de ROI van automatische leadopvolging met volume, gemiste opvolging, afspraken, klantwaarde, abonnement, usage en implementatie.",
    intent: "Praktisch rekenmodel voor de businesscase van automatische leadopvolging.", searchIntent: "beslis- en rekenintentie", primaryKeyword: "ROI leadopvolging berekenen", audience: "Ondernemers en salesverantwoordelijken die een investering in opvolging beoordelen.", promise: "Je kunt aannames, opbrengsten, kosten en onzekerheid zichtbaar doorrekenen.", conversion: "Vul een voorzichtige basis-, lage en hoge variant in.",
    keywords: ["ROI leadopvolging berekenen", "businesscase lead automation", "kosten AI leadopvolging", "gemiste leads berekenen", "opvolging rendement"], relatedArticles: ["wat-is-ai-leadopvolging", "hoe-snel-nieuwe-lead-opvolgen", "hoe-werken-ai-en-crm-samen"], relatedProducts: ["ai-leadopvolger", "autopilots-crm"], relatedNiches: ["autobedrijven", "makelaars", "zonnepanelen"],
    summary: ["Bereken eerst hoeveel relevante aanvragen nu niet tijdig of volledig worden opgevolgd.", "Schat daarna voorzichtig hoeveel extra concrete acties en klanten kunnen ontstaan; gebruik eigen data en toon een bandbreedte.", "Trek abonnement, gebruikskosten, implementatie, beheer en menselijke opvolgtijd af. Een indicatieve waarde is geen omzetgarantie."],
    sections: [
      { id: "rekenmodel", eyebrow: "Rekenmodel", title: "Bouw de berekening van processtappen op, niet van één groot percentage", paragraphs: ["Start met het maandelijkse aantal relevante leads. Vermenigvuldig dit met het aandeel dat nu te laat, onvolledig of niet wordt opgevolgd. Dat is het maximaal beïnvloedbare volume, niet automatisch het aantal extra klanten.", "Bereken vervolgens hoeveel van dat volume door de nieuwe route daadwerkelijk op tijd wordt verwerkt, welk aandeel tot een concrete afspraak of actie leidt en welk aandeel uiteindelijk klant wordt.", "Vermenigvuldig extra klanten met de waarde die voor jouw besluit relevant is: marge of dekkingsbijdrage is vaak bruikbaarder dan bruto omzet. Gebruik dezelfde definitie in alle scenario’s."], bullets: ["Beïnvloedbaar volume = leads × huidige opvolguitval", "Extra acties = extra verwerkte leads × actiepercentage", "Extra klanten = extra acties × realisatiepercentage", "Indicatieve waarde = extra klanten × waarde per resultaat", "Netto indicatie = waarde minus alle relevante kosten"] },
      { id: "kosten", eyebrow: "Kosten", title: "Neem ook implementatie, usage, beheer en menselijk werk mee", paragraphs: ["Een abonnement is zelden de enige kostenpost. Telefonie, berichten, modelgebruik, integraties en inrichting kunnen variabel of eenmalig zijn. Daarnaast blijft tijd nodig voor kennisbeheer, monitoring en uitzonderingen.", "Verdeel eenmalige implementatiekosten over een realistische beoordelingsperiode, maar houd ze zichtbaar. Verberg geen kosten om de terugverdientijd aantrekkelijker te maken."] },
      { id: "scenarios", eyebrow: "Bandbreedte", title: "Reken minimaal een lage, basis- en hoge variant", paragraphs: ["Gebruik de lage variant voor lagere bereikbaarheid of conversie en hogere kosten. De hoge variant mag alleen aannames bevatten die operationeel haalbaar en onderbouwd zijn.", "Vergelijk na livegang voorspelling met werkelijke data: bereikte leads, complete acties, geldige afspraken, klanten, afmeldingen en kosten. Pas het model aan; gebruik het niet als statische verkoopbelofte."] }
    ],
    examples: [{ title: "Voorbeeld zonder verzonnen benchmark", text: "Een autobedrijf vult eigen maandvolume, huidige opvolguitval, proefritpercentage, klantpercentage en gemiddelde marge in. Het model toont de uitkomst als bandbreedte." }, { title: "Niet-financiële waarde", text: "Leg daarnaast kortere wachttijd, completere CRM-data en minder handmatig herinneringswerk vast, zonder deze dubbel als omzet te tellen." }],
    faq: [{ question: "Welke klantwaarde gebruik je?", answer: "Gebruik de waarde die bij je beslissing past en consistent beschikbaar is, bij voorkeur marge of dekkingsbijdrage. Documenteer de definitie." }, { question: "Mag je tijdwinst als omzet tellen?", answer: "Niet automatisch. Tijdwinst wordt pas financiële waarde wanneer capaciteit werkelijk anders wordt ingezet of kosten aantoonbaar veranderen." }, { question: "Wanneer is de ROI betrouwbaar?", answer: "Pas wanneer definities stabiel zijn en voldoende eigen procesdata beschikbaar is. Vooraf blijft het een scenarioanalyse, geen garantie." }],
    related: [{ label: "Calculator", title: "Bekijk de interactieve berekening bij AI Leadopvolger.", href: "/producten/ai-leadopvolger/" }, { label: "CRM", title: "Lees hoe AI en CRM samenwerken.", href: "/kennisbank/hoe-werken-ai-en-crm-samen/" }, { label: "Branche", title: "Bekijk de klantreis voor autobedrijven.", href: "/voor-wie/autobedrijven/" }],
    sources: [openAiAgents, openAiTools]
  })
];

const clusterC: KnowledgeArticle[] = [
  article({
    slug: "ai-email-whatsapp-websitechat", category: "Inbox en kanalen", contentCluster: "Inbox, CRM en automatisering", pillar: true, readTime: "10 min",
    title: "Hoe kan AI e-mail, WhatsApp en websitechat centraal afhandelen?", accent: "centraal afhandelen?", cardTitle: "AI voor e-mail, WhatsApp en websitechat",
    excerpt: "Een centrale AI-inbox herkent de klant en intentie over kanalen heen, maar gebruikt per kanaal passende regels, toestemming en antwoordvorm.",
    description: "Lees hoe AI e-mail, WhatsApp en websitechat centraal verwerkt met klantcontext, kanaalregels, CRM-acties en menselijke overdracht.",
    intent: "Pillar over omnichannel AI-inboxbeheer voor klantcontact.", searchIntent: "informatief-commercieel", primaryKeyword: "AI voor e-mail en WhatsApp", audience: "Teams met klantvragen verspreid over inbox, messaging en chat.", promise: "Je begrijpt hoe kanalen één context delen zonder één generieke bot te worden.", conversion: "Breng kanalen, identiteit en leidende klantstatus in kaart.",
    keywords: ["AI voor e-mail en WhatsApp", "AI inbox", "websitechat automatiseren", "omnichannel AI", "klantcontact centraal"], relatedArticles: ["hoe-werken-ai-en-crm-samen", "klantcontactprocessen-veilig-automatiseren", "ai-avg-geautomatiseerd-klantcontact"], relatedProducts: ["ai-inboxmedewerker", "autopilots-crm"], relatedNiches: ["vastgoedbeheerders", "woningcorporaties", "kapperszaken"],
    summary: ["Centraliseren betekent dat ieder kanaal dezelfde klantstatus, kennis en eigenaarschap gebruikt; niet dat ieder bericht exact hetzelfde antwoord krijgt.", "De AI herkent intentie, haalt minimale context op en zet een e-mail, WhatsApp-bericht of chat om in antwoord, afspraak, ticket, taak of overdracht.", "Identiteit, toestemming, bijlagen, bewaartermijnen en verwachtingen verschillen per kanaal en moeten apart worden ontworpen."],
    sections: [
      { id: "gedeelde-context", eyebrow: "Context", title: "Eén klantcontext voorkomt herhaling en tegenstrijdige opvolging", paragraphs: ["Klanten wisselen gemakkelijk van kanaal. Een huurder mailt een foto, belt later over urgentie en vraagt via chat naar status. Zonder gedeelde context behandelt ieder kanaal dit als een nieuw gesprek.", "Een centrale inbox koppelt berichten waar dat betrouwbaar kan aan klant, dossier, object of lead. De toepassing ziet eerdere acties en de actuele eigenaar. Dat voorkomt dat WhatsApp een afspraak aanbiedt die per e-mail al is gewijzigd.", "Identiteitskoppeling moet voorzichtig gebeuren. Een telefoonnummer, e-mailadres of ordernummer kan helpen, maar gevoelige dossierinformatie vraagt passende verificatie voordat die wordt getoond of gewijzigd."] },
      { id: "kanaalregels", eyebrow: "Kanaalregels", title: "Gebruik dezelfde kennis, maar ontwerp per kanaal een andere interactie", paragraphs: ["E-mail bevat langere context en bijlagen en hoeft niet altijd direct beantwoord te worden. WhatsApp is korter en vraagt aandacht voor toestemming en afmelden. Websitechat is live en anoniemer totdat de bezoeker zich identificeert.", "Maak per kanaal duidelijk welke gegevens worden gevraagd, wat als bevestiging geldt en wanneer een gesprek naar een ander kanaal gaat. Een foto kan nuttig zijn voor een servicemelding; een wachtwoord of volledig medisch dossier hoort niet in gewone chat."], bullets: ["E-mail: lange context, documenten en asynchrone beoordeling", "WhatsApp: snelle dialoog, kanaaltoestemming en duidelijke stoproute", "Websitechat: eerste oriëntatie, beperkte identiteit en live verwachting", "CRM: gedeelde status, eigenaar, samenvatting en volgende actie"] },
      { id: "systeemactie", eyebrow: "Afhandeling", title: "Het resultaat is een afgehandelde route, niet een extra gegenereerde tekst", paragraphs: ["De AI bepaalt welke verplichte informatie ontbreekt, gebruikt goedgekeurde kennis en stelt een actie voor. Harde checks voor contract, servicegebied, agenda en status vinden buiten het model plaats.", "Pas na succesvolle verwerking bevestigt het systeem een afspraak, ticket of wijziging. Bij een mislukte write krijgt de klant een eerlijke tussenstatus en een medewerker een complete taak."] },
      { id: "meten", eyebrow: "Kwaliteit", title: "Meet herhaling, complete intake en correcte eigenaar", paragraphs: ["Een kortere eerste reactietijd is nuttig, maar een centrale inbox moet vooral herhaling en zoekwerk verminderen. Meet hoeveel gesprekken correct aan bestaande context zijn gekoppeld, welke verplichte velden ontbreken en of overdrachten bij het juiste team landen.", "Controleer regelmatig verkeerde samenvoegingen en kanalen waarop klanten afhaken. Meer centralisatie is alleen beter wanneer toegang en context correct blijven."] }
    ],
    examples: [{ title: "Vastgoedbeheer", text: "Een huurdersmail met foto wordt aan pand en dossier gekoppeld. De AI vraagt actieve lekkage en veiligheid uit en maakt daarna een ticket met juiste urgentie." }, { title: "Salon", text: "Een klant vraagt via Instagram of WhatsApp om een wijziging. De AI controleert behandeling en duur en past de agenda pas na bevestiging aan." }],
    faq: [{ question: "Kan AI één gesprek over meerdere kanalen volgen?", answer: "Ja, wanneer identiteit en toestemming betrouwbaar worden gekoppeld en één systeem de actuele status beheert. Zonder die voorwaarden kan samenvoegen juist risico geven." }, { question: "Moet ieder bericht automatisch worden beantwoord?", answer: "Nee. Sommige berichten vragen menselijke beoordeling, verificatie of alleen interne registratie. Classificatie en routing kunnen dan wel helpen." }, { question: "Kan AI bijlagen lezen?", answer: "Technisch vaak wel, maar toegestane bestandstypen, malwarecontrole, privacy, nauwkeurigheid en menselijke beoordeling moeten vooraf worden ingericht." }],
    related: [{ label: "Product", title: "Bekijk de AI Inboxmedewerker.", href: "/producten/ai-inboxmedewerker/" }, { label: "CRM", title: "Lees hoe AI en CRM samenwerken.", href: "/kennisbank/hoe-werken-ai-en-crm-samen/" }, { label: "Branche", title: "Bekijk AI voor vastgoedbeheerders.", href: "/voor-wie/vastgoedbeheerders/" }],
    sources: [uwvKlantcontact, openAiAgents, openAiTools, openAiSafety]
  }),
  article({
    slug: "hoe-werken-ai-en-crm-samen", category: "CRM en automatisering", contentCluster: "Inbox, CRM en automatisering", readTime: "9 min",
    title: "Hoe werken AI en CRM samen in klantcontact?", accent: "samen in klantcontact?", cardTitle: "Hoe werken AI en CRM samen?",
    excerpt: "AI begrijpt het gesprek; CRM bewaart klant, status, eigenaar en historie. De koppeling vertaalt taal naar gevalideerde velden en toegestane acties.",
    description: "Lees hoe AI en CRM samenwerken voor intake, samenvatting, leadstatus, taken, afspraken en veilige toegangs- en foutafhandeling.",
    intent: "Leveranciersonafhankelijke uitleg over AI-CRM-integratie.", searchIntent: "informatief", primaryKeyword: "AI en CRM", audience: "Sales-, service- en operationele teams met een CRM.", promise: "Je begrijpt datamodel, rechten, writes, validatie en monitoring.", conversion: "Kies één leesactie en één omkeerbare schrijfactie voor een pilot.",
    keywords: ["AI en CRM", "AI CRM koppeling", "gesprek naar CRM", "AI pipeline", "CRM automatiseren"], relatedArticles: ["ai-email-whatsapp-websitechat", "wat-is-ai-leadopvolging", "klantcontactprocessen-veilig-automatiseren"], relatedProducts: ["autopilots-crm", "ai-leadopvolger"], relatedNiches: ["autobedrijven", "makelaars", "vastgoedbeheerders"],
    summary: ["AI zet vrije taal om in een voorstel voor gestructureerde CRM-data; applicatielogica valideert en autoriseert de uiteindelijke actie.", "Lezen, voorstellen en schrijven hebben verschillende risico’s en horen verschillende rechten en bevestiging te krijgen.", "Bij iedere write moeten resultaat, bron, tijd, eigenaar en foutstatus controleerbaar zijn. Een mooie samenvatting is geen bewijs dat CRM correct is bijgewerkt."],
    sections: [
      { id: "rollen", eyebrow: "Rolverdeling", title: "AI begrijpt betekenis; CRM blijft de operationele bron", paragraphs: ["Een gesprek bevat vrije taal, correcties en impliciete informatie. AI kan daar intentie, samenvatting en voorgestelde velden uit halen. Het CRM bewaart de formele klantstatus, activiteiten, afspraken en eigenaarschap.", "Laat de AI niet zelf bepalen welke willekeurige CRM-velden bestaan. Bied afgebakende tools aan, zoals klant zoeken, notitie voorstellen, taak aanmaken of beschikbaarheid lezen. De tool controleert schema, autorisatie en bedrijfsregels.", "Maak één systeem leidend voor iedere status. Wanneer marketing, agenda en CRM allemaal een andere waarheid hebben, kan ook een goede agent geen betrouwbare vervolgstap kiezen."] },
      { id: "rechten", eyebrow: "Rechten", title: "Splits lezen, voorstellen en uitvoeren", paragraphs: ["Een agent die klantnaam en laatste activiteit leest, heeft minder impact dan een agent die een deal sluit of afspraak verwijdert. Geef per tool minimale rechten en laat impactvolle acties bevestigen.", "Schrijfacties moeten idempotent zijn waar herhaling mogelijk is. Een netwerkfout of dubbele toolcall mag niet twee afspraken of drie opvolgtaken maken."], bullets: ["Lezen: alleen noodzakelijke records en velden", "Voorstellen: conceptstatus, samenvatting of afspraak", "Uitvoeren: validatie, autorisatie en waar nodig bevestiging", "Loggen: resultaat en fout zonder geheimen of onnodige persoonsgegevens"] },
      { id: "velden", eyebrow: "Datamodel", title: "Leg vooraf vast welke velden feit zijn en welke interpretatie", paragraphs: ["E-mailadres, gekozen tijd en kenteken zijn concrete invoer. Koopintentie of sentiment zijn interpretaties en kunnen onzeker zijn. Bewaar dit onderscheid en presenteer een AI-inschatting niet als vaststaand klantfeit.", "Gebruik gecontroleerde keuzelijsten voor status, reden, urgentie en eigenaar. Vrije samenvattingen helpen mensen, maar horen vaste velden niet stil te vervangen."] },
      { id: "fouten", eyebrow: "Foutafhandeling", title: "Een mislukte CRM-write verandert de klantbelofte", paragraphs: ["De toepassing controleert de response van het CRM. Alleen daarna mag de AI zeggen dat een afspraak of wijziging is vastgelegd.", "Bij time-out of fout kan de AI een terugbeltaak via een alternatieve route maken of overdragen. De klant krijgt geen verzonnen bevestiging en het team ziet welke actie nog openstaat."] }
    ],
    examples: [{ title: "Lead", text: "De AI vult bron, behoefte en voorkeursmoment voor; een gevalideerde tool maakt de taak en koppelt de juiste verkoopeigenaar." }, { title: "Service", text: "De AI schrijft melding en urgentiesignalen naar een ticket, maar technisch of veiligheidsbesluit blijft bij de bevoegde medewerker." }],
    faq: [{ question: "Heeft een AI-agent automatisch toegang tot het hele CRM?", answer: "Nee. De applicatie bepaalt welke tools en rechten bestaan. Geef alleen toegang tot noodzakelijke objecten en acties." }, { question: "Kan AI CRM-data automatisch opschonen?", answer: "AI kan mogelijke duplicaten of ontbrekende velden signaleren. Samenvoegen en verwijderen vraagt sterke regels, audit en vaak menselijke controle." }, { question: "Wat als het CRM tijdelijk niet bereikbaar is?", answer: "Bevestig geen niet-uitgevoerde actie. Gebruik een gecontroleerde wachtrij of menselijke fallback en verwerk pas verder na een aantoonbaar succesvolle write." }],
    related: [{ label: "Product", title: "Bekijk Autopilots CRM.", href: "/producten/autopilots-crm/" }, { label: "Pillar", title: "Lees over AI voor inboxkanalen.", href: "/kennisbank/ai-email-whatsapp-websitechat/" }, { label: "Proces", title: "Bekijk koppelingen in het implementatieproces.", href: "/proces/" }],
    sources: [openAiTools, openAiAgents, openAiSafety]
  }),
  article({
    slug: "klantcontactprocessen-veilig-automatiseren", category: "Procesautomatisering", contentCluster: "Inbox, CRM en automatisering", readTime: "9 min",
    title: "Welke klantcontactprocessen kun je veilig automatiseren met AI?", accent: "veilig automatiseren met AI?", cardTitle: "Welke klantcontactprocessen kun je automatiseren?",
    excerpt: "Automatiseer eerst processen met duidelijke input, vaste regels en een controleerbare uitkomst. Houd oordeel, emotie en grote impact dichtbij een mens.",
    description: "Kies veilig te automatiseren klantcontactprocessen met een beslismodel voor herhaling, data, regels, acties, impact en menselijke fallback.",
    intent: "Praktische selectiehulp voor veilige AI-automatisering in klantcontact.", searchIntent: "praktisch", primaryKeyword: "klantcontact automatiseren met AI", audience: "Organisaties die use cases voor AI willen prioriteren.", promise: "Je beoordeelt processen op waarde én risico voordat je bouwt.", conversion: "Score drie klantreizen op herhaling, duidelijkheid en impact.",
    keywords: ["klantcontact automatiseren met AI", "processen automatiseren", "AI workflow klantcontact", "veilige AI automatisering", "AI use case kiezen"], relatedArticles: ["wat-is-een-ai-medewerker", "hoe-werken-ai-en-crm-samen", "ai-medewerker-implementeren", "menselijke-overdracht-ai-klantcontact"], relatedProducts: ["ai-inboxmedewerker", "ai-leadopvolger", "ai-telefoniste", "autopilots-crm"], relatedNiches: ["installatietechniek", "dakdekkers", "vastgoedbeheerders"],
    summary: ["Een geschikte eerste use case is herhaalbaar, heeft toegankelijke data, vaste regels en een uitkomst die technisch kan worden gecontroleerd.", "Splits een proces in lezen, begrijpen, voorstellen, uitvoeren en overdragen. Niet iedere stap hoeft dezelfde autonomie te krijgen.", "Automatiseer geen professioneel oordeel of onomkeerbare actie alleen omdat de taal eromheen voorspelbaar klinkt."],
    sections: [
      { id: "selectiemodel", eyebrow: "Selectie", title: "Beoordeel waarde, voorspelbaarheid en impact afzonderlijk", paragraphs: ["Veel volume maakt een proces interessant, maar niet automatisch veilig. Een zeldzame fout met grote gevolgen kan zwaarder wegen dan veel bespaarde minuten.", "Maak per route zichtbaar welke input nodig is, welke bronnen betrouwbaar zijn, welke uitzonderingen bestaan en welke uitkomst telt. Scoor daarna de impact van een verkeerde classificatie of actie.", "Start waar hoge herhaling samengaat met lage of omkeerbare impact. Statusvragen, afspraakvoorstellen, eerste intake en interne routering zijn vaak beter te begrenzen dan financieel, juridisch of technisch oordeel."] },
      { id: "autonomieniveaus", eyebrow: "Autonomie", title: "Geef iedere processtap het passende autonomieniveau", paragraphs: ["AI kan een bericht classificeren zonder direct iets naar de klant te sturen. Het kan een antwoord of CRM-update voorstellen die een medewerker bevestigt. Of het mag een laag-risicoactie zelfstandig uitvoeren.", "Door niveaus te combineren hoeft de keuze niet ‘alles handmatig’ of ‘volledig autonoom’ te zijn."], bullets: ["Assisteren: zoeken, samenvatten en concept maken", "Voorstellen: velden of actie klaarzetten voor bevestiging", "Uitvoeren: beperkte, gevalideerde en omkeerbare actie", "Overdragen: risico, onzekerheid, verzoek om mens of technische fout"] },
      { id: "rode-vlaggen", eyebrow: "Rode vlaggen", title: "Stop of beperk wanneer regels ongeschreven, data zwak of gevolgen groot zijn", paragraphs: ["Als medewerkers dezelfde vraag allemaal anders behandelen, ontbreekt waarschijnlijk een werkbaar proceskader. Als data verouderd of verspreid is, automatiseer je inconsistentie.", "Zorg bij klachten, veiligheid, gezondheid, juridische positie, kwetsbare personen en grote financiële impact voor expliciete menselijke verantwoordelijkheid. AI kan context verzamelen, maar niet vanzelf het bevoegde oordeel dragen."] },
      { id: "pilot", eyebrow: "Pilot", title: "Test de hele route inclusief storingen en overdracht", paragraphs: ["Gebruik echte maar zorgvuldig behandelde variatie: onvolledige vragen, typos, accent, tegenstrijdige informatie, ontbrekende records en uitgevallen tools.", "Definieer vooraf acceptatiecriteria voor juist antwoord, verplichte gegevens, actie, privacy en overdracht. Een pilot is pas geslaagd wanneer het team de uitkomst kan gebruiken."] }
    ],
    examples: [{ title: "Veilige start", text: "Een AI leest een afspraakverzoek, controleert beschikbare blokken en stelt twee opties voor. Boeken gebeurt na bevestiging." }, { title: "Beperkte autonomie", text: "Bij een veiligheidsmelding verzamelt de AI locatie en signalen, geeft alleen goedgekeurde noodinstructie en schakelt direct een medewerker in." }],
    faq: [{ question: "Welke processen automatiseer je meestal eerst?", answer: "Terugkerende intake, statusvragen, afspraakvoorstellen, eenvoudige kwalificatie en interne routering zijn vaak goed af te bakenen. Beoordeel altijd de eigen context." }, { question: "Is meer autonomie altijd efficiënter?", answer: "Nee. Fouten, herstelwerk en klantfrictie kunnen toenemen. De juiste autonomie levert een betrouwbare uitkomst met passende controle." }, { question: "Kun je een slecht proces met AI verbeteren?", answer: "AI kan knelpunten zichtbaar maken, maar een onduidelijk proces wordt niet vanzelf betrouwbaar. Leg eerst eigenaarschap, regels en data vast." }],
    related: [{ label: "Proces", title: "Bekijk de implementatieroute.", href: "/proces/" }, { label: "Pillar", title: "Lees wat een AI-medewerker is.", href: "/kennisbank/wat-is-een-ai-medewerker/" }, { label: "Branche", title: "Bekijk AI voor installatiebedrijven.", href: "/voor-wie/installatietechniek/" }],
    sources: [openAiAgents, openAiTools, openAiSafety, apAcmChatbots]
  })
];

const clusterD: KnowledgeArticle[] = [
  article({
    slug: "ai-medewerker-implementeren", category: "Implementatie", contentCluster: "Implementatie en betrouwbaarheid", pillar: true, readTime: "12 min",
    title: "Hoe implementeer je een AI-medewerker binnen je bedrijf?", accent: "binnen je bedrijf?", cardTitle: "Een AI-medewerker implementeren",
    excerpt: "Een productieklare AI-medewerker begint bij proces en eigenaarschap en gaat via data, regels, koppelingen, tests en gecontroleerde livegang.",
    description: "Stappenplan om een AI-medewerker te implementeren: use case, klantreis, data, AI-brein, koppelingen, evals, privacy, livegang en monitoring.",
    intent: "Praktische implementatiegids voor een AI-medewerker in klantcontact.", searchIntent: "praktisch-beslissend", primaryKeyword: "AI medewerker implementeren", audience: "Ondernemers, operations en projectverantwoordelijken die van pilot naar productie willen.", promise: "Je krijgt een controleerbare route van proceskeuze tot monitoring.", conversion: "Benoem eigenaar, scope en acceptatiecriteria vóór techniek.",
    keywords: ["AI medewerker implementeren", "AI implementatie stappenplan", "AI agent livegang", "AI klantcontact implementatie", "AI project bedrijf"], relatedArticles: ["klantcontactprocessen-veilig-automatiseren", "verkeerde-ai-antwoorden-hallucinaties-voorkomen", "menselijke-overdracht-ai-klantcontact", "ai-avg-geautomatiseerd-klantcontact"], relatedProducts: ["ai-inboxmedewerker", "ai-leadopvolger", "ai-telefoniste", "autopilots-crm"], relatedNiches: ["autobedrijven", "installatietechniek", "vastgoedbeheerders"],
    summary: ["Kies één klantreis en leg doel, eigenaar, grenzen, gegevens en uitkomst vast voordat je modellen of leveranciers selecteert.", "Bouw kennis, gesprekslogica en tools apart en test de complete keten met normale, afwijkende en mislukte scenario’s.", "Ga gecontroleerd live, monitor inhoud én systeemacties en verander slechts één relevante component tegelijk."],
    sections: [
      { id: "scope", eyebrow: "Fase 1", title: "Kies een smalle klantreis met een meetbare klantuitkomst", paragraphs: ["Begin niet met ‘we willen iets met AI’. Kies een gebeurtenis, bijvoorbeeld een gemiste oproep of huurdersmail, en beschrijf de gewenste uitkomst. Wie is geholpen, wat moet in welk systeem staan en wanneer is een mens nodig?", "Benoem een proceseigenaar die inhoudelijke keuzes kan maken. IT, privacy en eindgebruikers leveren randvoorwaarden, maar iemand moet besluiten over vragen, uitzonderingen en acceptatie.", "Leg nulmeting en definities vast. Zonder dezelfde betekenis van een complete intake, geldige afspraak of terechte overdracht kun je geen verbetering beoordelen."] },
      { id: "architectuur", eyebrow: "Fase 2", title: "Ontwerp kennis, regels, tools en rechten als losse lagen", paragraphs: ["Goedgekeurde bronnen beantwoorden inhoudelijke vragen. Gesprekslogica bepaalt welke informatie ontbreekt. Tools lezen of schrijven in systemen. Autorisatie en validatie dwingen harde grenzen af.", "Houd deze lagen scheidbaar. Een nieuwe prijslijst hoort geen codewijziging te vereisen; een modelupdate mag niet stil CRM-rechten veranderen.", "Maak een gegevensstroom met kanaal, persoonsgegevens, opslag, leverancier, bewaartermijn en toegang. Beoordeel privacy en beveiliging vóór productie, niet na de eerste klantvraag."], bullets: ["Bronnen met eigenaar en geldigheidsdatum", "Verplichte velden en uitzonderingsroutes", "Kleine tools met minimale rechten", "Logging zonder geheimen of onnodige data", "Menselijke eigenaar en responstijd"] },
      { id: "testen", eyebrow: "Fase 3", title: "Test conversatie, regels en systeemacties als één keten", paragraphs: ["Een goed antwoord met een verkeerde afspraak is een fout. Test daarom niet alleen tekstkwaliteit, maar ook toolargumenten, autorisatie, writes, bevestiging en overdracht.", "Bouw een vaste evaluatieset met normale vragen, randgevallen, misbruik, ontbrekende data en uitgevallen integraties. Laat inhoudsdeskundigen kritieke uitkomsten beoordelen.", "Herhaal relevante tests na wijzigingen in model, instructies, kennis, tools of CRM. Bewaar resultaten zodat regressies zichtbaar zijn."] },
      { id: "livegang", eyebrow: "Fase 4", title: "Ga gefaseerd live en monitor op klantuitkomst", paragraphs: ["Start met beperkte openingstijden, doelgroep of actietype wanneer risico dat vraagt. Houd een snelle terugweg naar menselijke afhandeling beschikbaar.", "Bekijk gesprekken en systeemacties op juistheid, privacy, compleetheid en klantfrictie. Voeg echte fouten toe aan de evaluatieset en pas bron, regel of tool gericht aan.", "Een AI-medewerker is geen eenmalige oplevering. Productie vraagt wijzigingenbeheer, brononderhoud, incidentroute en periodieke review van rechten en juridische context."] }
    ],
    examples: [{ title: "Pilot autobedrijf", text: "Start met gemiste voorraadoproepen, alleen lezen van voorraad en voorstellen van proefritten. Boeken volgt pas na bevestiging en alle writes worden gecontroleerd." }, { title: "Pilot vastgoedbeheer", text: "Start met classificatie en ticketconcept voor reparatiemeldingen; urgentie en leveranciersopdracht blijven in de eerste fase bij een medewerker." }],
    faq: [{ question: "Hoe lang duurt een implementatie?", answer: "Dat hangt af van scope, bronkwaliteit, integraties, rechten, testcapaciteit en snelheid van besluitvorming. Een vaste universele doorlooptijd is niet betrouwbaar." }, { question: "Moet je eerst alle data opschonen?", answer: "Niet alle data, wel de bronnen en velden die de gekozen route gebruikt. Maak verouderde of tegenstrijdige informatie expliciet." }, { question: "Wie moet eigenaar zijn?", answer: "Een inhoudelijke proceseigenaar met mandaat, ondersteund door IT, privacy/security en de medewerkers die de overdracht ontvangen." }],
    related: [{ label: "Proces", title: "Bekijk het interactieve Autopilots-proces.", href: "/proces/" }, { label: "Kwaliteit", title: "Lees hoe je verkeerde antwoorden voorkomt.", href: "/kennisbank/verkeerde-ai-antwoorden-hallucinaties-voorkomen/" }, { label: "Afspraak", title: "Bespreek een afgebakende eerste route.", href: "/afspraak/" }],
    sources: [openAiAgents, openAiEvals, openAiSafety, euAiLiteracy]
  }),
  article({
    slug: "verkeerde-ai-antwoorden-hallucinaties-voorkomen", category: "AI-betrouwbaarheid", contentCluster: "Implementatie en betrouwbaarheid", readTime: "10 min",
    title: "Hoe voorkom je verkeerde antwoorden en hallucinaties bij AI?", accent: "hallucinaties bij AI?", cardTitle: "Verkeerde AI-antwoorden voorkomen",
    excerpt: "Hallucinaties verdwijnen niet door één betere prompt. Betrouwbaarheid vraagt goedgekeurde bronnen, harde validatie, beperkte acties, tests en een eerlijke onzekerheidsroute.",
    description: "Voorkom verkeerde AI-antwoorden met bronbeheer, retrieval, validatie, toolrechten, evals, monitoring en menselijke overdracht.",
    intent: "Praktische kwaliteitsgids voor betrouwbare AI-antwoorden in klantcontact.", searchIntent: "risico-oplossing", primaryKeyword: "AI hallucinaties voorkomen", audience: "Teams die AI antwoorden of acties richting klanten laten maken.", promise: "Je weet welke maatregelen ieder een ander fouttype beperken.", conversion: "Maak een testset van kritieke vragen, ontbrekende bronnen en toolfouten.",
    keywords: ["AI hallucinaties voorkomen", "verkeerde AI antwoorden", "betrouwbare AI", "RAG kennisbank", "AI guardrails"], relatedArticles: ["ai-medewerker-implementeren", "menselijke-overdracht-ai-klantcontact", "ai-avg-geautomatiseerd-klantcontact"], relatedProducts: ["ai-inboxmedewerker", "ai-telefoniste"], relatedNiches: ["verzekeraars", "tandartsen", "installatietechniek"],
    summary: ["Een taalmodel kan overtuigend klinken terwijl informatie ontbreekt of fout is. Ontwerp dus voor gecontroleerde onzekerheid, niet voor absoluut vertrouwen.", "Retrieval helpt alleen wanneer bronnen actueel, eenduidig en toegestaan zijn; harde bedrijfsregels en toolvalidatie horen buiten het model.", "Test vóór en na livegang met representatieve vragen, misbruik en storingen. Laat risicovolle of onzekere gevallen met context naar een mens gaan."],
    sections: [
      { id: "fouttypen", eyebrow: "Diagnose", title: "Noem niet iedere fout een hallucinatie", paragraphs: ["Een model kan een feit verzinnen, maar een verkeerd antwoord kan ook komen door een oude bron, verkeerde klantkoppeling, onduidelijke instructie, transcriptiefout of mislukte tool.", "Classificeer fouten op oorzaak. Anders probeer je een CRM-bug met prompttekst te repareren of een verouderde prijslijst met een ander model.", "Maak kritieke feiten controleerbaar: bron, versie, klantrecord en toolresultaat moeten terug te vinden zijn voor bevoegde medewerkers."] },
      { id: "kennisbronnen", eyebrow: "Bronbeheer", title: "Laat de AI zoeken in een kleine, goedgekeurde en beheerde bronset", paragraphs: ["Retrieval of file search kan relevante passages uit documenten ophalen. Dat is geen kwaliteitsfilter. Verwijder duplicaten, geef iedere bron een eigenaar, status en geldigheidsdatum en scheid publieke van interne informatie.", "Als betrouwbare informatie ontbreekt of bronnen botsen, hoort de AI dat te benoemen en door te vragen of over te dragen. Laat hem geen ontbrekend beleid invullen op basis van algemene modelkennis."] },
      { id: "harde-controle", eyebrow: "Validatie", title: "Dwing prijzen, rechten en acties af buiten het taalmodel", paragraphs: ["Controleer servicegebied, agenda, productstatus, toegestane korting en veldwaarden in gewone applicatielogica. Een prompt is geen betrouwbare autorisatielaag.", "Splits lezen en schrijven. Vraag bevestiging voor impactvolle acties en controleer na iedere toolcall of de gewenste write echt is gelukt."], bullets: ["Brongebaseerde antwoorden met fallback", "Schema- en bedrijfsregelvalidatie", "Minimale toolrechten", "Bevestiging van kritieke gegevens", "Geen toezegging na mislukte write"] },
      { id: "evals", eyebrow: "Evals", title: "Maak betrouwbaarheid meetbaar met vaste en levende testsets", paragraphs: ["Bouw voorbeelden van normale vragen, parafrases, ontbrekende informatie, conflicterende bronnen, prompt-injectie en toolstoringen. Definieer per case wat een goed antwoord, juiste actie en passende overdracht is.", "Automatische graders kunnen schaal geven, maar kritieke veiligheid, beleid en klantimpact vragen menselijke steekproeven. Voeg productie-incidenten na zorgvuldige behandeling toe als regressietest."] }
    ],
    examples: [{ title: "Prijs ontbreekt", text: "De AI geeft geen schatting uit algemene kennis, maar zegt dat maatwerkcontrole nodig is en maakt een taak voor sales." }, { title: "Agenda faalt", text: "De AI zegt niet dat de afspraak staat. Hij legt een terugbelverzoek vast en draagt de gewenste momenten over." }],
    faq: [{ question: "Kun je hallucinaties volledig uitsluiten?", answer: "Niet als algemene belofte. Je kunt kans en impact sterk beperken met bronbeheer, validatie, beperkte autonomie, tests, monitoring en overdracht." }, { question: "Lost RAG verkeerde antwoorden op?", answer: "RAG helpt relevante bronnen aanbieden, maar slechte, verouderde of tegenstrijdige bronnen blijven een risico. Tool- en redeneerfouten vragen andere maatregelen." }, { question: "Moet je na een modelupdate opnieuw testen?", answer: "Ja. Modelgedrag kan veranderen. Herhaal alle relevante regressietests vóór bredere uitrol." }],
    related: [{ label: "Implementatie", title: "Bekijk het volledige implementatiestappenplan.", href: "/kennisbank/ai-medewerker-implementeren/" }, { label: "Overdracht", title: "Ontwerp de menselijke nooduitgang.", href: "/kennisbank/menselijke-overdracht-ai-klantcontact/" }, { label: "Product", title: "Bekijk de AI Inboxmedewerker.", href: "/producten/ai-inboxmedewerker/" }],
    sources: [openAiFileSearch, openAiEvals, openAiSafety, apAcmChatbots]
  }),
  article({
    slug: "menselijke-overdracht-ai-klantcontact", category: "Menselijke overdracht", contentCluster: "Implementatie en betrouwbaarheid", readTime: "9 min",
    title: "Wanneer moet een medewerker een AI-gesprek overnemen?", accent: "een AI-gesprek overnemen?", cardTitle: "Wanneer moet een medewerker overnemen?",
    excerpt: "Menselijke overdracht is geen mislukking, maar een ontworpen route voor risico, emotie, onzekerheid, klantkeuze en technische fouten.",
    description: "Ontwerp menselijke overdracht bij AI-klantcontact met duidelijke triggers, context, eigenaar, responstijd, klantverwachting en terugkoppeling.",
    intent: "Praktische uitleg over human-in-the-loop en escalatie in AI-klantcontact.", searchIntent: "praktisch", primaryKeyword: "AI gesprek medewerker overnemen", audience: "Service-, sales- en operationele teams die AI in klantcontact inzetten.", promise: "Je ontwerpt een overdracht waarbij klant en medewerker niet opnieuw beginnen.", conversion: "Leg triggers, contextpakket, eigenaar en terugkoppeling vast.",
    keywords: ["AI gesprek medewerker overnemen", "menselijke overdracht AI", "human in the loop", "AI fallback", "chatbot naar medewerker"], relatedArticles: ["verkeerde-ai-antwoorden-hallucinaties-voorkomen", "ai-medewerker-implementeren", "ai-act-chatbot-melden-dat-het-ai-is"], relatedProducts: ["ai-inboxmedewerker", "ai-telefoniste", "ai-leadopvolger"], relatedNiches: ["verzekeraars", "tandartsen", "vastgoedbeheerders"],
    summary: ["Draag over bij expliciet verzoek om een mens, risico, emotie, lage zekerheid, ontbrekende bevoegdheid of een mislukte kritieke tool.", "Stuur kanaal, klantvraag, feitelijke samenvatting, verzamelde gegevens, acties, ontbrekende informatie en reden van overdracht mee.", "Koppel de overdracht aan een concrete wachtrij of eigenaar en vertel de klant eerlijk wat er nu gebeurt."],
    sections: [
      { id: "triggers", eyebrow: "Triggers", title: "Gebruik inhoudelijke, klantgestuurde én technische triggers", paragraphs: ["Klachten, dreiging, veiligheid, privacy, juridische of financiële uitzonderingen en professioneel oordeel zijn duidelijke inhoudelijke triggers. Lage zekerheid en herhaald misverstaan horen daar ook bij.", "De klant moet zelf eenvoudig om een mens kunnen vragen. Toezichthouders AP en ACM benadrukken dat organisaties bij chatbotklantenservice effectieve menselijke communicatie moeten behouden.", "Technische problemen zijn eveneens triggers: agenda niet bereikbaar, CRM-write mislukt, identiteit niet bevestigd of telefonie valt weg. De AI improviseert dan niet over de uitkomst."] },
      { id: "contextpakket", eyebrow: "Context", title: "Laat de medewerker verdergaan in plaats van opnieuw beginnen", paragraphs: ["Een overdracht bevat vraag, feitelijke samenvatting, verzamelde gegevens, reeds uitgevoerde acties, ontbrekende informatie en reden van escalatie. Voeg het oorspronkelijke gesprek beschikbaar toe volgens toegang en bewaarbeleid.", "Vermijd onbewezen interpretaties in de samenvatting. ‘Klant is boos’ kan een inschatting zijn; citeer liever de concrete klacht en urgentie. Markeer wat klant heeft bevestigd en wat AI heeft afgeleid."] },
      { id: "eigenaarschap", eyebrow: "Eigenaarschap", title: "Een taak zonder eigenaar is alleen verplaatst werk", paragraphs: ["Routeer naar team, wachtrij of persoon met een passende responstijd. Laat de klant weten of direct wordt doorverbonden, later wordt teruggebeld of eerst inhoudelijke beoordeling volgt.", "Bouw ook een fallback wanneer niemand beschikbaar is. Sla het verzoek duurzaam op, stuur bevestiging en voorkom dat dezelfde automatisering opnieuw begint."], bullets: ["Concrete eigenaar of wachtrij", "Urgentie en gewenste reactietijd", "Klantverwachting en bevestiging", "Context en brongegevens", "Status terug naar CRM en AI-route"] },
      { id: "leren", eyebrow: "Optimalisatie", title: "Gebruik overdrachten als kwaliteitsbron, niet als cijfer dat altijd omlaag moet", paragraphs: ["Bekijk of overdrachten terecht, tijdig en compleet waren. Een hoger percentage kan positief zijn wanneer risicovolle situaties beter worden herkend.", "Voeg terugkerende onnodige overdrachten toe aan kennis, regels of tests. Verlaag autonomie niet blind en verhoog haar niet om een dashboarddoel te halen."] }
    ],
    examples: [{ title: "Klacht", text: "De AI bevestigt ontvangst, doet geen schuld- of compensatietoezegging en draagt tijdlijn en klantvraag over aan service." }, { title: "Veiligheid", text: "De AI geeft alleen goedgekeurde noodinstructie, verzamelt locatie en contact en schakelt de storingsroute in." }],
    faq: [{ question: "Wanneer moet AI altijd een mens inschakelen?", answer: "Dat volgt uit de eigen risicoanalyse. Veelgebruikte triggers zijn klantverzoek, veiligheid, klachten, privacy, professioneel oordeel, lage zekerheid en mislukte kritieke tools." }, { question: "Is meer zelfstandige afhandeling altijd beter?", answer: "Nee. De juiste klantuitkomst en beheersing wegen zwaarder dan een laag overdrachtspercentage." }, { question: "Wat als geen medewerker beschikbaar is?", answer: "Leg een bevestigde terugbel- of beoordelingsroute vast met eigenaar, urgentie en status. Laat de AI geen oplossing of tijdstip verzinnen." }],
    related: [{ label: "Kwaliteit", title: "Lees hoe je verkeerde antwoorden beperkt.", href: "/kennisbank/verkeerde-ai-antwoorden-hallucinaties-voorkomen/" }, { label: "Product", title: "Bekijk de AI Telefoniste.", href: "/producten/ai-telefoniste/" }, { label: "Proces", title: "Bekijk livegang en monitoring.", href: "/proces/" }],
    sources: [apAcmChatbots, openAiSafety, openAiEvals]
  })
];

const clusterE: KnowledgeArticle[] = [
  article({
    slug: "ai-avg-geautomatiseerd-klantcontact", category: "Privacy en regelgeving", contentCluster: "Privacy, AI Act en ontwikkelingen", pillar: true, readTime: "11 min",
    title: "AI en de AVG: wat moet je regelen bij geautomatiseerd klantcontact?", accent: "geautomatiseerd klantcontact?", cardTitle: "AI, klantcontact en de AVG",
    excerpt: "De AVG verdwijnt niet omdat een leverancier AI gebruikt. Breng doel, grondslag, gegevensstroom, rollen, bewaartermijnen en rechten vóór livegang in kaart.",
    description: "Praktische AVG-checklist voor AI in klantcontact: doel, grondslag, dataminimalisatie, verwerkers, DPIA, bewaartermijnen, rechten en beveiliging.",
    intent: "Praktische privacy-uitleg voor organisaties die AI in klantcontact inzetten.", searchIntent: "risico-informatief", primaryKeyword: "AI AVG klantcontact", audience: "Ondernemers, operations, privacy- en IT-verantwoordelijken.", promise: "Je weet welke privacyvragen vóór ontwerp, inkoop en livegang beantwoord moeten zijn.", conversion: "Teken de gegevensstroom van één klantreis en laat die beoordelen.",
    keywords: ["AI AVG klantcontact", "AVG AI medewerker", "privacy AI chatbot", "DPIA AI", "AI persoonsgegevens"], relatedArticles: ["ai-act-chatbot-melden-dat-het-ai-is", "ai-medewerker-implementeren", "klantcontactprocessen-veilig-automatiseren"], relatedProducts: ["ai-inboxmedewerker", "ai-telefoniste", "autopilots-crm"], relatedNiches: ["tandartsen", "verzekeraars", "vastgoedbeheerders"],
    summary: ["Bepaal eerst waarom gegevens worden verwerkt en welke gegevens echt nodig zijn; AI is geen zelfstandig doel of grondslag.", "Leg vast wie verwerkingsverantwoordelijke en verwerker is, waar gegevens heen gaan, hoe lang ze blijven en wie toegang heeft.", "Beoordeel risico’s, beveiliging, betrokkenenrechten en de noodzaak van een DPIA vóór productie. Dit artikel is praktische uitleg, geen juridisch advies."],
    sections: [
      { id: "doel-en-grondslag", eyebrow: "Startpunt", title: "Begin bij klantdoel en grondslag, niet bij de gekozen AI-tool", paragraphs: ["Beschrijf per klantreis wat het bedrijf wil bereiken: een afspraak plannen, een storing registreren of een vraag beantwoorden. Koppel persoonsgegevens alleen aan dat concrete doel en bepaal met privacydeskundigheid welke AVG-grondslag passend is.", "Vraag niet standaard alles wat technisch mogelijk is. Een postcode kan nodig zijn voor servicegebied; een volledig dossier meestal niet voor een openingsvraag. Scheid verplichte gegevens van handige extra context en vertel de klant begrijpelijk wat ermee gebeurt.", "Bijzondere persoonsgegevens, kwetsbare personen, monitoring of beslissingen met grote impact vragen extra terughoudendheid en specialistische beoordeling."] },
      { id: "gegevensstroom", eyebrow: "Datastroom", title: "Teken ieder systeem, iedere leverancier en iedere opslagstap", paragraphs: ["Een gesprek kan door telefonie, transcriptie, een model, een kennislaag, logging en CRM lopen. Noteer per stap categorieën gegevens, locatie, doel, ontvangers, beveiliging, bewaartermijn en verwijderroute.", "Leg contractueel vast welke partij verwerker of subverwerker is en controleer internationale doorgifte, instellingen voor modeltraining en incidentafspraken. Een marketingclaim als ‘AVG-proof’ vervangt deze beoordeling niet.", "Gebruik gescheiden omgevingen, minimale rechten en waar mogelijk pseudonimisering. Zet geen API-sleutels, volledige dossiers of onnodige gesprekken in logs."] },
      { id: "risico-en-dpia", eyebrow: "Risico", title: "Beoordeel vroeg of een DPIA nodig is en ontwerp maatregelen mee", paragraphs: ["Een gegevensbeschermingseffectbeoordeling is aangewezen wanneer verwerking waarschijnlijk een hoog privacyrisico oplevert. Laat dit beoordelen op basis van de werkelijke toepassing, schaal, gegevens, betrokkenen en impact; alleen het label AI geeft geen volledig antwoord.", "Documenteer verkeerde klantkoppeling, ongewenste openbaarmaking, te lange opslag, onbevoegde toolacties en onvoldoende menselijke route als concrete scenario’s. Koppel ieder risico aan techniek, proces, eigenaar en test.", "Privacy by design betekent dat gegevensbeperking, autorisatie, verwijdering en menselijke controle al in architectuur en acceptatiecriteria staan."] },
      { id: "rechten-en-beheer", eyebrow: "Beheer", title: "Maak inzage, correctie, verwijdering en bezwaar uitvoerbaar", paragraphs: ["Medewerkers moeten kunnen vinden welke gespreksgegevens en afgeleide velden bij een klant horen. Markeer AI-samenvattingen en inschattingen als zodanig, zodat interpretatie niet ongemerkt een vast klantfeit wordt.", "Stel bewaartermijnen per gegevenstype in en test verwijdering ook bij leveranciers en afgeleide indexen. Houd een incidentroute en wijzigingsproces bij wanneer model, leverancier, bron of gebruiksdoel verandert."] }
    ],
    examples: [{ title: "Afspraakplanning", text: "De agent gebruikt naam, contactgegeven en gekozen moment voor de afspraak; het volledige klantdossier is niet standaard beschikbaar." }, { title: "Gespreksanalyse", text: "Voor kwaliteitsanalyse wordt vooraf bepaald welke gesprekken nodig zijn, wie ze mag bekijken, hoe lang ze blijven en hoe betrokkenen hun rechten uitoefenen." }],
    faq: [{ question: "Is een AI-leverancier automatisch verwerkingsverantwoordelijke?", answer: "Nee. Rollen volgen uit wie doel en middelen bepaalt en wat contractueel en feitelijk gebeurt. Laat de concrete keten juridisch beoordelen." }, { question: "Is voor iedere AI-toepassing een DPIA verplicht?", answer: "Niet uitsluitend omdat er AI wordt gebruikt. Een DPIA is nodig wanneer de verwerking waarschijnlijk een hoog privacyrisico oplevert. Beoordeel de echte toepassing en raadpleeg deskundigheid." }, { question: "Mogen klantgesprekken worden bewaard om AI te verbeteren?", answer: "Alleen met een passend doel, grondslag, transparantie, beveiliging en bewaartermijn. Leveranciersinstellingen en contracten moeten daarbij aansluiten." }],
    related: [{ label: "Regelgeving", title: "Lees wanneer je moet melden dat iemand met AI praat.", href: "/kennisbank/ai-act-chatbot-melden-dat-het-ai-is/" }, { label: "Implementatie", title: "Bekijk het implementatiestappenplan.", href: "/kennisbank/ai-medewerker-implementeren/" }, { label: "Afspraak", title: "Bespreek een privacybewuste klantreis.", href: "/afspraak/" }],
    sources: [apAiAvg, apGenerativeAi, apAcmChatbots, euAiAct]
  }),
  article({
    slug: "ai-act-chatbot-melden-dat-het-ai-is", category: "AI Act", contentCluster: "Privacy, AI Act en ontwikkelingen", readTime: "10 min",
    title: "Moet je bij een chatbot of voicebot melden dat het AI is?", accent: "melden dat het AI is?", cardTitle: "Moet je melden dat een chatbot AI is?",
    excerpt: "Ontwerp de interactie zo dat een klant tijdig begrijpt dat die met AI praat en eenvoudig een mens kan bereiken. AVG en AI Act blijven daarbij verschillende kaders.",
    description: "Lees wat de AI Act en Nederlandse toezichthouders zeggen over AI-transparantie, chatbots, voicebots en toegang tot een menselijke medewerker.",
    intent: "Actuele, voorzichtige uitleg van transparantieverplichtingen rond klantgerichte AI.", searchIntent: "juridisch-informatief", primaryKeyword: "chatbot melden dat het AI is", audience: "Organisaties met chatbots, voicebots of AI-medewerkers in klantcontact.", promise: "Je ontwerpt duidelijke AI-melding, menselijke route en bewijsbaar beheer zonder juridische overclaim.", conversion: "Controleer opening, kanaalwissel, overdracht en privacy-informatie.",
    keywords: ["chatbot melden dat het AI is", "AI Act chatbot", "AI transparantieplicht", "voicebot AI melden", "menselijke klantenservice chatbot"], relatedArticles: ["ai-avg-geautomatiseerd-klantcontact", "menselijke-overdracht-ai-klantcontact", "voice-ai-conversational-ai-ontwikkelingen-2026"], relatedProducts: ["ai-inboxmedewerker", "ai-telefoniste"], relatedNiches: ["autobedrijven", "tandartsen", "verzekeraars"],
    summary: ["Laat een klant uiterlijk bij het begin van de relevante interactie duidelijk begrijpen dat een AI-systeem communiceert, tenzij dat uit de context al evident is.", "Bied een werkbare menselijke route wanneer de situatie, het klantverzoek of consumentenrecht dat vraagt; verstop die route niet achter herhaalde botvragen.", "Stand per 15 juli 2026: Europese transparantieregels en concept-richtlijnen zijn in beweging. Controleer vóór livegang de definitieve tekst, toepassingsdatum en eigen juridische context."],
    sections: [
      { id: "actuele-status", eyebrow: "Stand 15 juli 2026", title: "Artikel 50 richt zich op herkenbare interactie met AI", paragraphs: ["De Europese Commissie beschrijft onder de AI Act transparantieverplichtingen voor bepaalde AI-systemen die met mensen interacteren. Het uitgangspunt is dat iemand wordt geïnformeerd dat die met AI communiceert, behalve waar dit voor een redelijk geïnformeerd persoon duidelijk is.", "De Commissie publiceerde concept-richtlijnen en noemt 2 augustus 2026 als toepassingsmoment voor de relevante transparantieregels. Omdat richtlijnen en wetgevingsstatus kunnen wijzigen, hoort de organisatie de definitieve situatie vlak vóór livegang opnieuw te controleren.", "Deze plicht staat naast andere regels. De AVG gaat over persoonsgegevens; consumenten- en sectorspecifieke regels kunnen aanvullende eisen stellen. Een openingszin alleen maakt een gehele toepassing niet compliant."] },
      { id: "goede-melding", eyebrow: "Ontwerp", title: "Maak de melding vroeg, begrijpelijk en passend bij het kanaal", paragraphs: ["In chat kan bij de eerste boodschap staan dat een AI-assistent helpt. Aan de telefoon hoort de voicebot dit natuurlijk uit te spreken voordat een klant veel gegevens deelt. Gebruik gewone taal en leg kort uit wat de rol is.", "Vermijd labels die groter klinken dan de werkelijkheid. Zeg niet dat een volledig klantenserviceteam beschikbaar is wanneer de agent slechts afspraken plant. Herhaal de melding bij een wezenlijke kanaal- of rolwissel wanneer anders verwarring ontstaat.", "Test of mensen de melding zien of horen, ook op mobiel, bij snelle interruptie en na doorverbinden."] },
      { id: "menselijke-route", eyebrow: "Menselijke keuze", title: "Een menselijke route moet in de praktijk werken", paragraphs: ["AP en ACM stelden in 2025 dat een chatbot een mens bij klantenservice niet volledig mag vervangen wanneer effectieve communicatie anders ontbreekt. Ontwerp dus een eenvoudige vraag als ‘ik wil een medewerker spreken’ als echte trigger.", "Vertel eerlijk wat daarna gebeurt: directe overdracht, terugbelverzoek of beoordeling binnen een afgesproken venster. Geef de medewerker vraag, gegevens, reeds uitgevoerde acties en reden van overdracht mee.", "Een bot die de klant na ieder verzoek opnieuw naar hetzelfde menu stuurt, biedt formeel misschien een knop maar geen effectieve route."] },
      { id: "bewijs-en-beheer", eyebrow: "Beheer", title: "Bewaar ontwerpkeuzes, tests en wijzigingsmomenten", paragraphs: ["Leg vast welke melding op welk kanaal wordt gebruikt, welke uitzonderingen gelden en hoe overdracht is getest. Controleer dit opnieuw bij nieuwe stemmen, persona’s, interfaces of kanaalcombinaties.", "Train medewerkers die AI inzetten of de overdracht ontvangen passend bij hun rol. AI-geletterdheid gaat niet alleen over techniek, maar ook over grenzen, risico’s en verantwoord gebruik."] }
    ],
    examples: [{ title: "Chatopening", text: "‘Je chat met de AI-assistent van [bedrijf]. Ik help met afspraken en veelgestelde vragen. Wil je een medewerker, zeg dat dan gerust.’" }, { title: "Voiceopening", text: "‘Je spreekt met onze AI-telefoniste. Ik kan je vraag uitvragen en een afspraak voorstellen; je kunt op ieder moment om een medewerker vragen.’" }],
    faq: [{ question: "Is een klein AI-icoon voldoende?", answer: "Niet vanzelf. De informatie moet tijdig, duidelijk en begrijpelijk zijn in de concrete interface en voor het beoogde publiek." }, { question: "Moet een voicebot ook zeggen dat het AI is?", answer: "Ontwerp daar wel voor. Een natuurlijke stem kan verwarring vergroten; maak de AI-rol aan het begin hoorbaar en controleer de definitieve juridische eisen." }, { question: "Vervangt een AI-melding de privacyverklaring?", answer: "Nee. Transparantie over AI en informatie over verwerking van persoonsgegevens hebben verschillende functies en kunnen beide nodig zijn." }],
    related: [{ label: "Privacy", title: "Lees de AVG-checklist voor AI-klantcontact.", href: "/kennisbank/ai-avg-geautomatiseerd-klantcontact/" }, { label: "Overdracht", title: "Ontwerp de route naar een medewerker.", href: "/kennisbank/menselijke-overdracht-ai-klantcontact/" }, { label: "Ontwikkeling", title: "Bekijk de voice-AI-ontwikkelingen van 2026.", href: "/kennisbank/voice-ai-conversational-ai-ontwikkelingen-2026/" }],
    sources: [euAiAct, euTransparency, apAcmChatbots, euAiLiteracy]
  }),
  article({
    slug: "voice-ai-conversational-ai-ontwikkelingen-2026", category: "Voice AI", contentCluster: "Privacy, AI Act en ontwikkelingen", readTime: "11 min",
    title: "Voice AI en conversational AI in 2026: welke ontwikkelingen zijn relevant?", accent: "ontwikkelingen zijn relevant?", cardTitle: "Voice AI-ontwikkelingen in 2026",
    excerpt: "Voice AI beweegt van losse transcriptie naar realtime, onderbreekbare gesprekken met toolgebruik. Productkwaliteit blijft afhangen van telefonie, latency, regels en fallback.",
    description: "Actuele uitleg over voice AI in 2026: realtime speech-to-speech, full-duplex, transcriptie, vertaling, tools, GPT-Live en productie-eisen.",
    intent: "Actueel overzicht van voice-AI-ontwikkelingen, zonder producthype of speculatie.", searchIntent: "trend-informatief", primaryKeyword: "voice AI ontwikkelingen 2026", audience: "Beslissers en teams die conversational AI of een AI-telefoniste onderzoeken.", promise: "Je onderscheidt relevante technische vooruitgang van een productieklare klantreis.", conversion: "Test één echt telefoonscenario op uitkomst, niet alleen op natuurlijke stem.",
    keywords: ["voice AI ontwikkelingen 2026", "conversational AI 2026", "realtime voice agent", "GPT-Live", "AI telefonie trends"], relatedArticles: ["wat-is-een-ai-telefoniste", "chatbot-voicebot-ai-medewerker-verschil", "ai-act-chatbot-melden-dat-het-ai-is", "verkeerde-ai-antwoorden-hallucinaties-voorkomen"], relatedProducts: ["ai-telefoniste"], relatedNiches: ["tandartsen", "installatietechniek", "kapperszaken"],
    summary: ["Realtime spraakmodellen combineren luisteren en spreken directer, waardoor onderbreken, timing en natuurlijke beurtwisseling beter kunnen worden ontworpen.", "Nieuwe modellen voegen toolgebruik, transcriptie, meertaligheid en soms sterkere redeneercapaciteit samen, maar telefonie en bedrijfslogica blijven aparte productlagen.", "Stand 15 juli 2026: OpenAI kondigde GPT-Live voor ChatGPT Voice aan; API-beschikbaarheid werd bij publicatie nog als toekomstig genoemd. Verwar een productaankondiging niet met een beschikbare productie-API."],
    sections: [
      { id: "realtime", eyebrow: "Realtime", title: "Van keten met losse stappen naar directere speech-to-speech", paragraphs: ["Een klassieke voicebot zet audio om naar tekst, laat een model antwoorden en maakt daar opnieuw audio van. Realtime modellen kunnen spraak directer verwerken en genereren. Dat helpt bij latency, intonatie en natuurlijk onderbreken.", "De winst is niet alleen een mooiere stem. Een bruikbaar gesprek moet weten wanneer de klant klaar is, een correctie herkennen, niet door de klant heen praten en na een stilte passend reageren.", "Telefonienetwerk, ruis, accent, cijfers, namen en slechte verbinding blijven praktische foutbronnen. Test daarom echte oproepen in plaats van alleen een laptopdemo."] },
      { id: "modellen-2026", eyebrow: "Modelontwikkelingen", title: "Meer begrip, vertaling en tools komen in dezelfde realtime route", paragraphs: ["OpenAI introduceerde in mei 2026 onder meer GPT-Realtime-2 en nieuwe realtime spraak- en transcriptiemodellen. De aankondiging legt nadruk op instructievolging, toolgebruik, transcriptie en live vertaling.", "In juli 2026 kondigde OpenAI GPT-Live aan voor ChatGPT Voice, met full-duplex gesprek en sterker geïntegreerde intelligentie. In dezelfde publicatie stond dat toegang via de API gepland was. Voor implementatie moet dus per datum worden gecontroleerd welk model daadwerkelijk beschikbaar, ondersteund en geschikt is.", "De richting is relevant: de voice-agent kan tijdens het gesprek kennis ophalen, agenda controleren of een CRM-actie voorbereiden. Iedere toolactie blijft apart gevalideerd en gelogd."] },
      { id: "productielaag", eyebrow: "Productie", title: "Een geavanceerd model is nog geen betrouwbare AI-telefoniste", paragraphs: ["Naast het model zijn telefoonroutering, nummerherkenning, privacy-informatie, gesprekslogica, agenda, CRM, monitoring en overdracht nodig. Een natuurlijk gesprek dat geen afspraak opslaat, levert geen klantuitkomst.", "Ontwerp voor mislukking: transcriptie onzeker, tool niet bereikbaar, klant wil een mens of de lijn valt weg. Laat de agent geen bevestiging geven zonder aantoonbare systeemactie.", "Beoordeel leveranciers op datastroom, regio-opties, retentie, contracten, observability, modelwissels en kosten per complete route, niet alleen op prijs per minuut."] },
      { id: "keuze", eyebrow: "Keuzehulp", title: "Kies op scenario, risico en systeemactie", paragraphs: ["Gebruik een AI-telefoniste waar mondeling contact snelheid of toegankelijkheid biedt: gemiste oproepen, afspraakintake, storingsvragen of eenvoudige status. Chat of formulier kan beter zijn voor documenten, rustige vergelijking of zeer nauwkeurige schriftelijke bevestiging.", "Meet taakvoltooiing, juiste velden, foutieve bevestigingen, overdrachtskwaliteit en klantinspanning. Een lage gemiddelde gesprekstijd is geen succes als medewerkers daarna alles opnieuw moeten uitvragen."] }
    ],
    examples: [{ title: "Tandarts", text: "De agent begrijpt een afspraakvraag, controleert twee vrije momenten en boekt pas na mondelinge bevestiging; pijn of spoed volgt een aparte triage- en mensroute." }, { title: "Installatie", text: "Tijdens een storingsgesprek verzamelt de agent foutcode en veiligheidsinformatie, maakt een werkbonconcept en schakelt bij risicosignalen direct door." }],
    faq: [{ question: "Is GPT-Live al beschikbaar via de API?", answer: "Volgens OpenAI’s aankondiging van 8 juli 2026 was API-toegang gepland. Controleer de actuele officiële documentatie voordat je architectuur of planning erop baseert." }, { question: "Vervangt realtime voice een telefonieplatform?", answer: "Nee. Nummerbeheer, routering, SIP of andere verbindingen, opnamebeleid, fallback en operationele monitoring blijven nodig." }, { question: "Wat is de belangrijkste voice-AI-meting?", answer: "Meet de correcte klantuitkomst: juiste informatie, complete intake, succesvolle systeemactie of bruikbare overdracht. Combineer dit met latency, fouten en klantinspanning." }],
    related: [{ label: "Basis", title: "Lees wat een AI-telefoniste is.", href: "/kennisbank/wat-is-een-ai-telefoniste/" }, { label: "Vergelijking", title: "Vergelijk chatbot, voicebot en AI-medewerker.", href: "/kennisbank/chatbot-voicebot-ai-medewerker-verschil/" }, { label: "Product", title: "Bekijk de AI Telefoniste.", href: "/producten/ai-telefoniste/" }],
    sources: [openAiVoice2026, openAiGptLive, openAiRealtime, openAiSpeech, euTransparency]
  })
];

export const strategicKnowledgeArticles: KnowledgeArticle[] = [...clusterA, ...clusterB, ...clusterC, ...clusterD, ...clusterE].map((item) => ({
  ...item,
  sections: [...item.sections, ...(articleExpansions[item.slug] ?? [])]
}));
