import type { SupportedLocale } from "./languages";

export const appointmentCopy = {
 nl:{title:"Afspraak plannen | Autopilots",description:"Plan een afspraak en ontdek waar een AI-medewerker werk kan overnemen.",kicker:"Afspraak plannen",hero:"Bekijk waar AI direct werk overneemt.",lead:"Kies een moment. In 30 minuten bepalen we waar AI waarde toevoegt en wat een logische eerste stap is.",context:"Meegenomen in dit gesprek",change:"Wijzig keuze",steps:["Huidige situatie","Beste productroute","Benodigde koppelingen","Concrete vervolgstap"],calendar:"Plan een afspraak met Autopilots",fallback:"Ik kan de kalender niet gebruiken",for:"voor"},
 en:{title:"Book a call | Autopilots",description:"Book a call and discover where an AI colleague can take over work.",kicker:"Book a call",hero:"See where AI can take over work immediately.",lead:"Choose a time. In 30 minutes, we determine where AI adds value and the most logical first step.",context:"Included in this conversation",change:"Change selection",steps:["Current situation","Best product route","Required integrations","Concrete next step"],calendar:"Book a call with Autopilots",fallback:"I cannot use the calendar",for:"for"},
 de:{title:"Termin vereinbaren | Autopilots",description:"Vereinbaren Sie einen Termin und erfahren Sie, wo ein KI-Kollege Arbeit übernehmen kann.",kicker:"Termin vereinbaren",hero:"Sehen Sie, wo KI sofort Arbeit übernimmt.",lead:"Wählen Sie einen Termin. In 30 Minuten bestimmen wir, wo KI Wert schafft und welcher erste Schritt sinnvoll ist.",context:"Im Gespräch berücksichtigt",change:"Auswahl ändern",steps:["Aktuelle Situation","Beste Produktroute","Benötigte Integrationen","Konkreter nächster Schritt"],calendar:"Termin mit Autopilots vereinbaren",fallback:"Ich kann den Kalender nicht verwenden",for:"für"},
 es:{title:"Reservar una llamada | Autopilots",description:"Reserva una llamada y descubre dónde un colaborador de IA puede asumir trabajo.",kicker:"Reservar una llamada",hero:"Descubre dónde la IA puede asumir trabajo de inmediato.",lead:"Elige un momento. En 30 minutos determinamos dónde aporta valor la IA y el primer paso lógico.",context:"Incluido en esta conversación",change:"Cambiar selección",steps:["Situación actual","Mejor ruta de producto","Integraciones necesarias","Siguiente paso concreto"],calendar:"Reservar una llamada con Autopilots",fallback:"No puedo utilizar el calendario",for:"para"},
 it:{title:"Prenota una call | Autopilots",description:"Prenota una call e scopri dove un collega AI può assumere il lavoro.",kicker:"Prenota una call",hero:"Scopri dove l'AI può assumere lavoro da subito.",lead:"Scegli un momento. In 30 minuti determiniamo dove l'AI crea valore e il primo passo logico.",context:"Incluso nella conversazione",change:"Modifica selezione",steps:["Situazione attuale","Miglior percorso prodotto","Integrazioni necessarie","Prossimo passo concreto"],calendar:"Prenota una call con Autopilots",fallback:"Non posso usare il calendario",for:"per"},
 fr:{title:"Planifier un appel | Autopilots",description:"Planifiez un appel et découvrez où un collaborateur IA peut prendre en charge le travail.",kicker:"Planifier un appel",hero:"Découvrez où l'IA peut immédiatement prendre en charge le travail.",lead:"Choisissez un créneau. En 30 minutes, nous déterminons où l'IA apporte de la valeur et la première étape logique.",context:"Pris en compte pendant cet échange",change:"Modifier la sélection",steps:["Situation actuelle","Meilleur parcours produit","Connexions nécessaires","Prochaine étape concrète"],calendar:"Planifier un appel avec Autopilots",fallback:"Je ne peux pas utiliser le calendrier",for:"pour"},
} as const;

export const fallbackFormCopy = {
 nl:{kicker:"Kalender niet beschikbaar?",title:"Laat je gegevens veilig achter.",text:"We nemen contact op om samen een geschikt moment te plannen.",name:"Naam",company:"Bedrijf",email:"Zakelijk e-mailadres",phone:"Telefoonnummer",optional:"optioneel",consent:"Ik ga akkoord met verwerking van mijn gegevens om deze afspraak te plannen.",privacy:"Privacyinformatie",submit:"Vraag een afspraak aan",mail:"Liever direct mailen?",sending:"Je aanvraag wordt veilig verstuurd…",success:"Gelukt. We nemen contact op om een moment af te stemmen.",error:"Versturen is nu niet gelukt. Je kunt ons ook direct e-mailen."},
 en:{kicker:"Calendar unavailable?",title:"Leave your details securely.",text:"We will contact you to arrange a suitable time together.",name:"Name",company:"Company",email:"Business email",phone:"Phone number",optional:"optional",consent:"I agree to the processing of my details to arrange this appointment.",privacy:"Privacy information",submit:"Request an appointment",mail:"Prefer to email directly?",sending:"Your request is being sent securely…",success:"Done. We will contact you to arrange a time.",error:"Your request could not be sent. You can also email us directly."},
 de:{kicker:"Kalender nicht verfügbar?",title:"Hinterlassen Sie Ihre Daten sicher.",text:"Wir melden uns, um gemeinsam einen passenden Termin zu finden.",name:"Name",company:"Unternehmen",email:"Geschäftliche E-Mail",phone:"Telefonnummer",optional:"optional",consent:"Ich stimme der Verarbeitung meiner Daten zur Terminplanung zu.",privacy:"Datenschutzhinweise",submit:"Termin anfragen",mail:"Lieber direkt mailen?",sending:"Ihre Anfrage wird sicher gesendet…",success:"Erledigt. Wir melden uns zur Terminabstimmung.",error:"Die Anfrage konnte nicht gesendet werden. Sie können uns auch direkt mailen."},
 es:{kicker:"¿Calendario no disponible?",title:"Deja tus datos de forma segura.",text:"Nos pondremos en contacto para acordar un momento adecuado.",name:"Nombre",company:"Empresa",email:"Email profesional",phone:"Teléfono",optional:"opcional",consent:"Acepto el tratamiento de mis datos para organizar esta cita.",privacy:"Información de privacidad",submit:"Solicitar una cita",mail:"¿Prefieres escribir directamente?",sending:"Tu solicitud se envía de forma segura…",success:"Listo. Te contactaremos para acordar un momento.",error:"No se pudo enviar la solicitud. También puedes escribirnos directamente."},
 it:{kicker:"Calendario non disponibile?",title:"Lascia i tuoi dati in modo sicuro.",text:"Ti contatteremo per concordare un momento adatto.",name:"Nome",company:"Azienda",email:"Email aziendale",phone:"Telefono",optional:"facoltativo",consent:"Acconsento al trattamento dei dati per organizzare questo appuntamento.",privacy:"Informazioni privacy",submit:"Richiedi un appuntamento",mail:"Preferisci scrivere direttamente?",sending:"La richiesta viene inviata in modo sicuro…",success:"Fatto. Ti contatteremo per concordare un momento.",error:"Non è stato possibile inviare la richiesta. Puoi anche scriverci direttamente."},
 fr:{kicker:"Calendrier indisponible ?",title:"Laissez vos coordonnées en toute sécurité.",text:"Nous vous contacterons pour convenir d'un créneau adapté.",name:"Nom",company:"Entreprise",email:"E-mail professionnel",phone:"Téléphone",optional:"facultatif",consent:"J'accepte le traitement de mes données pour organiser ce rendez-vous.",privacy:"Informations de confidentialité",submit:"Demander un rendez-vous",mail:"Vous préférez écrire directement ?",sending:"Votre demande est envoyée de façon sécurisée…",success:"C'est fait. Nous vous contacterons pour convenir d'un créneau.",error:"La demande n'a pas pu être envoyée. Vous pouvez aussi nous écrire directement."},
} as const;

export const contactCopy = {
 nl:{title:"Contact | Autopilots",description:"Plan een afspraak met Autopilots en ontdek waar AI-medewerkers werk kunnen overnemen in klantcontact, support, planning en opvolging.",kicker:"Contact Autopilots",hero:"Laten we kijken waar AI in jouw proces",accent:"direct werk overneemt.",lead:"Plan een korte kennismaking. We bekijken je huidige workflow en laten zien welke AI-medewerker logisch is als eerste stap.",appointment:"Plan afspraak",products:"Bekijk producten",chips:["Demo","Advies","Workflow","CRM","Livegang"],plan:"Afspraak plannen",calendarTitle:"Kies direct een moment in de agenda.",calendarText:"We kijken naar je huidige situatie en bepalen welk AI-product als eerste logisch waarde toevoegt.",calendar:"Plan een afspraak met Autopilots"},
 en:{title:"Contact | Autopilots",description:"Book a call with Autopilots and discover where AI colleagues can take over work in customer contact, support, planning and follow-up.",kicker:"Contact Autopilots",hero:"Let us find where AI can",accent:"take over work immediately.",lead:"Book a short introduction. We review your current workflow and show which AI colleague is the logical first step.",appointment:"Book a call",products:"View products",chips:["Demo","Advice","Workflow","CRM","Launch"],plan:"Book a call",calendarTitle:"Choose a time directly in the calendar.",calendarText:"We review your current situation and determine which AI product can add value first.",calendar:"Book a call with Autopilots"},
 es:{title:"Contacto | Autopilots",description:"Reserva una llamada con Autopilots y descubre dónde los colaboradores de IA pueden asumir tareas de atención, soporte, agenda y seguimiento.",kicker:"Contacta con Autopilots",hero:"Veamos dónde la IA puede",accent:"asumir trabajo de inmediato.",lead:"Reserva una breve presentación. Revisamos tu flujo actual y mostramos qué colaborador de IA es el primer paso lógico.",appointment:"Reservar llamada",products:"Ver productos",chips:["Demo","Asesoramiento","Flujo","CRM","Lanzamiento"],plan:"Reservar una llamada",calendarTitle:"Elige directamente un momento en la agenda.",calendarText:"Revisamos tu situación actual y determinamos qué producto de IA puede aportar valor primero.",calendar:"Reservar una llamada con Autopilots"},
 de:{title:"Kontakt | Autopilots",description:"Vereinbaren Sie einen Termin mit Autopilots und erfahren Sie, wo KI-Kollegen Arbeit in Kundenkontakt, Support, Planung und Nachverfolgung übernehmen.",kicker:"Autopilots kontaktieren",hero:"Finden wir heraus, wo KI",accent:"sofort Arbeit übernimmt.",lead:"Vereinbaren Sie ein kurzes Kennenlernen. Wir betrachten Ihren aktuellen Ablauf und zeigen, welcher KI-Kollege der logische erste Schritt ist.",appointment:"Termin vereinbaren",products:"Produkte ansehen",chips:["Demo","Beratung","Workflow","CRM","Livegang"],plan:"Termin vereinbaren",calendarTitle:"Wählen Sie direkt einen Termin im Kalender.",calendarText:"Wir betrachten Ihre aktuelle Situation und bestimmen, welches KI-Produkt zuerst Mehrwert schafft.",calendar:"Termin mit Autopilots vereinbaren"},
 it:{title:"Contatti | Autopilots",description:"Prenota una call con Autopilots e scopri dove i collaboratori AI possono assumere attività di contatto, supporto, pianificazione e follow-up.",kicker:"Contatta Autopilots",hero:"Scopriamo dove l'AI può",accent:"assumere subito il lavoro.",lead:"Prenota una breve presentazione. Analizziamo il flusso attuale e mostriamo quale collaboratore AI è il primo passo logico.",appointment:"Prenota una call",products:"Vedi prodotti",chips:["Demo","Consulenza","Workflow","CRM","Lancio"],plan:"Prenota una call",calendarTitle:"Scegli direttamente un momento nel calendario.",calendarText:"Analizziamo la situazione attuale e determiniamo quale prodotto AI può creare valore per primo.",calendar:"Prenota una call con Autopilots"},
 fr:{title:"Contact | Autopilots",description:"Planifiez un échange avec Autopilots et découvrez où des collaborateurs IA peuvent prendre en charge la relation client, l'assistance, la planification et le suivi.",kicker:"Contacter Autopilots",hero:"Voyons où l'IA peut",accent:"prendre immédiatement le relais.",lead:"Planifiez une courte présentation. Nous analysons votre fonctionnement actuel et montrons quel collaborateur IA constitue la première étape logique.",appointment:"Planifier un appel",products:"Voir les produits",chips:["Démo","Conseil","Parcours","CRM","Lancement"],plan:"Planifier un appel",calendarTitle:"Choisissez directement un créneau dans l'agenda.",calendarText:"Nous analysons votre situation et déterminons quel produit IA peut apporter de la valeur en premier.",calendar:"Planifier un appel avec Autopilots"}
} as const satisfies Record<SupportedLocale, Record<string, unknown>>;
