import type { KnowledgeArticle } from "../content/knowledgeArticles";
import type { SupportedLocale } from "./languages";

const titleRows: Record<string,Record<SupportedLocale,string>> = {
 "wat-is-een-ai-medewerker":{nl:"Wat is een AI-medewerker?",en:"What is an AI employee?",es:"¿Qué es un empleado de IA?",de:"Was ist ein KI-Mitarbeiter?",it:"Cos'è un collaboratore AI?",fr:"Qu'est-ce qu'un collaborateur IA ?"},
 "wat-is-een-ai-telefoniste":{nl:"Wat is een AI-telefoniste?",en:"What is an AI receptionist?",es:"¿Qué es una recepcionista de IA?",de:"Was ist ein KI-Telefonassistent?",it:"Cos'è un receptionist AI?",fr:"Qu'est-ce qu'un standardiste IA ?"},
 "chatbot-voicebot-ai-medewerker-verschil":{nl:"Chatbot, voicebot of AI-medewerker: wat is het verschil?",en:"Chatbot, voicebot or AI employee: what is the difference?",es:"Chatbot, voicebot o empleado de IA: ¿cuál es la diferencia?",de:"Chatbot, Voicebot oder KI-Mitarbeiter: Was ist der Unterschied?",it:"Chatbot, voicebot o collaboratore AI: qual è la differenza?",fr:"Chatbot, voicebot ou collaborateur IA : quelle différence ?"},
 "wat-is-ai-leadopvolging":{nl:"Wat is AI-leadopvolging?",en:"What is AI lead follow-up?",es:"¿Qué es el seguimiento de leads con IA?",de:"Was ist KI-Lead-Nachverfolgung?",it:"Cos'è il follow-up dei lead con AI?",fr:"Qu'est-ce que le suivi de leads par IA ?"},
 "hoe-snel-nieuwe-lead-opvolgen":{nl:"Hoe snel moet je een nieuwe lead opvolgen?",en:"How quickly should you follow up a new lead?",es:"¿Con qué rapidez debes contactar un nuevo lead?",de:"Wie schnell sollten neue Leads nachverfolgt werden?",it:"Quanto velocemente seguire un nuovo lead?",fr:"Dans quel délai relancer un nouveau lead ?"},
 "roi-automatische-leadopvolging-berekenen":{nl:"ROI van automatische leadopvolging berekenen",en:"How to calculate the ROI of automated lead follow-up",es:"Cómo calcular el ROI del seguimiento automático de leads",de:"ROI automatisierter Lead-Nachverfolgung berechnen",it:"Come calcolare il ROI del follow-up automatico dei lead",fr:"Comment calculer le ROI du suivi automatisé des leads"},
 "ai-email-whatsapp-websitechat":{nl:"AI voor e-mail, WhatsApp en websitechat",en:"AI for email, WhatsApp and website chat",es:"IA para email, WhatsApp y chat web",de:"KI für E-Mail, WhatsApp und Website-Chat",it:"AI per email, WhatsApp e chat del sito",fr:"L'IA pour l'e-mail, WhatsApp et le chat du site"},
 "hoe-werken-ai-en-crm-samen":{nl:"Hoe werken AI en CRM samen?",en:"How do AI and CRM work together?",es:"¿Cómo funcionan juntos la IA y el CRM?",de:"Wie arbeiten KI und CRM zusammen?",it:"Come lavorano insieme AI e CRM?",fr:"Comment l'IA et le CRM fonctionnent-ils ensemble ?"},
 "klantcontactprocessen-veilig-automatiseren":{nl:"Klantcontactprocessen veilig automatiseren",en:"How to automate customer contact safely",es:"Cómo automatizar la atención al cliente de forma segura",de:"Kundenkontakt sicher automatisieren",it:"Come automatizzare il contatto clienti in sicurezza",fr:"Comment automatiser la relation client en toute sécurité"},
 "ai-medewerker-implementeren":{nl:"Een AI-medewerker implementeren",en:"How to implement an AI employee",es:"Cómo implementar un empleado de IA",de:"Einen KI-Mitarbeiter implementieren",it:"Come implementare un collaboratore AI",fr:"Comment mettre en place un collaborateur IA"},
 "verkeerde-ai-antwoorden-hallucinaties-voorkomen":{nl:"Verkeerde AI-antwoorden en hallucinaties voorkomen",en:"How to prevent AI hallucinations and incorrect answers",es:"Cómo evitar alucinaciones y respuestas incorrectas de la IA",de:"KI-Halluzinationen und falsche Antworten vermeiden",it:"Come evitare allucinazioni e risposte errate dell'AI",fr:"Comment éviter les hallucinations et mauvaises réponses de l'IA"},
 "menselijke-overdracht-ai-klantcontact":{nl:"Menselijke overdracht in AI-klantcontact",en:"Human handoff in AI customer contact",es:"Transferencia humana en la atención al cliente con IA",de:"Menschliche Übergabe im KI-Kundenkontakt",it:"Passaggio umano nel contatto clienti con AI",fr:"Le transfert humain dans la relation client assistée par IA"},
 "ai-avg-geautomatiseerd-klantcontact":{nl:"AI, AVG en geautomatiseerd klantcontact",en:"AI, GDPR and automated customer contact",es:"IA, RGPD y atención al cliente automatizada",de:"KI, DSGVO und automatisierter Kundenkontakt",it:"AI, GDPR e contatto clienti automatizzato",fr:"IA, RGPD et relation client automatisée"},
 "ai-act-chatbot-melden-dat-het-ai-is":{nl:"AI Act: moet je melden dat een chatbot AI is?",en:"AI Act: must you disclose that a chatbot is AI?",es:"Ley de IA: ¿hay que indicar que un chatbot es IA?",de:"AI Act: Muss ein Chatbot als KI gekennzeichnet werden?",it:"AI Act: bisogna dichiarare che un chatbot è AI?",fr:"AI Act : faut-il signaler qu'un chatbot est une IA ?"},
 "voice-ai-conversational-ai-ontwikkelingen-2026":{nl:"Voice AI en conversational AI: ontwikkelingen in 2026",en:"Voice AI and conversational AI trends in 2026",es:"Tendencias de Voice AI e IA conversacional en 2026",de:"Voice AI und Conversational-AI-Trends 2026",it:"Tendenze Voice AI e AI conversazionale nel 2026",fr:"Tendances Voice AI et IA conversationnelle en 2026"}
};

export function articleTitle(locale:SupportedLocale,slug:string,fallback:string){return titleRows[slug]?.[locale]??fallback}

const packs = {
 en:{category:"Practical AI",label:"Guide",read:"min read",excerpt:(t:string)=>`A practical guide to ${t.toLowerCase()}, with clear choices for customer contact, systems and human handoff.`,summary:["Start with a clearly defined customer journey and a measurable outcome.","Connect knowledge, permissions and systems before automating actions.","Keep human review available for uncertainty, risk and exceptions."],eyes:["Context","How it works","Implementation","Systems","Boundaries","Results"],heads:["What this means in daily operations","From customer question to controlled action","How to implement this safely","The role of data and connected systems","Where people remain in control","How to measure practical value"],paras:(t:string)=>[`The practical value of ${t.toLowerCase()} comes from combining language understanding with approved knowledge and a clear next action. The route must be understandable for customers and the team.`,`A reliable setup defines inputs, decisions, permissions and fallback before launch. That prevents a standalone demo and creates a process that can be monitored and improved.`],bullets:["Define scope and success criteria","Use approved knowledge and permissions","Record every outcome in the right system","Transfer uncertainty with full context"],example:"A customer receives an immediate, useful next step while the team receives the complete context and a clear owner.",faqQ:["Can this work with our current systems?","When should a person take over?","How do you prevent incorrect actions?","How quickly can this go live?"],faqA:["That depends on available APIs, permissions and required actions; these are verified before implementation.","Risk, uncertainty, emotion and exceptions are transferred with the full conversation context.","Actions follow approved knowledge, explicit permissions, validation and fallback rules.","A first route can often launch in two to four weeks once access, content and feedback are available."]},
 es:{category:"IA práctica",label:"Guía",read:"min de lectura",excerpt:(t:string)=>`Guía práctica sobre ${t.toLowerCase()}, con decisiones claras para atención, sistemas y transferencia humana.`,summary:["Empieza con un recorrido definido y un resultado medible.","Conecta conocimiento, permisos y sistemas antes de automatizar acciones.","Mantén revisión humana para incertidumbre, riesgo y excepciones."],eyes:["Contexto","Funcionamiento","Implementación","Sistemas","Límites","Resultados"],heads:["Qué significa en la operativa diaria","De la consulta a una acción controlada","Cómo implementarlo con seguridad","El papel de los datos y sistemas conectados","Dónde las personas mantienen el control","Cómo medir el valor práctico"],paras:(t:string)=>[`El valor práctico de ${t.toLowerCase()} nace de combinar comprensión del lenguaje, conocimiento aprobado y una siguiente acción clara. El recorrido debe ser comprensible para cliente y equipo.`,`Una configuración fiable define entradas, decisiones, permisos y transferencia antes del lanzamiento. Así se crea un proceso que puede medirse y mejorarse.`],bullets:["Define alcance y criterios de éxito","Usa conocimiento y permisos aprobados","Registra cada resultado en el sistema correcto","Transfiere la incertidumbre con todo el contexto"],example:"El cliente recibe un siguiente paso útil de inmediato y el equipo recibe contexto completo y un responsable claro.",faqQ:["¿Puede funcionar con nuestros sistemas?","¿Cuándo interviene una persona?","¿Cómo se evitan acciones incorrectas?","¿Cuándo puede estar activo?"],faqA:["Depende de APIs, permisos y acciones; se comprueba antes de implementar.","Riesgo, incertidumbre, emoción y excepciones se transfieren con todo el contexto.","Las acciones siguen conocimiento aprobado, permisos, validación y reglas de transferencia.","Una primera ruta puede estar activa en dos a cuatro semanas cuando hay accesos, contenido y feedback."]},
 de:{category:"KI-Praxis",label:"Leitfaden",read:"Min. Lesezeit",excerpt:(t:string)=>`Praxisleitfaden zu ${t.toLowerCase()} mit klaren Entscheidungen für Kundenkontakt, Systeme und menschliche Übergabe.`,summary:["Beginnen Sie mit einer klaren Kundenreise und messbarem Ergebnis.","Verbinden Sie Wissen, Rechte und Systeme, bevor Aktionen automatisiert werden.","Menschliche Prüfung bleibt bei Unsicherheit, Risiko und Ausnahmen verfügbar."],eyes:["Kontext","Funktionsweise","Implementierung","Systeme","Grenzen","Ergebnisse"],heads:["Was dies im Alltag bedeutet","Von der Kundenfrage zur kontrollierten Aktion","So wird es sicher implementiert","Die Rolle von Daten und verbundenen Systemen","Wo Menschen die Kontrolle behalten","So wird der praktische Wert gemessen"],paras:(t:string)=>[`Der praktische Wert von ${t.toLowerCase()} entsteht durch Sprachverständnis, freigegebenes Wissen und eine klare nächste Aktion. Die Route muss für Kunden und Team verständlich sein.`,`Eine verlässliche Einrichtung definiert Eingaben, Entscheidungen, Rechte und Übergaben vor dem Livegang. So entsteht ein messbarer und verbesserbarer Prozess.`],bullets:["Umfang und Erfolgskriterien definieren","Freigegebenes Wissen und Rechte nutzen","Jedes Ergebnis im richtigen System speichern","Unsicherheit mit vollständigem Kontext übergeben"],example:"Der Kunde erhält sofort einen sinnvollen nächsten Schritt; das Team bekommt vollständigen Kontext und eine klare Zuständigkeit.",faqQ:["Funktioniert das mit bestehenden Systemen?","Wann übernimmt ein Mensch?","Wie werden falsche Aktionen verhindert?","Wie schnell kann es live gehen?"],faqA:["Das hängt von APIs, Rechten und Aktionen ab und wird vorab geprüft.","Risiko, Unsicherheit, Emotion und Ausnahmen werden mit vollständigem Kontext übergeben.","Aktionen folgen freigegebenem Wissen, Rechten, Validierung und Übergaberegeln.","Eine erste Route kann bei verfügbaren Zugängen, Inhalten und Feedback oft in zwei bis vier Wochen starten."]},
 it:{category:"AI pratica",label:"Guida",read:"min di lettura",excerpt:(t:string)=>`Guida pratica a ${t.toLowerCase()}, con scelte chiare per contatto clienti, sistemi e passaggio umano.`,summary:["Parti da un customer journey definito e un risultato misurabile.","Collega conoscenze, permessi e sistemi prima di automatizzare azioni.","Mantieni la revisione umana per incertezza, rischio ed eccezioni."],eyes:["Contesto","Funzionamento","Implementazione","Sistemi","Limiti","Risultati"],heads:["Cosa significa nel lavoro quotidiano","Dalla richiesta a un'azione controllata","Come implementarlo in sicurezza","Il ruolo dei dati e dei sistemi collegati","Dove le persone mantengono il controllo","Come misurare il valore pratico"],paras:(t:string)=>[`Il valore pratico di ${t.toLowerCase()} nasce dalla comprensione del linguaggio, da conoscenze approvate e da una chiara azione successiva. Il percorso deve essere comprensibile per cliente e team.`,`Una configurazione affidabile definisce input, decisioni, permessi e passaggi prima del lancio. Così il processo può essere misurato e migliorato.`],bullets:["Definisci ambito e criteri di successo","Usa conoscenze e permessi approvati","Registra ogni risultato nel sistema giusto","Trasferisci l'incertezza con tutto il contesto"],example:"Il cliente riceve subito un passo utile, mentre il team ottiene contesto completo e un responsabile chiaro.",faqQ:["Funziona con i sistemi esistenti?","Quando interviene una persona?","Come si evitano azioni errate?","Quanto velocemente può andare online?"],faqA:["Dipende da API, permessi e azioni e viene verificato prima dell'implementazione.","Rischio, incertezza, emozione ed eccezioni vengono trasferiti con tutto il contesto.","Le azioni seguono conoscenze approvate, permessi, validazione e regole di passaggio.","Una prima rotta può partire in due-quattro settimane quando accessi, contenuti e feedback sono disponibili."]},
 fr:{category:"IA pratique",label:"Guide",read:"min de lecture",excerpt:(t:string)=>`Guide pratique sur ${t.toLowerCase()}, avec des choix clairs pour la relation client, les systèmes et le transfert humain.`,summary:["Commencez par un parcours défini et un résultat mesurable.","Reliez connaissances, droits et systèmes avant d'automatiser les actions.","Conservez une validation humaine pour l'incertitude, le risque et les exceptions."],eyes:["Contexte","Fonctionnement","Implémentation","Systèmes","Limites","Résultats"],heads:["Ce que cela signifie au quotidien","De la demande à une action maîtrisée","Comment l'implémenter en sécurité","Le rôle des données et systèmes connectés","Où l'humain conserve le contrôle","Comment mesurer la valeur pratique"],paras:(t:string)=>[`La valeur pratique de ${t.toLowerCase()} vient de la compréhension du langage, des connaissances validées et d'une prochaine action claire. Le parcours doit rester compréhensible pour le client et l'équipe.`,`Une configuration fiable définit entrées, décisions, droits et transferts avant le lancement. Le processus peut ainsi être mesuré et amélioré.`],bullets:["Définir le périmètre et les critères de réussite","Utiliser des connaissances et droits validés","Enregistrer chaque résultat dans le bon système","Transférer l'incertitude avec tout le contexte"],example:"Le client reçoit immédiatement une prochaine étape utile, tandis que l'équipe obtient le contexte complet et un responsable clair.",faqQ:["Cela fonctionne-t-il avec nos systèmes ?","Quand un humain prend-il le relais ?","Comment éviter les actions incorrectes ?","Sous quel délai cela peut-il être lancé ?"],faqA:["Cela dépend des API, droits et actions, vérifiés avant l'implémentation.","Risque, incertitude, émotion et exceptions sont transférés avec tout le contexte.","Les actions suivent les connaissances validées, les droits, la validation et les règles de transfert.","Un premier parcours peut souvent être lancé sous deux à quatre semaines lorsque les accès, contenus et retours sont disponibles."]}
};

export function localizedArticle(locale:SupportedLocale,source:KnowledgeArticle):KnowledgeArticle{
 if(locale==="nl") return source;
 const p=packs[locale]; const title=articleTitle(locale,source.slug,source.title);
 const clusterIndex=["AI-medewerkers en klantcontact","Leads en conversie","Inbox, CRM en automatisering","Implementatie en betrouwbaarheid","Privacy, AI Act en ontwikkelingen"].indexOf(source.contentCluster??"");
 const clusters={en:["AI colleagues and customer contact","Leads and conversion","Inbox, CRM and automation","Implementation and reliability","Privacy, AI Act and developments"],es:["Colaboradores de IA y atención","Leads y conversión","Bandeja, CRM y automatización","Implementación y fiabilidad","Privacidad, Ley de IA y novedades"],de:["KI-Kollegen und Kundenkontakt","Leads und Conversion","Postfach, CRM und Automatisierung","Implementierung und Zuverlässigkeit","Datenschutz, AI Act und Entwicklungen"],it:["Collaboratori AI e contatto","Lead e conversione","Inbox, CRM e automazione","Implementazione e affidabilità","Privacy, AI Act e sviluppi"],fr:["Collaborateurs IA et relation client","Leads et conversion","Messagerie, CRM et automatisation","Implémentation et fiabilité","Confidentialité, AI Act et évolutions"]}[locale];
 const contentCluster=clusters[Math.max(0,clusterIndex)]??p.category;
 return {...source,title,accent:"",cardTitle:title,category:p.category,contentCluster,label:p.label,readTime:`${source.readTime.match(/\d+/)?.[0]??"7"} ${p.read}`,excerpt:p.excerpt(title),description:p.excerpt(title),author:"Autopilots",keywords:[title,p.category,"Autopilots"],summary:source.summary.map((_,i)=>p.summary[i%p.summary.length]),sections:source.sections.map((section,i)=>({...section,eyebrow:p.eyes[i%p.eyes.length],title:p.heads[i%p.heads.length],paragraphs:section.paragraphs.map((_,j)=>p.paras(title)[j%2]),bullets:section.bullets?.map((_,j)=>p.bullets[j%p.bullets.length])})),examples:source.examples?.map((_,i)=>({title:`${p.eyes[(i+1)%p.eyes.length]} ${i+1}`,text:p.example})),faq:source.faq.map((_,i)=>({question:p.faqQ[i%p.faqQ.length],answer:p.faqA[i%p.faqA.length]}))};
}

export const knowledgeOverviewCopy = {
 nl:{title:"Autopilots kennisbank | AI kennis en implementatiekennis",description:"Kies AI kennis of Autopilots implementatiekennis.",kicker:"Autopilots kennisbank",hero:"Je staat op de splitsing. Kies links AI kennis of rechts",accent:"Autopilots kennis.",lead:"Links vind je kennis over AI-tools, modellen en toepassingen. Rechts vind je hoe Autopilots AI omzet naar werkende systemen, klantreizen, CRM-acties en optimalisatie.",choose:"Kies kennisroute",aria:"Kennisroutes",roadAria:"Kies je kennisroute",ai:"AI kennis",ap:"Autopilots kennis",route:"Route",aiTitle:"Ga naar AI kennis.",aiText:"Tools, modellen, OpenAI, Claude, AI-nieuws, voice agents, chat agents en nichegerichte uitleg.",apTitle:"Ga naar Autopilots kennis.",apText:"AI-breinen, klantreizen, koppelingen, CRM-acties, livegang, monitoring en lessen uit implementaties.",latest:"Laatste kennis",latestTitle:"Laatste kennis voor ondernemers die AI praktisch willen toepassen.",latestText:"Praktische uitleg over tools, klantcontact, branches, implementatie en systemen die in de dagelijkse operatie werken."},
 en:{title:"Autopilots knowledge | AI and implementation guides",description:"Choose AI knowledge or Autopilots implementation knowledge.",kicker:"Autopilots knowledge",hero:"You are at the junction. Choose AI knowledge on the left or",accent:"Autopilots knowledge on the right.",lead:"On the left: AI tools, models and applications. On the right: how Autopilots turns AI into working systems, customer journeys, CRM actions and optimisation.",choose:"Choose a knowledge route",aria:"Knowledge routes",roadAria:"Choose your knowledge route",ai:"AI knowledge",ap:"Autopilots knowledge",route:"Route",aiTitle:"Go to AI knowledge.",aiText:"Tools, models, OpenAI, Claude, AI news, voice agents, chat agents and industry-focused explanations.",apTitle:"Go to Autopilots knowledge.",apText:"AI brains, customer journeys, integrations, CRM actions, launch, monitoring and implementation lessons.",latest:"Latest knowledge",latestTitle:"Latest guidance for companies applying AI in practice.",latestText:"Practical explanations about tools, customer contact, industries, implementation and systems that work in daily operations."},
 es:{title:"Conocimientos Autopilots | IA e implementación",description:"Elige conocimientos sobre IA o sobre implementación Autopilots.",kicker:"Conocimientos Autopilots",hero:"Estás en el cruce. Elige conocimientos de IA a la izquierda o",accent:"conocimientos Autopilots a la derecha.",lead:"A la izquierda: herramientas, modelos y aplicaciones de IA. A la derecha: cómo Autopilots crea sistemas, recorridos, acciones CRM y optimización.",choose:"Elegir ruta",aria:"Rutas de conocimiento",roadAria:"Elige tu ruta",ai:"Conocimientos de IA",ap:"Conocimientos Autopilots",route:"Ruta",aiTitle:"Ir a conocimientos de IA.",aiText:"Herramientas, modelos, OpenAI, Claude, noticias, agentes de voz y chat y explicaciones por sector.",apTitle:"Ir a conocimientos Autopilots.",apText:"Cerebros de IA, recorridos, integraciones, acciones CRM, lanzamiento, monitorización y lecciones.",latest:"Últimos conocimientos",latestTitle:"Guías recientes para aplicar la IA en la práctica.",latestText:"Explicaciones sobre herramientas, atención, sectores, implementación y sistemas que funcionan a diario."},
 de:{title:"Autopilots Wissen | KI und Implementierung",description:"Wählen Sie KI-Wissen oder Autopilots Implementierungswissen.",kicker:"Autopilots Wissen",hero:"Sie stehen an der Abzweigung. Links geht es zu KI-Wissen, rechts zu",accent:"Autopilots Wissen.",lead:"Links: KI-Tools, Modelle und Anwendungen. Rechts: wie Autopilots daraus Systeme, Kundenreisen, CRM-Aktionen und Optimierung baut.",choose:"Wissensroute wählen",aria:"Wissensrouten",roadAria:"Wissensroute wählen",ai:"KI-Wissen",ap:"Autopilots Wissen",route:"Route",aiTitle:"Zum KI-Wissen.",aiText:"Tools, Modelle, OpenAI, Claude, KI-News, Voice- und Chat-Agents sowie Branchenerklärungen.",apTitle:"Zum Autopilots Wissen.",apText:"KI-Gehirne, Kundenreisen, Integrationen, CRM-Aktionen, Livegang, Monitoring und Erfahrungen.",latest:"Aktuelles Wissen",latestTitle:"Aktuelle Leitfäden für die praktische KI-Anwendung.",latestText:"Praxiswissen über Tools, Kundenkontakt, Branchen, Implementierung und Systeme für den Alltag."},
 it:{title:"Conoscenza Autopilots | AI e implementazione",description:"Scegli conoscenza AI o conoscenza sull'implementazione Autopilots.",kicker:"Conoscenza Autopilots",hero:"Sei al bivio. Scegli la conoscenza AI a sinistra o",accent:"la conoscenza Autopilots a destra.",lead:"A sinistra: strumenti, modelli e applicazioni AI. A destra: come Autopilots crea sistemi, customer journey, azioni CRM e ottimizzazione.",choose:"Scegli il percorso",aria:"Percorsi di conoscenza",roadAria:"Scegli il percorso",ai:"Conoscenza AI",ap:"Conoscenza Autopilots",route:"Percorso",aiTitle:"Vai alla conoscenza AI.",aiText:"Strumenti, modelli, OpenAI, Claude, notizie, agenti vocali e chat e spiegazioni per settore.",apTitle:"Vai alla conoscenza Autopilots.",apText:"Cervelli AI, customer journey, integrazioni, azioni CRM, lancio, monitoraggio e lezioni.",latest:"Ultime conoscenze",latestTitle:"Guide recenti per applicare l'AI nella pratica.",latestText:"Spiegazioni su strumenti, contatto clienti, settori, implementazione e sistemi operativi."},
 fr:{title:"Connaissances Autopilots | IA et implémentation",description:"Choisissez les connaissances IA ou les méthodes d'implémentation Autopilots.",kicker:"Connaissances Autopilots",hero:"Vous êtes à l'intersection. À gauche, les connaissances IA ; à droite,",accent:"les connaissances Autopilots.",lead:"À gauche : outils, modèles et applications IA. À droite : comment Autopilots crée systèmes, parcours clients, actions CRM et optimisation.",choose:"Choisir un parcours",aria:"Parcours de connaissances",roadAria:"Choisir votre parcours",ai:"Connaissances IA",ap:"Connaissances Autopilots",route:"Parcours",aiTitle:"Accéder aux connaissances IA.",aiText:"Outils, modèles, OpenAI, Claude, actualités, agents vocaux et chat et explications métier.",apTitle:"Accéder aux connaissances Autopilots.",apText:"Cerveaux IA, parcours, connexions, actions CRM, lancement, suivi et enseignements.",latest:"Dernières connaissances",latestTitle:"Guides récents pour appliquer l'IA concrètement.",latestText:"Explications sur les outils, la relation client, les secteurs, l'implémentation et les systèmes opérationnels."}
} as const;
