import type { SupportedLocale } from "./languages";

const privacySections = {
 nl:[
  ["verantwoordelijke","Verantwoordelijke","Autopilots beheert deze website en de aanvragen die hier binnenkomen.","Voor vragen over privacy of de verwerking van persoonsgegevens kun je mailen naar info@auto-pilots.io. De formele bedrijfsidentiteit en vestigingsgegevens worden vóór juridische eindgoedkeuring door de verantwoordelijke bevestigd."],
  ["welke-gegevens","Welke gegevens","Alleen wat nodig is voor contact, planning en uitvoering.","Wanneer je een afspraak plant of contact opneemt, kunnen naam, zakelijke contactgegevens, bedrijfsinformatie, afspraakgegevens en de inhoud van je verzoek worden verwerkt. Bij een bestelling verwerkt de betaalprovider ook betaal- en transactiegegevens. Autopilots ontvangt niet automatisch je volledige betaalkaartgegevens."],
  ["waarom","Waarom en grondslag","Om te reageren, een afspraak te plannen en afspraken uit te voeren.","We verwerken gegevens wanneer dat nodig is om op jouw verzoek stappen te zetten vóór of tijdens een overeenkomst, om wettelijke administratie te voeren, de website te beveiligen en — waar vereist — op basis van toestemming. Toestemming kun je voor toekomstige verwerking intrekken."],
  ["diensten","Externe diensten","Kalender, CRM, AI-demo en betaling hebben ieder een afgebakende rol.","De afspraakmodule en CRM-verwerking lopen via LeadConnector/GoHighLevel. Bevestigde betaalroutes gebruiken Stripe. Een voice-demo kan na jouw actieve start ElevenLabs gebruiken. De website en serverfuncties zijn voorbereid voor Netlify. Per klantimplementatie leggen we vast welke aanvullende systemen worden ingezet."],
  ["cookies","Cookies en analytics","Analytische metingen starten pas na jouw keuze.","De website gebruikt lokale opslag voor noodzakelijke voorkeuren. Een analyticsprovider wordt alleen geladen wanneer deze technisch is geconfigureerd én jij analytische meting toestaat. We sturen geen naam, e-mailadres, telefoonnummer of vrije formulierinhoud mee in analytics-events."],
  ["doorgifte","Doorgifte en beveiliging","We beperken toegang en leggen externe verwerking vast.","Sommige leveranciers kunnen gegevens buiten de Europese Economische Ruimte verwerken. De waarborgen hangen af van accountregio en contracten. We gebruiken versleutelde verbindingen, secrets buiten de websitecode, servervalidatie, minimale rechten en logging zonder formulierinhoud."],
  ["bewaren","Bewaartermijnen","Niet langer dan nodig voor het doel.","Contact- en afspraakgegevens worden bewaard zolang dit nodig is voor opvolging, uitvoering en administratie, of zolang een wettelijke bewaarplicht geldt. Testdata en niet-relevante gegevens blijven niet onnodig in productiesystemen staan."],
  ["rechten","Jouw rechten","Je kunt vragen om inzicht, correctie of verwijdering.","Je kunt ook bezwaar maken of vragen om beperking of overdracht wanneer dat wettelijk van toepassing is. Mail naar info@auto-pilots.io. We kunnen om redelijke verificatie vragen. Je behoudt het recht een klacht in te dienen bij de bevoegde privacytoezichthouder."]
 ],
 en:[
  ["controller","Controller","Autopilots manages this website and the requests submitted through it.","For questions about privacy or personal data, email info@auto-pilots.io. The responsible party confirms the formal company identity and registered details before final legal approval."],
  ["data","Data we process","Only what is needed for contact, planning and delivery.","When you book or contact us, we may process your name, business contact details, company information, appointment data and request. For orders, the payment provider processes payment and transaction data; Autopilots does not automatically receive full card details."],
  ["purposes","Purposes and legal bases","To respond, schedule and perform agreed work.","We process data to take steps at your request before or during a contract, keep required records, protect the website and forms, and—where required—on the basis of consent. Consent can be withdrawn for future processing."],
  ["services","External services","Calendar, CRM, AI demo and payment each have a defined role.","Booking and CRM processing use LeadConnector/GoHighLevel. Confirmed payments use Stripe. A voice demo may use ElevenLabs after you actively start it. The site and server functions are prepared for Netlify. Additional systems are documented for each customer implementation."],
  ["cookies","Cookies and analytics","Analytics only starts after your choice.","Local storage is used for necessary preferences. Analytics loads only when configured and you consent. We do not send names, email addresses, phone numbers or free-form content in analytics events."],
  ["transfers","Transfers and security","We restrict access and document external processing.","Some suppliers may process data outside the EEA. Safeguards depend on account region and contracts. We use encrypted connections, secrets outside website code, server validation, least privilege and logs without form content."],
  ["retention","Retention","No longer than the purpose requires.","Contact and appointment data is retained for follow-up, delivery, administration or legal duties. Test data and irrelevant information should not remain in production systems unnecessarily."],
  ["rights","Your rights","You may request access, correction or deletion.","You may also object or request restriction or portability where applicable. Email info@auto-pilots.io. Reasonable identity verification may be required. You may complain to the competent data protection authority."]
 ],
 es:[
  ["responsable","Responsable","Autopilots gestiona este sitio y las solicitudes recibidas.","Para preguntas sobre privacidad o datos personales, escribe a info@auto-pilots.io. La identidad empresarial y los datos registrales se confirman antes de la aprobación jurídica final."],
  ["datos","Datos tratados","Solo lo necesario para contacto, planificación y ejecución.","Al reservar o contactar podemos tratar nombre, datos profesionales, información de empresa, cita y solicitud. En pedidos, el proveedor de pagos trata datos de pago y transacción; Autopilots no recibe automáticamente los datos completos de la tarjeta."],
  ["finalidades","Finalidades y bases","Para responder, reservar y ejecutar los acuerdos.","Tratamos datos para actuar a petición tuya antes o durante un contrato, cumplir obligaciones administrativas, proteger el sitio y, cuando corresponda, con consentimiento. Puedes retirar el consentimiento para el futuro."],
  ["servicios","Servicios externos","Agenda, CRM, demo de IA y pago tienen funciones delimitadas.","Las reservas y el CRM usan LeadConnector/GoHighLevel; los pagos confirmados, Stripe. La demo de voz puede usar ElevenLabs tras activarla. El sitio está preparado para Netlify. Los sistemas adicionales se documentan por implementación."],
  ["cookies","Cookies y analítica","La medición comienza solo después de tu elección.","Usamos almacenamiento local para preferencias necesarias. La analítica solo carga si está configurada y das permiso. No enviamos nombres, emails, teléfonos ni texto libre a eventos analíticos."],
  ["transferencias","Transferencias y seguridad","Limitamos accesos y documentamos el tratamiento externo.","Algunos proveedores pueden tratar datos fuera del EEE. Las garantías dependen de región y contratos. Usamos conexiones cifradas, secretos fuera del código, validación en servidor, permisos mínimos y registros sin contenido de formularios."],
  ["conservacion","Conservación","No más tiempo del necesario.","Los datos de contacto y citas se conservan para seguimiento, ejecución, administración u obligaciones legales. Los datos de prueba o irrelevantes no permanecen innecesariamente en producción."],
  ["derechos","Tus derechos","Puedes solicitar acceso, rectificación o supresión.","También puedes oponerte o pedir limitación o portabilidad cuando proceda. Escribe a info@auto-pilots.io. Podemos solicitar verificación razonable. Puedes reclamar ante la autoridad de protección de datos competente."]
 ],
 de:[
  ["verantwortlicher","Verantwortlicher","Autopilots betreibt diese Website und bearbeitet eingehende Anfragen.","Bei Fragen zu Datenschutz oder personenbezogenen Daten schreiben Sie an info@auto-pilots.io. Unternehmensidentität und Sitz werden vor der abschließenden rechtlichen Freigabe bestätigt."],
  ["daten","Verarbeitete Daten","Nur was für Kontakt, Planung und Durchführung nötig ist.","Bei Terminbuchung oder Kontakt können Name, geschäftliche Kontaktdaten, Unternehmens-, Termin- und Anfragedaten verarbeitet werden. Bei Bestellungen verarbeitet der Zahlungsanbieter Zahlungsdaten; Autopilots erhält nicht automatisch vollständige Kartendaten."],
  ["zwecke","Zwecke und Rechtsgrundlagen","Zur Antwort, Terminplanung und Vertragserfüllung.","Wir verarbeiten Daten für Schritte auf Ihre Anfrage vor oder während eines Vertrags, gesetzliche Verwaltung, Schutz der Website und—wenn nötig—mit Einwilligung. Eine Einwilligung kann für die Zukunft widerrufen werden."],
  ["dienste","Externe Dienste","Kalender, CRM, KI-Demo und Zahlung haben abgegrenzte Rollen.","Termin und CRM nutzen LeadConnector/GoHighLevel, bestätigte Zahlungen Stripe. Eine aktiv gestartete Voice-Demo kann ElevenLabs nutzen. Website und Serverfunktionen sind für Netlify vorbereitet. Weitere Systeme werden je Implementierung dokumentiert."],
  ["cookies","Cookies und Analyse","Analysen starten erst nach Ihrer Auswahl.","Lokaler Speicher dient notwendigen Präferenzen. Analytics lädt nur bei Konfiguration und Zustimmung. Namen, E-Mail, Telefonnummern oder Freitext senden wir nicht in Analyseereignissen."],
  ["uebermittlung","Übermittlung und Sicherheit","Wir beschränken Zugriffe und dokumentieren externe Verarbeitung.","Einige Anbieter können außerhalb des EWR verarbeiten. Garantien hängen von Region und Verträgen ab. Wir nutzen Verschlüsselung, Secrets außerhalb des Codes, Servervalidierung, minimale Rechte und Logs ohne Formularinhalte."],
  ["speicherung","Speicherdauer","Nicht länger als für den Zweck nötig.","Kontakt- und Termindaten werden für Nachverfolgung, Durchführung, Verwaltung oder gesetzliche Pflichten gespeichert. Test- und irrelevante Daten bleiben nicht unnötig in Produktionssystemen."],
  ["rechte","Ihre Rechte","Sie können Auskunft, Berichtigung oder Löschung verlangen.","Sie können außerdem widersprechen oder Einschränkung beziehungsweise Übertragbarkeit verlangen. Schreiben Sie an info@auto-pilots.io. Eine angemessene Identitätsprüfung ist möglich. Beschwerden können an die zuständige Datenschutzbehörde gerichtet werden."]
 ],
 it:[
  ["titolare","Titolare","Autopilots gestisce questo sito e le richieste inviate.","Per domande su privacy o dati personali scrivi a info@auto-pilots.io. Identità aziendale e sede vengono confermate prima dell'approvazione legale finale."],
  ["dati","Dati trattati","Solo quanto serve per contatto, pianificazione ed esecuzione.","Quando prenoti o ci contatti possiamo trattare nome, contatti professionali, dati aziendali, appuntamento e richiesta. Per gli ordini, il provider di pagamento tratta i dati della transazione; Autopilots non riceve automaticamente i dati completi della carta."],
  ["finalita","Finalità e basi giuridiche","Per rispondere, prenotare ed eseguire gli accordi.","Trattiamo dati per agire su richiesta prima o durante un contratto, adempiere obblighi amministrativi, proteggere il sito e, quando richiesto, con consenso. Il consenso può essere revocato per il futuro."],
  ["servizi","Servizi esterni","Calendario, CRM, demo AI e pagamento hanno ruoli definiti.","Prenotazioni e CRM usano LeadConnector/GoHighLevel; i pagamenti confermati Stripe. La demo vocale può usare ElevenLabs dopo l'avvio attivo. Il sito è predisposto per Netlify. I sistemi aggiuntivi sono documentati per ogni implementazione."],
  ["cookie","Cookie e analytics","La misurazione inizia solo dopo la tua scelta.","Usiamo memoria locale per preferenze necessarie. Analytics viene caricato solo se configurato e autorizzato. Non inviamo nomi, email, telefoni o testo libero negli eventi."],
  ["trasferimenti","Trasferimenti e sicurezza","Limitiamo gli accessi e documentiamo i trattamenti esterni.","Alcuni fornitori possono trattare dati fuori dal SEE. Le garanzie dipendono da regione e contratti. Usiamo connessioni cifrate, segreti fuori dal codice, validazione server, permessi minimi e log senza contenuto dei moduli."],
  ["conservazione","Conservazione","Non oltre quanto necessario.","I dati di contatto e appuntamento restano per follow-up, esecuzione, amministrazione o obblighi legali. Dati di test o irrilevanti non restano inutilmente nei sistemi di produzione."],
  ["diritti","I tuoi diritti","Puoi chiedere accesso, rettifica o cancellazione.","Puoi anche opporti o chiedere limitazione o portabilità quando applicabile. Scrivi a info@auto-pilots.io. Possiamo richiedere una verifica ragionevole. Puoi rivolgerti all'autorità privacy competente."]
 ],
 fr:[
  ["responsable","Responsable","Autopilots gère ce site et les demandes qui y sont envoyées.","Pour toute question sur la confidentialité ou les données personnelles, écrivez à info@auto-pilots.io. L'identité juridique et le siège sont confirmés avant validation juridique finale."],
  ["donnees","Données traitées","Uniquement ce qui est nécessaire au contact, à la planification et à l'exécution.","Lors d'une prise de rendez-vous ou d'un contact, nous pouvons traiter nom, coordonnées professionnelles, informations d'entreprise, rendez-vous et demande. Pour une commande, le prestataire de paiement traite les données de transaction ; Autopilots ne reçoit pas automatiquement les données complètes de carte."],
  ["finalites","Finalités et bases légales","Pour répondre, planifier et exécuter les accords.","Nous traitons les données pour agir à votre demande avant ou pendant un contrat, respecter les obligations administratives, protéger le site et, si nécessaire, avec votre consentement. Celui-ci peut être retiré pour l'avenir."],
  ["services","Services externes","Agenda, CRM, démo IA et paiement ont chacun un rôle défini.","Les rendez-vous et le CRM utilisent LeadConnector/GoHighLevel, les paiements confirmés Stripe. Une démo vocale peut utiliser ElevenLabs après activation. Le site est préparé pour Netlify. Les systèmes complémentaires sont documentés par implémentation."],
  ["cookies","Cookies et statistiques","La mesure ne commence qu'après votre choix.","Le stockage local sert aux préférences nécessaires. Les statistiques ne chargent que si elles sont configurées et autorisées. Aucun nom, e-mail, téléphone ou texte libre n'est envoyé dans les événements."],
  ["transferts","Transferts et sécurité","Nous limitons les accès et encadrons les traitements externes.","Certains fournisseurs peuvent traiter des données hors EEE. Les garanties dépendent de la région et des contrats. Nous utilisons chiffrement, secrets hors du code, validation serveur, droits minimaux et journaux sans contenu de formulaires."],
  ["conservation","Conservation","Pas plus longtemps que nécessaire.","Les données de contact et rendez-vous sont conservées pour suivi, exécution, administration ou obligations légales. Les données de test ou sans utilité ne restent pas inutilement en production."],
  ["droits","Vos droits","Vous pouvez demander accès, rectification ou suppression.","Vous pouvez aussi vous opposer ou demander limitation ou portabilité lorsque la loi le prévoit. Écrivez à info@auto-pilots.io. Une vérification raisonnable peut être demandée. Vous pouvez saisir l'autorité de protection des données compétente."]
 ]
} as const;

export const privacyPageCopy = {
 nl:{title:"Privacy en gegevensverwerking | Autopilots",description:"Lees welke persoonsgegevens Autopilots verwerkt, waarom en welke rechten je hebt.",home:"Home",name:"Privacy",updated:"Laatst bijgewerkt: 15 juli 2026",hero:"Privacy en",accent:"gegevensverwerking.",lead:"Hier leggen we in gewone taal uit welke gegevens via deze website kunnen worden verwerkt en welke externe diensten daarbij een rol spelen.",onPage:"Op deze pagina"},
 en:{title:"Privacy and data processing | Autopilots",description:"Read which personal data Autopilots processes, why, and which rights you have.",home:"Home",name:"Privacy",updated:"Last updated: 15 July 2026",hero:"Privacy and",accent:"data processing.",lead:"This page explains in plain language which data this website may process and which external services are involved.",onPage:"On this page"},
 es:{title:"Privacidad y tratamiento de datos | Autopilots",description:"Consulta qué datos personales trata Autopilots, por qué y cuáles son tus derechos.",home:"Inicio",name:"Privacidad",updated:"Última actualización: 15 de julio de 2026",hero:"Privacidad y",accent:"tratamiento de datos.",lead:"Explicamos con claridad qué datos puede tratar este sitio y qué servicios externos intervienen.",onPage:"En esta página"},
 de:{title:"Datenschutz und Datenverarbeitung | Autopilots",description:"Lesen Sie, welche personenbezogenen Daten Autopilots verarbeitet, warum und welche Rechte Sie haben.",home:"Startseite",name:"Datenschutz",updated:"Zuletzt aktualisiert: 15. Juli 2026",hero:"Datenschutz und",accent:"Datenverarbeitung.",lead:"Hier erklären wir verständlich, welche Daten diese Website verarbeitet und welche externen Dienste beteiligt sind.",onPage:"Auf dieser Seite"},
 it:{title:"Privacy e trattamento dati | Autopilots",description:"Scopri quali dati personali tratta Autopilots, perché e quali diritti hai.",home:"Home",name:"Privacy",updated:"Ultimo aggiornamento: 15 luglio 2026",hero:"Privacy e",accent:"trattamento dei dati.",lead:"Spieghiamo in modo chiaro quali dati può trattare il sito e quali servizi esterni intervengono.",onPage:"In questa pagina"},
 fr:{title:"Confidentialité et traitement des données | Autopilots",description:"Découvrez quelles données personnelles Autopilots traite, pourquoi et quels sont vos droits.",home:"Accueil",name:"Confidentialité",updated:"Dernière mise à jour : 15 juillet 2026",hero:"Confidentialité et",accent:"traitement des données.",lead:"Nous expliquons simplement quelles données ce site peut traiter et quels services externes interviennent.",onPage:"Sur cette page"}
} as const satisfies Record<SupportedLocale, Record<string,string>>;

export function getPrivacySections(locale: SupportedLocale){
 return privacySections[locale].map((row,index)=>[privacySections.nl[index][0],...row.slice(1)] as [string,string,string,string]);
}

const termCards = {
 nl:[["Productscope","Controleer welke kanalen, afdeling, intake, acties en menselijke fallback bij het gekozen product horen."],["Prijs en usage","Maandbedrag, implementatiekosten, btw en eventuele bericht- of belkosten moeten zichtbaar zijn vóór bevestiging."],["Technische toegang","Livegang hangt af van beschikbare API’s, rechten, gegevenskwaliteit, telefoon- of kanaaltoegang en tijdige feedback."],["Planning","De gebruikelijke livegang is twee tot vier weken na de implementatiecall. Dit is geen absolute garantie bij externe afhankelijkheden."],["Privacy","Voor livegang leggen we de gegevensstromen, rollen en verwerkersovereenkomst vast."],["Vragen","Is iets niet duidelijk of ontbreekt een vaste configuratie? Plan dan eerst een scopecheck."]],
 en:[["Product scope","Check which channels, department, intake, actions and human fallback belong to the selected product."],["Price and usage","Monthly fee, implementation, VAT and message or call costs must be visible before confirmation."],["Technical access","Launch depends on APIs, permissions, data quality, channel access and timely feedback."],["Planning","Launch is usually two to four weeks after the implementation call; external dependencies can affect this."],["Privacy","Before launch, we define data flows, roles and the data processing agreement."],["Questions","If anything is unclear or lacks a fixed configuration, schedule a scope check first."]],
 es:[["Alcance del producto","Comprueba canales, departamento, toma de datos, acciones y transferencia humana del producto."],["Precio y uso","Cuota mensual, implementación, impuestos y costes de mensajes o llamadas deben verse antes de confirmar."],["Acceso técnico","El lanzamiento depende de APIs, permisos, calidad de datos, acceso a canales y comentarios a tiempo."],["Planificación","El lanzamiento suele realizarse entre dos y cuatro semanas tras la llamada; las dependencias externas pueden afectarlo."],["Privacidad","Antes del lanzamiento definimos flujos de datos, funciones y contrato de tratamiento."],["Preguntas","Si algo no está claro o no tiene configuración fija, reserva primero una comprobación."]],
 de:[["Produktumfang","Prüfen Sie Kanäle, Abteilung, Aufnahme, Aktionen und menschliche Übergabe des Produkts."],["Preis und Nutzung","Monatsbetrag, Implementierung, Steuern sowie Nachrichten- oder Gesprächskosten müssen vor Bestätigung sichtbar sein."],["Technischer Zugang","Der Livegang hängt von APIs, Rechten, Datenqualität, Kanalzugang und rechtzeitigem Feedback ab."],["Planung","Üblich sind zwei bis vier Wochen nach dem Implementierungstermin; externe Abhängigkeiten können dies beeinflussen."],["Datenschutz","Vor dem Livegang definieren wir Datenflüsse, Rollen und Auftragsverarbeitung."],["Fragen","Ist etwas unklar oder nicht fest konfiguriert, planen Sie zuerst einen Scope-Check."]],
 it:[["Ambito prodotto","Verifica canali, reparto, raccolta dati, azioni e passaggio umano inclusi nel prodotto."],["Prezzo e utilizzo","Canone, implementazione, imposte e costi di messaggi o chiamate devono essere visibili prima della conferma."],["Accesso tecnico","Il lancio dipende da API, permessi, qualità dati, accesso ai canali e feedback puntuale."],["Pianificazione","Il lancio avviene normalmente entro due-quattro settimane dalla call; le dipendenze esterne possono influire."],["Privacy","Prima del lancio definiamo flussi, ruoli e accordo sul trattamento dati."],["Domande","Se qualcosa non è chiaro o non ha configurazione fissa, pianifica prima un controllo."]],
 fr:[["Périmètre produit","Vérifiez les canaux, le service, la collecte, les actions et le transfert humain inclus."],["Prix et usage","Abonnement, implémentation, taxes et coûts de messages ou appels doivent être visibles avant confirmation."],["Accès technique","Le lancement dépend des API, droits, qualité des données, accès aux canaux et retours rapides."],["Planification","Le lancement intervient généralement sous deux à quatre semaines après l'appel ; les dépendances externes peuvent influer."],["Confidentialité","Avant le lancement, nous définissons flux de données, rôles et accord de traitement."],["Questions","Si un point est flou ou sans configuration fixe, planifiez d'abord une vérification."]]
} as const;

export const termsPageCopy = {
 nl:{title:"Voorwaarden bij directe bestelling | Autopilots",description:"Controleer de onderdelen voor een directe bestelling.",home:"Home",name:"Voorwaarden bij bestelling",kicker:"Voor je bevestigt",hero:"Controleer scope, usage en",accent:"implementatie.",lead:"Deze pagina is een praktische controlelijst. De definitieve commerciële en juridische voorwaarden staan in het specifieke voorstel, de betaalomgeving en de documenten die vóór livegang worden gedeeld.",order:"Terug naar bestellen",privacy:"Bekijk privacy",check:"Plan een scopecheck"},
 en:{title:"Direct order terms | Autopilots",description:"Review the items that matter before placing a direct order.",home:"Home",name:"Order terms",kicker:"Before confirming",hero:"Check scope, usage and",accent:"implementation.",lead:"This page is a practical checklist. Final commercial and legal terms appear in the specific proposal, payment environment and documents shared before launch.",order:"Back to order",privacy:"View privacy",check:"Book a scope check"},
 es:{title:"Condiciones de pedido directo | Autopilots",description:"Revisa los puntos importantes antes de un pedido directo.",home:"Inicio",name:"Condiciones del pedido",kicker:"Antes de confirmar",hero:"Comprueba alcance, uso e",accent:"implementación.",lead:"Esta página es una lista práctica. Las condiciones comerciales y jurídicas definitivas aparecen en la propuesta, el entorno de pago y los documentos previos al lanzamiento.",order:"Volver al pedido",privacy:"Ver privacidad",check:"Reservar comprobación"},
 de:{title:"Bedingungen für Direktbestellung | Autopilots",description:"Prüfen Sie die wichtigen Punkte vor einer Direktbestellung.",home:"Startseite",name:"Bestellbedingungen",kicker:"Vor der Bestätigung",hero:"Prüfen Sie Umfang, Nutzung und",accent:"Implementierung.",lead:"Diese Seite ist eine praktische Checkliste. Endgültige kaufmännische und rechtliche Bedingungen stehen im Angebot, Zahlungsbereich und den vor Livegang geteilten Dokumenten.",order:"Zurück zur Bestellung",privacy:"Datenschutz ansehen",check:"Scope-Check buchen"},
 it:{title:"Condizioni per ordine diretto | Autopilots",description:"Controlla gli elementi importanti prima di un ordine diretto.",home:"Home",name:"Condizioni dell'ordine",kicker:"Prima di confermare",hero:"Controlla ambito, utilizzo e",accent:"implementazione.",lead:"Questa pagina è una lista pratica. Le condizioni commerciali e legali definitive sono nella proposta, nell'ambiente di pagamento e nei documenti condivisi prima del lancio.",order:"Torna all'ordine",privacy:"Vedi privacy",check:"Prenota controllo"},
 fr:{title:"Conditions de commande directe | Autopilots",description:"Vérifiez les éléments importants avant une commande directe.",home:"Accueil",name:"Conditions de commande",kicker:"Avant de confirmer",hero:"Vérifiez le périmètre, l'usage et",accent:"l'implémentation.",lead:"Cette page est une liste pratique. Les conditions commerciales et juridiques définitives figurent dans la proposition, l'espace de paiement et les documents partagés avant lancement.",order:"Retour à la commande",privacy:"Voir la confidentialité",check:"Planifier une vérification"}
} as const satisfies Record<SupportedLocale, Record<string,string>>;

export function getTermCards(locale: SupportedLocale){ return termCards[locale]; }
