import type { SupportedLocale } from "./languages";
import { translatedTermsSections } from "./termsTranslations";

export type TermsSection = { title: string; paragraphs: string[] };
export type TermsDocument = {
  title: string; description: string; home: string; name: string; kicker: string;
  hero: string; accent: string; lead: string; updated: string; version: string;
  download: string; privacy: string; contact: string; contents: string;
  languageNotice: string; sections: TermsSection[];
};

const nl: TermsDocument = {
  title: "Algemene servicevoorwaarden | Autopilots",
  description: "De algemene B2B-servicevoorwaarden van Autopilots AI Agency LLC voor AI-medewerkers, software, implementatie en support.",
  home: "Home", name: "Algemene servicevoorwaarden", kicker: "B2B-servicevoorwaarden",
  hero: "Duidelijke afspraken voor", accent: "betrouwbare AI-diensten.",
  lead: "Deze voorwaarden gelden voor zakelijke klanten van Autopilots AI Agency LLC en vormen samen met de bestelling, het voorstel of de Statement of Work de overeenkomst.",
  updated: "Laatst bijgewerkt: 1 september 2026", version: "Versie 1.0",
  download: "Download als PDF", privacy: "Bekijk privacy", contact: "Neem contact op", contents: "Inhoud",
  languageNotice: "De Nederlandse versie is juridisch leidend. Vertalingen zijn uitsluitend voor het leesgemak.",
  sections: [
    {title:"1. Definities en B2B-toepasselijkheid",paragraphs:["Autopilots betekent Autopilots AI Agency LLC, gevestigd te 131 Continental Dr, Suite 305, Newark, Delaware 19713, Verenigde Staten. Opdrachtgever is uitsluitend een natuurlijke persoon of rechtspersoon die handelt in de uitoefening van een beroep of bedrijf. Deze voorwaarden zijn niet bedoeld voor consumenten.","Diensten omvatten AI-medewerkers, voice agents, software, configuratie, implementatie, integraties, onderhoud en support. Een Order Form, Stripe-bestelling, voorstel of Statement of Work (‘Order’) legt onder meer product, scope, prijs, looptijd en eventuele bijzondere afspraken vast."]},
    {title:"2. Overeenkomst, acceptatie en rangorde",paragraphs:["De overeenkomst ontstaat door ondertekening, elektronische acceptatie in Stripe of een andere betaalomgeving, of doordat Autopilots op verzoek met de uitvoering begint. Opdrachtgever bevestigt vóór betaling dat deze voorwaarden via een directe link beschikbaar zijn gesteld en digitaal kunnen worden opgeslagen.","Bij tegenstrijdigheid geldt: (1) de verwerkersovereenkomst voor privacyonderwerpen, (2) de Order, (3) een uitdrukkelijk overeengekomen SLA, (4) deze voorwaarden en (5) overige documentatie. Inkoopvoorwaarden van Opdrachtgever worden afgewezen. Mondelinge afspraken wijzigen de overeenkomst alleen na schriftelijke bevestiging door beide partijen."]},
    {title:"3. Scope, onboarding en wijzigingen",paragraphs:["Autopilots levert uitsluitend de functionaliteit, kanalen, integraties en ondersteuning die in de Order zijn opgenomen. Meerwerk, gewijzigde wensen, extra databronnen, uitzonderingen en nieuwe integraties kunnen gevolgen hebben voor prijs en planning en worden pas uitgevoerd na akkoord.","Planning begint zodra betaling, benodigde informatie, toegangen, testdata, contactpersonen en - waar nodig - een verwerkersovereenkomst beschikbaar zijn. Vertraging door Opdrachtgever of derden verschuift termijnen. Autopilots mag aantoonbaar extra werk en stand-bykosten in rekening brengen."]},
    {title:"4. AI-diensten en menselijke controle",paragraphs:["AI-output is probabilistisch en kan onjuist, onvolledig of onverwacht zijn. Autopilots garandeert geen foutloze output, ononderbroken beschikbaarheid, omzetresultaat, kostenbesparing of geschiktheid voor een niet uitdrukkelijk overeengekomen doel.","Opdrachtgever blijft verantwoordelijk voor beslissingen, communicatie en bedrijfsprocessen die op AI-output zijn gebaseerd en richt passende menselijke controle, escalatie en fallback in. De Diensten mogen niet worden gebruikt voor noodoproepen, zelfstandig juridisch of medisch advies, verboden AI-toepassingen of andere hoog-risicotoepassingen zonder voorafgaande schriftelijke overeenkomst."]},
    {title:"5. Verplichtingen van Opdrachtgever",paragraphs:["Opdrachtgever verstrekt tijdig juiste informatie, bevoegdheden en toegangen, beveiligt eigen accounts en controleert scripts, prompts, databronnen en resultaten. Opdrachtgever staat ervoor in dat aangeleverde content en instructies rechtmatig zijn en geen rechten van derden schenden.","Opdrachtgever is verantwoordelijk voor toepasselijke privacy-, marketing-, telecom-, consumenten- en sectorspecifieke regels, waaronder geldige opt-ins, opt-outs, bel-me-nietregistraties, afzenderregistraties, AI-disclosure en meldingen over gespreksopnames. Misleiding, discriminatie, fraude, spoofing, spam en het omzeilen van beveiliging of providerbeleid zijn verboden."]},
    {title:"6. Derde diensten",paragraphs:["De Diensten kunnen afhankelijk zijn van modelproviders, telecomproviders, hosting, CRM-, agenda-, berichten- en betaalproviders. Hun voorwaarden, limieten, prijswijzigingen, storingen en beleidswijzigingen kunnen de Diensten beïnvloeden.","Autopilots is niet aansprakelijk voor een tekortkoming die uitsluitend door een derde dienst wordt veroorzaakt en zal zich redelijkerwijs inspannen om de gevolgen te beperken. Autopilots mag een derde dienst vervangen wanneer dit nodig is voor veiligheid, continuïteit, compliance of doelmatige uitvoering, mits de kern van de overeengekomen Dienst niet wezenlijk wordt verminderd."]},
    {title:"7. Prijzen, gebruik en betaling",paragraphs:["Alle bedragen zijn exclusief btw en heffingen, tenzij anders vermeld. Setup-, abonnements- en vooruitbetaalde bedragen zijn niet restitueerbaar, behalve voor zover dwingend recht anders bepaalt. Variabele gebruiks- en derde-partijkosten worden volgens de Order of de geldende tarieven doorbelast.","Facturen zijn betaalbaar binnen de vermelde termijn. Bij te late betaling mag Autopilots wettelijke handelsrente, redelijke incassokosten en reactivatiekosten rekenen en na een schriftelijke waarschuwing Diensten, integraties, verkeer of toegang opschorten. Abonnementskosten blijven tijdens een aan Opdrachtgever toerekenbare opschorting verschuldigd. Opdrachtgever mag facturen niet verrekenen en moet een betwisting binnen zeven dagen gemotiveerd melden; het onbetwiste deel blijft betaalbaar."]},
    {title:"8. Duur en opzegging via Stripe",paragraphs:["De looptijd en verlenging staan in de Order. Een maandabonnement kan via de beschikbare Stripe-klantomgeving worden opgezegd met een opzegtermijn van één maand. Een overeenkomst met vaste looptijd kan via Stripe of schriftelijk worden opgezegd tegen het einde van de lopende termijn; opzegging moet uiterlijk dertig dagen vóór verlenging zijn ontvangen.","Een opzegging beëindigt toekomstige verlenging en geeft geen recht op terugbetaling van reeds betaalde of verschuldigde bedragen. Opdrachtgever blijft verantwoordelijk voor export en veiligstelling van gegevens vóór het einde van de beschikbare exportperiode."]},
    {title:"9. Intellectueel eigendom en klantdata",paragraphs:["Alle rechten op software, prompts, playbooks, templates, configuraties, integratiemethoden, documentatie en bestaande of generiek ontwikkelde onderdelen van Autopilots blijven bij Autopilots. Opdrachtgever krijgt voor de contractduur een beperkt, niet-exclusief, niet-overdraagbaar gebruiksrecht voor de eigen organisatie.","Klantdata en door Opdrachtgever aangeleverde content blijven van Opdrachtgever. Opdrachtgever verleent Autopilots de rechten die nodig zijn om de Diensten te leveren. Autopilots gebruikt Klantdata niet om algemeen beschikbare modellen te trainen, tenzij dit afzonderlijk en uitdrukkelijk is overeengekomen. Geanonimiseerde, niet-herleidbare statistieken mogen worden gebruikt voor beveiliging, verbetering en rapportage."]},
    {title:"10. Privacy, beveiliging en opnames",paragraphs:["Wanneer Autopilots als verwerker optreedt, sluiten partijen vóór verwerking van productiegegevens een verwerkersovereenkomst. Beveiliging, subverwerkers, doorgifte, incidenten, bewaartermijnen en verwijdering worden daarin nader geregeld. Autopilots neemt passende maatregelen, maar garandeert geen absolute beveiliging.","Een vergadering of gesprek wordt alleen opgenomen nadat dit aan deelnemers kenbaar is gemaakt en voor zover een geldige rechtsgrond bestaat. Opnames worden niet automatisch als doorslaggevend bewijs beschouwd. Opdrachtgever verleent redelijke medewerking aan privacy- en beveiligingsonderzoeken die samenhangen met zijn gebruik."]},
    {title:"11. Geheimhouding en referentiegebruik",paragraphs:["Partijen houden vertrouwelijke informatie geheim en gebruiken deze alleen voor de overeenkomst. Deze verplichting geldt vijf jaar na beëindiging en voor bedrijfsgeheimen zolang zij als bedrijfsgeheim kwalificeren.","Autopilots mag naam en logo van Opdrachtgever als zakelijke referentie gebruiken, tenzij Opdrachtgever dit schriftelijk uitsluit. Casestudies, testimonials en niet-openbare resultaten worden alleen na voorafgaande goedkeuring gepubliceerd. Een intrekking werkt voor toekomstig materiaal; voor bestaand materiaal geldt een redelijke afbouwtermijn."]},
    {title:"12. Garanties, aansprakelijkheid en claimtermijn",paragraphs:["Autopilots levert de Diensten als inspanningsverbintenis met redelijke vakbekwaamheid en zorg. Voor zover wettelijk toegestaan is Autopilots alleen aansprakelijk voor aantoonbare directe schade die rechtstreeks voortvloeit uit een toerekenbare tekortkoming. Aansprakelijkheid voor indirecte schade, winst- of omzetverlies, gemiste besparingen, reputatieschade, bedrijfsstagnatie en verlies of beschadiging van data is uitgesloten.","De totale aansprakelijkheid van Autopilots per kalenderjaar is beperkt tot het bedrag dat Opdrachtgever in de zes maanden vóór de schadeveroorzakende gebeurtenis voor de betrokken Dienst heeft betaald, met een absoluut maximum van EUR 25.000. Deze beperkingen gelden niet voor zover beperking wettelijk verboden is of bij opzet of bewuste roekeloosheid van de leiding van Autopilots. Opdrachtgever meldt een mogelijke claim binnen dertig dagen na ontdekking en stelt Autopilots in staat de schade te beperken. Iedere claim vervalt twaalf maanden nadat Opdrachtgever deze ontdekte of redelijkerwijs had moeten ontdekken, voor zover wettelijk toegestaan."]},
    {title:"13. Vrijwaring",paragraphs:["Opdrachtgever vrijwaart Autopilots tegen aanspraken, boetes en redelijke kosten van derden die voortvloeien uit onrechtmatig gebruik, klantcontent, klantinstructies, ontbrekende toestemmingen, telecom- of marketingovertredingen, niet-goedgekeurde use-cases of koppelingen en wijzigingen buiten Autopilots om.","De vrijwaring geldt niet voor zover een aanspraak rechtstreeks is veroorzaakt door opzet of bewuste roekeloosheid van de leiding van Autopilots. Autopilots informeert Opdrachtgever tijdig en geeft hem redelijke invloed op het verweer, zonder dat Opdrachtgever zonder toestemming een verplichting voor Autopilots mag erkennen."]},
    {title:"14. Opschorting, beëindiging en overmacht",paragraphs:["Autopilots mag de Diensten onmiddellijk beperken of opschorten bij veiligheidsrisico, vermoedelijk onrechtmatig gebruik, provider- of carrierrisico, dreigende schade, sanctierisico of betalingsachterstand. Bij een herstelbare wezenlijke tekortkoming krijgt de nalatige partij in beginsel dertig dagen om te herstellen. Betalingsachterstand van veertien dagen, faillissement, misbruik of een niet-herstelbaar risico kan onmiddellijke beëindiging rechtvaardigen.","Geen partij is aansprakelijk voor niet-nakoming door een gebeurtenis buiten haar redelijke controle, waaronder uitval van internet, stroom, carriers, cloud- of modelproviders, cyberaanvallen, overheidsmaatregelen en natuurrampen. Duurt overmacht langer dan zestig dagen, dan mag iedere partij het getroffen deel beëindigen zonder schadevergoeding; reeds geleverde prestaties en gemaakte kosten blijven verschuldigd."]},
    {title:"15. Wijzigingen en slotbepalingen",paragraphs:["Autopilots mag deze voorwaarden wijzigen wegens wetgeving, veiligheid, providervereisten of verbetering van de dienstverlening. Niet-materiële wijzigingen kunnen direct ingaan. Materiële wijzigingen worden minimaal dertig dagen vooraf gemeld en gelden voor een lopende vaste termijn alleen wanneer wettelijk nodig, uitdrukkelijk geaccepteerd of vanaf de volgende verlenging. Bij een wezenlijk nadelige wijziging mag Opdrachtgever vóór de ingangsdatum opzeggen.","Nederlands recht is van toepassing. Geschillen worden exclusief voorgelegd aan de bevoegde rechter van de rechtbank Amsterdam, voor zover een forumkeuze wettelijk is toegestaan. Elektronische berichten aan de adressen in de Order gelden als schriftelijke kennisgeving. Nietigheid van één bepaling tast de rest niet aan. De Nederlandse tekst prevaleert boven vertalingen."]}
  ]
};

const localeMeta: Record<Exclude<SupportedLocale,"nl">, Omit<TermsDocument,"sections">> = {
  en:{title:"General service terms | Autopilots",description:"B2B service terms for Autopilots AI employees, software and implementation.",home:"Home",name:"General service terms",kicker:"B2B service terms",hero:"Clear agreements for",accent:"reliable AI services.",lead:"These terms apply to business customers of Autopilots AI Agency LLC and form the agreement together with the Order, proposal or Statement of Work.",updated:"Last updated: 1 September 2026",version:"Version 1.0",download:"Download Dutch PDF",privacy:"View privacy",contact:"Contact us",contents:"Contents",languageNotice:"The Dutch version is legally controlling. This translation is provided for convenience only."},
  es:{title:"Condiciones generales de servicio | Autopilots",description:"Condiciones B2B para empleados de IA, software e implementación de Autopilots.",home:"Inicio",name:"Condiciones generales",kicker:"Condiciones B2B",hero:"Acuerdos claros para",accent:"servicios de IA fiables.",lead:"Estas condiciones se aplican a clientes empresariales de Autopilots AI Agency LLC y forman el contrato junto con el pedido, propuesta o Statement of Work.",updated:"Última actualización: 1 de septiembre de 2026",version:"Versión 1.0",download:"Descargar PDF neerlandés",privacy:"Ver privacidad",contact:"Contacto",contents:"Contenido",languageNotice:"La versión neerlandesa es jurídicamente vinculante. Esta traducción se ofrece solo para facilitar la lectura."},
  de:{title:"Allgemeine Servicebedingungen | Autopilots",description:"B2B-Servicebedingungen für KI-Mitarbeiter, Software und Implementierung von Autopilots.",home:"Startseite",name:"Allgemeine Servicebedingungen",kicker:"B2B-Servicebedingungen",hero:"Klare Vereinbarungen für",accent:"zuverlässige KI-Dienste.",lead:"Diese Bedingungen gelten für Geschäftskunden von Autopilots AI Agency LLC und bilden zusammen mit Bestellung, Angebot oder Statement of Work den Vertrag.",updated:"Zuletzt aktualisiert: 1. September 2026",version:"Version 1.0",download:"Niederländisches PDF herunterladen",privacy:"Datenschutz",contact:"Kontakt",contents:"Inhalt",languageNotice:"Die niederländische Fassung ist rechtlich maßgeblich. Diese Übersetzung dient nur der Lesbarkeit."},
  it:{title:"Condizioni generali di servizio | Autopilots",description:"Condizioni B2B per collaboratori AI, software e implementazione Autopilots.",home:"Home",name:"Condizioni generali",kicker:"Condizioni B2B",hero:"Accordi chiari per",accent:"servizi AI affidabili.",lead:"Queste condizioni si applicano ai clienti aziendali di Autopilots AI Agency LLC e formano il contratto insieme all'ordine, proposta o Statement of Work.",updated:"Ultimo aggiornamento: 1 settembre 2026",version:"Versione 1.0",download:"Scarica PDF olandese",privacy:"Privacy",contact:"Contatti",contents:"Contenuto",languageNotice:"La versione neerlandese è giuridicamente prevalente. Questa traduzione è fornita solo per comodità."},
  fr:{title:"Conditions générales de service | Autopilots",description:"Conditions B2B pour collaborateurs IA, logiciel et implémentation Autopilots.",home:"Accueil",name:"Conditions générales",kicker:"Conditions B2B",hero:"Des accords clairs pour",accent:"des services IA fiables.",lead:"Ces conditions s'appliquent aux clients professionnels d'Autopilots AI Agency LLC et forment le contrat avec la commande, l'offre ou le Statement of Work.",updated:"Dernière mise à jour : 1 septembre 2026",version:"Version 1.0",download:"Télécharger le PDF néerlandais",privacy:"Confidentialité",contact:"Contact",contents:"Sommaire",languageNotice:"La version néerlandaise fait juridiquement foi. Cette traduction est fournie uniquement pour faciliter la lecture."}
};

// The Dutch clauses are controlling. Localized routes retain the complete clause text and
// localized structure; a qualified legal translator must approve them before they become controlling.
export const termsDocuments: Record<SupportedLocale, TermsDocument> = {
  nl,
  ...Object.fromEntries(Object.entries(localeMeta).map(([locale,meta])=>[locale,{...meta,sections:translatedTermsSections[locale as keyof typeof translatedTermsSections].map(section=>({title:section.title,paragraphs:[...section.paragraphs]}))}]))
} as Record<SupportedLocale, TermsDocument>;
