import type { SupportedLocale } from "./languages";

export type UiCopy = {
  system: { skipToContent: string; footerTagline: string; consentTitle: string; consentText: string; consentReject: string; consentAccept: string };
  navigation: { products: string; niches: string; process: string; knowledge: string; crew: string; appointment: string; order: string; menu: string; language: string };
  header: { productsLabel: string; productsTitle: string; productsText: string; productsCta: string; nichesLabel: string; nichesTitle: string; nichesText: string; nichesCta: string };
  footer: { title: string; text: string; analysis: string; allNiches: string; company: string; privacy: string; terms: string; future: string };
  products: Record<string, string>;
  home: { title: string; description: string; eyebrow: string; heading: string; accent: string; lead: string };
};

export const uiCopy: Record<SupportedLocale, UiCopy> = {
  nl: {
    system: { skipToContent: "Ga naar hoofdinhoud", footerTagline: "AI-medewerkers voor klantcontact en operatie.", consentTitle: "Jij bepaalt welke metingen actief zijn.", consentText: "Noodzakelijke functies staan altijd aan. Analytische metingen starten alleen na jouw keuze en bevatten geen formulierinhoud.", consentReject: "Alleen noodzakelijk", consentAccept: "Analytiek toestaan" },
    navigation: { products: "Producten", niches: "Voor wie", process: "Proces", knowledge: "Kennisbank", crew: "Crew", appointment: "Plan afspraak", order: "Bestel direct", menu: "Menu", language: "Taal kiezen" },
    header: { productsLabel: "Autopilots producten", productsTitle: "Onze AI-producten voor klantcontact en groei.", productsText: "Een vaste productbasis, ingericht op de processen en systemen van je branche.", productsCta: "Vergelijk onze producten", nichesLabel: "Voor wie", nichesTitle: "Een eigen klantreis voor iedere branche.", nichesText: "Vragen, intake, planning, systemen en menselijke fallback sluiten aan op de praktijk.", nichesCta: "Bekijk alle branches" },
    footer: { title: "AI-medewerkers die klantcontact omzetten naar actie.", text: "Onze vaste producten, ingericht op de processen, systemen en uitzonderingen van je branche.", analysis: "Plan een korte analyse", allNiches: "Alle branches", company: "Autopilots", privacy: "Privacy", terms: "Voorwaarden", future: "Voor de bedrijven van de toekomst." },
    products: { "ai-inboxmedewerker": "AI Inboxmedewerker", "ai-leadopvolger": "AI Leadopvolger", "ai-telefoniste": "AI Telefoniste", "autopilots-crm": "Autopilots CRM", "leadsmachine-ai": "Leadsmachine AI" },
    home: { title: "Autopilots | AI-medewerkers voor klantcontact en operatie", description: "Autopilots bouwt AI-medewerkers die klantcontact afhandelen, afspraken plannen en CRM-processen slimmer maken.", eyebrow: "Autopilots", heading: "AI-medewerkers die klantcontact omzetten naar", accent: "een concrete actie.", lead: "Onze AI-producten voor inbox, leadopvolging, telefonie, CRM en acquisitie — ingericht op jullie processen en systemen." }
  },
  en: {
    system: { skipToContent: "Skip to main content", footerTagline: "AI employees for customer contact and operations.", consentTitle: "You decide which measurements are active.", consentText: "Essential functions are always enabled. Analytics only start after your choice and never include form content.", consentReject: "Essential only", consentAccept: "Allow analytics" },
    navigation: { products: "Products", niches: "Industries", process: "Process", knowledge: "Knowledge", crew: "Team", appointment: "Book a call", order: "Order", menu: "Menu", language: "Choose language" },
    header: { productsLabel: "Autopilots products", productsTitle: "Our AI products for customer contact and growth.", productsText: "A proven product foundation configured for your industry, processes and systems.", productsCta: "Compare all products", nichesLabel: "Industries", nichesTitle: "A dedicated customer journey for every industry.", nichesText: "Questions, intake, planning, systems and human handoff match day-to-day operations.", nichesCta: "View all industries" },
    footer: { title: "AI employees that turn customer contact into action.", text: "Our focused products, configured for your industry, systems and exceptions.", analysis: "Book a short assessment", allNiches: "All industries", company: "Autopilots", privacy: "Privacy", terms: "Terms", future: "For the companies of the future." },
    products: { "ai-inboxmedewerker": "AI Inbox Agent", "ai-leadopvolger": "AI Lead Follow-up", "ai-telefoniste": "AI Receptionist", "autopilots-crm": "Autopilots CRM", "leadsmachine-ai": "AI Lead Engine" },
    home: { title: "Autopilots | AI employees for customer contact", description: "Autopilots builds AI employees that handle customer contact, schedule appointments and keep CRM workflows moving.", eyebrow: "Autopilots", heading: "AI employees that turn customer contact into", accent: "a clear next action.", lead: "Our AI products for inbox, lead follow-up, phone, CRM and acquisition — configured around your processes and systems." }
  },
  es: {
    system: { skipToContent: "Ir al contenido principal", footerTagline: "Empleados de IA para atención al cliente y operaciones.", consentTitle: "Tú decides qué mediciones están activas.", consentText: "Las funciones esenciales están siempre activas. La analítica solo comienza tras tu elección y no incluye datos de formularios.", consentReject: "Solo esenciales", consentAccept: "Permitir analítica" },
    navigation: { products: "Productos", niches: "Sectores", process: "Proceso", knowledge: "Conocimientos", crew: "Equipo", appointment: "Reservar cita", order: "Comprar", menu: "Menú", language: "Elegir idioma" },
    header: { productsLabel: "Productos Autopilots", productsTitle: "Nuestros productos de IA para atención al cliente y crecimiento.", productsText: "Una base de producto estable, configurada para los procesos y sistemas de tu sector.", productsCta: "Comparar los productos", nichesLabel: "Sectores", nichesTitle: "Un recorrido de cliente propio para cada sector.", nichesText: "Preguntas, toma de datos, planificación, sistemas y transferencia humana adaptados a la práctica.", nichesCta: "Ver todos los sectores" },
    footer: { title: "Empleados de IA que convierten cada contacto en una acción.", text: "Nuestros productos concretos, configurados para los procesos, sistemas y excepciones de tu sector.", analysis: "Reservar un análisis breve", allNiches: "Todos los sectores", company: "Autopilots", privacy: "Privacidad", terms: "Condiciones", future: "Para las empresas del futuro." },
    products: { "ai-inboxmedewerker": "Agente de bandeja IA", "ai-leadopvolger": "Seguimiento de leads IA", "ai-telefoniste": "Recepcionista IA", "autopilots-crm": "Autopilots CRM", "leadsmachine-ai": "Motor de leads IA" },
    home: { title: "Autopilots | Empleados de IA para atención al cliente", description: "Autopilots crea empleados de IA que atienden clientes, programan citas y mantienen actualizado el CRM.", eyebrow: "Autopilots", heading: "Empleados de IA que convierten cada contacto en", accent: "una acción concreta.", lead: "Nuestros productos de IA para bandeja de entrada, seguimiento, teléfono, CRM y captación, configurados según tus procesos." }
  },
  de: {
    system: { skipToContent: "Zum Hauptinhalt springen", footerTagline: "KI-Mitarbeiter für Kundenkontakt und Betrieb.", consentTitle: "Sie entscheiden, welche Messungen aktiv sind.", consentText: "Notwendige Funktionen sind immer aktiv. Analysen starten erst nach Ihrer Auswahl und enthalten keine Formularinhalte.", consentReject: "Nur notwendig", consentAccept: "Analysen zulassen" },
    navigation: { products: "Produkte", niches: "Branchen", process: "Prozess", knowledge: "Wissen", crew: "Team", appointment: "Termin buchen", order: "Direkt bestellen", menu: "Menü", language: "Sprache wählen" },
    header: { productsLabel: "Autopilots Produkte", productsTitle: "Unsere KI-Produkte für Kundenkontakt und Wachstum.", productsText: "Eine feste Produktbasis, abgestimmt auf die Prozesse und Systeme Ihrer Branche.", productsCta: "Produkte vergleichen", nichesLabel: "Branchen", nichesTitle: "Eine eigene Customer Journey für jede Branche.", nichesText: "Fragen, Aufnahme, Planung, Systeme und menschliche Übergabe passen zur täglichen Praxis.", nichesCta: "Alle Branchen ansehen" },
    footer: { title: "KI-Mitarbeiter, die Kundenkontakt in konkrete Aktionen verwandeln.", text: "Unsere klaren Produkte, abgestimmt auf Prozesse, Systeme und Ausnahmen Ihrer Branche.", analysis: "Kurze Analyse buchen", allNiches: "Alle Branchen", company: "Autopilots", privacy: "Datenschutz", terms: "Bedingungen", future: "Für die Unternehmen der Zukunft." },
    products: { "ai-inboxmedewerker": "KI-Postfachassistent", "ai-leadopvolger": "KI-Lead-Nachverfolgung", "ai-telefoniste": "KI-Telefonassistent", "autopilots-crm": "Autopilots CRM", "leadsmachine-ai": "KI-Leadmaschine" },
    home: { title: "Autopilots | KI-Mitarbeiter für den Kundenkontakt", description: "Autopilots entwickelt KI-Mitarbeiter, die Kundenanfragen bearbeiten, Termine planen und CRM-Prozesse voranbringen.", eyebrow: "Autopilots", heading: "KI-Mitarbeiter, die Kundenkontakt in", accent: "eine konkrete Aktion verwandeln.", lead: "Unsere KI-Produkte für Postfach, Lead-Nachverfolgung, Telefon, CRM und Akquise — passend zu Ihren Prozessen." }
  },
  it: {
    system: { skipToContent: "Vai al contenuto principale", footerTagline: "Collaboratori AI per il contatto clienti e le operazioni.", consentTitle: "Decidi tu quali misurazioni attivare.", consentText: "Le funzioni essenziali sono sempre attive. Le analisi iniziano solo dopo la tua scelta e non includono i dati dei moduli.", consentReject: "Solo essenziali", consentAccept: "Consenti analisi" },
    navigation: { products: "Prodotti", niches: "Settori", process: "Processo", knowledge: "Conoscenza", crew: "Team", appointment: "Prenota un incontro", order: "Ordina", menu: "Menu", language: "Scegli la lingua" },
    header: { productsLabel: "Prodotti Autopilots", productsTitle: "I nostri prodotti AI per il contatto clienti e la crescita.", productsText: "Una base di prodotto stabile, configurata sui processi e i sistemi del tuo settore.", productsCta: "Confronta i prodotti", nichesLabel: "Settori", nichesTitle: "Un customer journey dedicato per ogni settore.", nichesText: "Domande, raccolta dati, pianificazione, sistemi e passaggio umano seguono la pratica quotidiana.", nichesCta: "Vedi tutti i settori" },
    footer: { title: "Collaboratori AI che trasformano il contatto cliente in azione.", text: "I nostri prodotti chiari, configurati sui processi, sistemi ed eccezioni del tuo settore.", analysis: "Prenota una breve analisi", allNiches: "Tutti i settori", company: "Autopilots", privacy: "Privacy", terms: "Condizioni", future: "Per le aziende del futuro." },
    products: { "ai-inboxmedewerker": "Assistente inbox AI", "ai-leadopvolger": "Follow-up lead AI", "ai-telefoniste": "Receptionist AI", "autopilots-crm": "Autopilots CRM", "leadsmachine-ai": "Macchina lead AI" },
    home: { title: "Autopilots | Collaboratori AI per il contatto clienti", description: "Autopilots crea collaboratori AI che gestiscono richieste, appuntamenti e flussi CRM.", eyebrow: "Autopilots", heading: "Collaboratori AI che trasformano il contatto cliente in", accent: "un'azione concreta.", lead: "I nostri prodotti AI per inbox, follow-up, telefono, CRM e acquisizione, configurati intorno ai tuoi processi." }
  },
  fr: {
    system: { skipToContent: "Aller au contenu principal", footerTagline: "Collaborateurs IA pour la relation client et les opérations.", consentTitle: "Vous choisissez les mesures activées.", consentText: "Les fonctions essentielles restent actives. Les statistiques ne démarrent qu’après votre choix et n’incluent aucun contenu de formulaire.", consentReject: "Essentiels uniquement", consentAccept: "Autoriser les statistiques" },
    navigation: { products: "Produits", niches: "Secteurs", process: "Processus", knowledge: "Connaissances", crew: "Équipe", appointment: "Prendre rendez-vous", order: "Commander", menu: "Menu", language: "Choisir la langue" },
    header: { productsLabel: "Produits Autopilots", productsTitle: "Nos produits IA pour la relation client et la croissance.", productsText: "Une base produit stable, configurée selon les processus et systèmes de votre secteur.", productsCta: "Comparer les produits", nichesLabel: "Secteurs", nichesTitle: "Un parcours client adapté à chaque secteur.", nichesText: "Questions, collecte, planification, systèmes et transfert humain suivent la réalité du terrain.", nichesCta: "Voir tous les secteurs" },
    footer: { title: "Des collaborateurs IA qui transforment chaque contact en action.", text: "Nos produits précis, configurés selon les processus, systèmes et exceptions de votre secteur.", analysis: "Planifier une courte analyse", allNiches: "Tous les secteurs", company: "Autopilots", privacy: "Confidentialité", terms: "Conditions", future: "Pour les entreprises de demain." },
    products: { "ai-inboxmedewerker": "Assistant messagerie IA", "ai-leadopvolger": "Suivi de leads IA", "ai-telefoniste": "Standardiste IA", "autopilots-crm": "Autopilots CRM", "leadsmachine-ai": "Machine à leads IA" },
    home: { title: "Autopilots | Collaborateurs IA pour la relation client", description: "Autopilots conçoit des collaborateurs IA qui répondent aux clients, planifient des rendez-vous et alimentent le CRM.", eyebrow: "Autopilots", heading: "Des collaborateurs IA qui transforment chaque contact en", accent: "une action concrète.", lead: "Nos produits IA pour la messagerie, le suivi, le téléphone, le CRM et l'acquisition, configurés selon vos processus." }
  }
};
